### PR TITLE
Add simulator tooltip

### PR DESCRIPTION
**Pull request by kaalleen**
It would be nice to know how to control the simulation from within Ink/Stitch without reading the documentation. This adds a tooltip to the simulator.

### CODE REVIEW

**Comment by lexelby** [comment]
Wonderful!

**Comment by lexelby** [comment]
Regarding the translation strings, do you think it's a problem to have all those tab characters in there?  Will that make it difficult for translators?

**Comment by kaalleen** [comment]
This is my first attempt to add control buttons to the simulator.
They need retooling though,e.g. in case the simulator width is too small, they are badly overlapping and unusable. I have no clue how to fix this for now.

**Comment by lexelby** [comment]
Interesting!  I too have no clue how to fix the sizing issue... I suppose we could enforce a minimum size?  TBH, the simulator view really taxes my GUI knowledge :)

I think we're going to need to run the buttons through `_()`?

**Comment by kaalleen** [comment]
Minimum width is set. At least it is working somehow ;)
Button strings should now be translatable too, thanks for the hint.

**Comment by lexelby** [comment]
Looks great, nice work!  I like the idea of having tooltips for each button instead of a big one for the main window.

**Comment by lexelby** [comment]
Feel free to merge it when you're ready.  It looks good to me now, but I wasn't sure if you had any more work in mind :)

**Comment by kaalleen** [comment]
I wasn't sure myself, there are some things bothering me about it. But if I want to come back to it later, I can do it with an other Pull request ;)

**Comment by lexelby** [comment]
Agreed.  We still have a pretty small userbase and we're very active, so we can quite quickly push out a fix if something goes wrong.  Full steam ahead :)

**Pull request merged**
