### PR TITLE
ParseStyle

### PR DESCRIPTION
**Pull request by kaalleen**
This PR aims at issue #632 
(It also includes changes to the get_style function from the svg_objects branch)

### CODE REVIEW

**Comment by lexelby** [comment]
Oh no! I actually already did some work on fixing this, but I totally forgot to create a pull request.  Sorry about that. :(

My work is in the lexelby/fix-parse-style branch.  I went a different direction and brought in a python module to do the style parsing properly, so we don't have to try to get it right ourselves.

How do you want to handle this?

**Comment by kaalleen** [comment]
Oh sorry, I did not notice.
I leave it up to you, whatever you think is best.

**Comment by lexelby** [comment]
I'd prefer to go with what's in my branch, so that we can avoid implementing our own CSS parser.  I don't have time to turn it into a PR right now though...

**Comment by kaalleen** [comment]
Ok, sure. I can turn it into a pull request if you like.

**Comment by lexelby** [comment]
By all means, go right ahead :)

**Pull request closed without merging**
