### PR TITLE
Circular fill fix

### PR DESCRIPTION
**Pull request by kaalleen**
Ignore travel stitches when processing the bean stitch setting.

### CODE REVIEW

**Comment by george-steel** [comment]
@kaalleen I'm a little late to the party, but what's the point of having the bean stitch setting at all on circular fills. I'm working on something that affects the fills using running stitch and am curious about the motivation behind the setting.

**Comment by kaalleen** [comment]
It's been a requested feature to make thicker lines or to create special patterns when row spacing has higher values.
What are your plans if you don't mind sharing?

**Comment by george-steel** [comment]
@kaalleen I'm working on a new variant of running stitch that can use randomized stitch lengths behaves better when stitching parallel curves. My current even-spacing algorithm works quite well for single running stitch lines, bean stitch, and distant lines (> 1.5mm apart), but produces some nasty Moiré artifacts when parallel curves get too close together (I'm having this problem in a design I'm working on.

I wanted to know if people were actually using distant spacing (which is the only context in which bean stitch makes sense) to know if I need to offer a choice of running stitch algorithm just to switch to the close-spacing version.

**Comment by tyrosinase** [comment]
I do, on both contour and circular (though IIRC contour sometimes starts with an inconvenient underpath).

**Comment by george-steel** [comment]
@tyrosinase Good to know. I'll add a setting for choice of running stitch algorithm. As someone who uses both versions, do you think the default should be for close spacing for distant spacing (the current algorithm).

**Comment by tyrosinase** [comment]
Tough call. Sometimes I like the moiré, sometimes it's distracting. I'm usually in favor of "default is the way it originally went" so people aren't surprised by it, but OTOH I suspect I'll pick the randomized version more often going forward so... either way works.

**Comment by kaalleen** [comment]
Interesting feature :)

> do you think the default should be for close spacing for distant spacing (the current algorithm)

Whenever possible keep the previous defaults.

**Pull request merged**
