### PR TITLE
Update pyembroidery submodule

### PR DESCRIPTION
**Pull request by MangaValk**
should fix https://github.com/inkstitch/inkstitch/issues/882

### CODE REVIEW

**Comment by MangaValk** [comment]
since making a build on windows seems horible, can someone make a new build using the newest pyembroidery? thanks

**Comment by lexelby** [comment]
Hi, thanks for the PR!  I've given you write access to this repository.  That will let you push your branch directly so that your PR will use our build system.

We try to name our branches "usernsme/something" so we can keep things organized.

Thanks again!

**Comment by MangaValk** [comment]
> Hi, thanks for the PR! I've given you write access to this repository. That will let you push your branch directly so that your PR will use our build system.
> 
> We try to name our branches "usernsme/something" so we can keep things organized.
> 
> Thanks again!

Thank you! the build is working now 👍 
glad to have helped some on this awesome project

**Comment by lexelby** [comment]
Awesome!  Now you can find your binaries here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-mangavalk-update_pyembroidery

Give it a once-over and make sure it works properly, and report back.  Once you've done that, one of us will approve.

> glad to have helped some on this awesome project

We really appreciate it.  Feel free to pitch in on other stuff if anything catches your interest. :)

**Comment by MangaValk** [comment]
> Awesome! Now you can find your binaries here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-mangavalk-update_pyembroidery
> 
> Give it a once-over and make sure it works properly, and report back. Once you've done that, one of us will approve.
> 
> > glad to have helped some on this awesome project
> 
> We really appreciate it. Feel free to pitch in on other stuff if anything catches your interest. :)

The Windows version is working without any issues now :) 
can't say anything about the linuc and mac versions tho.

**Pull request merged**
