### PR TITLE
simulator timeline

### LINKED ISSUE #91: Simulate window flickers on Windows
When running in Windows, the simulate view flickers occasionally.  It's still usable, but the flickering is disruptive.

### LINKED ISSUE #267: Timeline and Stitch Counter
I was wondering if it would be doable to add a timeline and a simple stitch counter (something like current stitch / total stitch) to the Simulate module?

Something that I can pause the animation, scrub through manually and find the exact stitch count that I'm on in a pattern.

One possible use case would be to find the exact stitch count to add specialty functions to individual stitches in an exported CSV file format and then convert that CSV file back into a raw stitch file that would accept said commands.

Thoughts?

### PR DESCRIPTION
**Pull request by kaalleen**
This is the very first version of a simulator timeline - testing is appreciated though.

1. on high speed level there is an odd behavior of jumping adding/removing whole blocks of lines
2. it would be nice to get commands (trims, stops) into the list of lines to count them too (they disappear within color_block_to_point_lists)
3. how is the flickering issue in windows by now (i didn't have it in mind when i modified the simulator, so it might need some attention)

fixes #91 
closes #267

### CODE REVIEW

**Comment by lexelby** [comment]
Wow, so cool! :D  Nice work so far.  I also get issue 1 you mentioned above -- not sure what that is, from looking through the code.

One thing I noticed is that there can occasionally be bigger gaps between rows in a large section of fill stitch.  I think that has to do with the lines being drawn without anti-aliasing.  My original code used a GraphicsContext which defaults to anti-aliased drawing, but it looks like GraphicsContext doesn't have the DrawLineList() function?  I guess maybe if we want speed we can't have anti-aliasing, which is fine.

**Comment by lexelby** [comment]
I think I figured out why it gets stuck at high speeds.  If `iterate_frames()` takes longer than `frame_period` to render a frame then the Timer gives up and never fires again, because it missed one of its firing times.  With a 24000-stitch design, I'm seeing draw_one_frame take as much as 200ms toward the end.

Fortunately there's an easy fix!  Instead of using `self.timer.Start()`, we can use `self.timer.StartOnce(self.frame_period)`.  Then we can call `self.timer.StartOnce(self.frame_period)` again in `iterate_frames()` after rendering the frame.  In fact, we can measure the time it takes to call `draw_one_frame()` and subtract that from the `frame_period`.

**Comment by kaalleen** [comment]
> Fortunately there's an easy fix! Instead of using self.timer.Start(), we can use self.timer.StartOnce(self.frame_period)

Oh thanks, that helped!

>  In fact, we can measure the time it takes to call draw_one_frame() and subtract that from the frame_period

Sounds good... but don't forget, I am just a beginner ;)
How do we do this?

**Comment by wwderw** [comment]
>how is the flickering issue in windows by now (i didn't have it in mind when i modified the simulator, so it might need some attention)

I didn't get flickering of the main simulation, but one when the stitch counter moves to the upper left, on Windows, that flashes while the simulation is going.  It does not on the Linux version.

On Windows, the symbols on the buttons for the timeline, also do not show up, they do on Linux.

I also noticed that the timeline goes from being on top of those "media" buttons to the top left on both versions.  Is that on purpose?

simulator testing

All in all, I'm liking how it looks.  I think it's on the right track that's for sure.

**Comment by kaalleen** [comment]
Thanks for your review. ... wow, it looks terrible ;)

The text flickering is caused by using something called static text... i suppose it's not made to be changing all the time, we should draw it to the panel as well, this might solve this issue.

I had someone test it with windows and it did look fine, slider was on the bottom and symbols were showing up (except for the black background behind the panel, which is actually supposed to be white). But seeing your screenshot... this cannot stay as is at all.

Which windows version are you using?

**Comment by kaalleen** [comment]
Oh, now I understand... the timeline moves up there when you are changing the params, is that right?

**Comment by lexelby** [comment]
>> In fact, we can measure the time it takes to call draw_one_frame() and subtract  that from the frame_period
> 
> Sounds good... but don't forget, I am just a beginner ;)
> How do we do this?

Beginner or not, you've long since surpassed my wxPython knowledge. :)

Sorry for being vague in my previous comment; I struggle with knowing when to share more detail, versus not wanting to jump in with uninvited code suggestions.

Here's what I was thinking:

```python
import time

...

            start = time.time()
            self.draw_one_frame()
            duration = time.time() - start
            duration_ms = int(duration * 1000)
            time_to_next_frame = self.frame_period - duration_ms
            self.timer.StartOnce(time_to_next_frame)
```

The only problem with this approach is that `time_to_next_frame` may be less than zero if it took longer than `frame_period` to render the frame, so we'll need to check that too.

**Comment by kaalleen** [comment]
This should fix the jumping timeline ... but ti pushes the simulation to an unwanted size/position ;)
I'll work on it tomorrow.

**Comment by lexelby** [comment]
Aw, did the unicode media symbols not work out?  I'm actually a big fan of that if we can get it to work cross-platform.

**Comment by lexelby** [comment]
Here's another idea: what if we get rid of the separation between speed up/slow down and simulate forward/backward?  It seems to me that it would be natural to press the right arrow a bunch to make it go faster, then the left arrow slows it down until it's almost stopped, then if I hit the left arrow even more, it starts going backward.  More left arrows means it'd go even faster backward.

What do you think?

**Comment by kaalleen** [comment]
> Sorry for being vague in my previous comment; I struggle with knowing when to share more detail, versus not wanting to jump in with uninvited code suggestions.

Oh, that's no problem, I can ask if I don't understand a thing ;)

> Aw, did the unicode media symbols not work out? I'm actually a big fan of that if we can get it to work cross-platform.

Sorry for being so tight-lipped yesterday and removing them without saying a word.
Cross-platform is the issue here...  I don't know how to make it work cross-platform and testing it, is not a lot of fun. Maybe we should think about images instead, but I rather use unicode. I didn't give up on it yet, but I will save that for later.

> what if we get rid of the separation between speed up/slow down and simulate forward/backward?

The new version has it now. I think we should leave the speed up, slow down functionality active - at least the shortcuts... You could speed up the simulation so much, that you loose the chance to make it slower again. I limited the speed levels... but I didn't want to be too drastic, because you might want it to be very fast with larger designs. What do you think?

**Comment by lexelby** [comment]
Yay!  I'm not at my computer right now, but I'm excited to try this new version out later!

> Sorry for being so tight-lipped yesterday and removing them without saying a word.
Cross-platform is the issue here... I don't know how to make it work cross-platform and testing it, is not a lot of fun. Maybe we should think about images instead, but I rather use unicode. I didn't give up on it yet, but I will save that for later.

I figured, and no worries about being tight-lipped; I just figured you were busy with non-inkstitch stuff. :)  Saving this for later is fine with me.

**Comment by Metallicow** [comment]
Ok I downloaded and installed inkscape-0.92.3-x86.exe and downloaded and extracted inkstitch-v1.17.0-win32.zip into C:\Users\%USERNAME%\AppData\Roaming\inkscape\extensions. Fired inscape up and found your simulate extension and loaded a sample svg file from the repo. I see the flickering and and some things could be optimized a bit(dc drawing would be better than StaticText for this overlay if doublebuffering didnt fix it). Then went to drop this PulReqz branch on top only to find that just an inkstich.py and a bin directory was in the download. How do you run from source? I am using Py2.7.x and wxPy Phoenix devel. There is only two files in this PulReqz that needs patched. how should I do this in the extention folder. or was the main download compiled? looks like pyinstaller...

**Comment by lexelby** [comment]
Correct, we're building using PyInstaller.  The easiest way to test this branch would be to grab the dev-build from here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-simulator-timeline

Unzip that into your extensions dir, replacing existing files from the original v1.17.0 ZIP file.

Running from source is possible, but it takes a little setup.  Install the requirements from the `requirements.txt` file and symlink inkstitch.py and everything in inx/ into your Inkscape extensions dir.  That ought to get you up and running, I think.

**Comment by Metallicow** [comment]
k. I managed to drop the dev build over the reg build in the ext dir. From first review, I would say you are on the right track but there are a few issues that need addressed.
untitled

Important stuff that NEEDS fixed.
* Main frame is NOT resizable! Moving the window works fine, but the first thing a real user will try and do is to resize the frame also so they can inspect the Inkscape window underneath which holds the real data. The problem with this is that when I try to resize the main frame... It is programatically being force fed back to me right in the middle of the screen at the OS res(whatever you hardcoded). Do not hardcode this! (This fires every wx.EVT_SIZE) The window should be resizable(there is a frame flag bit but probably isnt necessary) but scaling an image could be problematic, since this is a simulation and is primarily meant for debugging or finding a particular stitch/line in the file you want to patch. If you need to maintain aspect ratio, use a scrolled window.

Minor stuff and/or eyecandy/usability fixes.
* I of course need to get to a particular stitch number so, I would remove the slider flag bit and replace the updating number with a editable TextCtrl and some static texts. I would want to EX: type 1234 into the slider/TextCtrl and when I hit reset; have drawing reset at that point in time prossibly for 30-50 stitches or whatever.
* Individual stitch increment. +1 or -1. single frame like a movie editor would have.
* Speed controls should be separated. I shouldnt have to click << 12 times to get to x-6 from x6(plus all the calculations in between which freezes up the ui). Speed buttons control the speed attribute and a forwards/reverse button controls the direction the machine will operate, just like a vehicle.
* Drawing the stitch number on top with dc is subjective, but the speed mult is not needed there. Draw window is for drawing, not eating up extra draw cycles/resources. I would move all that stuff into the control panel.
* DragScroller mixin. This is purely fancy stuff, but since I would use a wx.ScrolledWindow or wx.ScrolledPanel for the drawing, this makes navigation easier. see DragScroller.py in the wxPy demo.
* Use flags and border tolerances and proper sizer stuff and window flags as seen in attached mockup so that everything will look native and size right on various platforms. sizer.Layout() will usually take care of everything properly unless you have a spaghetti widget layout.
* Keybindings. It might be useful to set focus to the pause button upon frame construction, so that the user can simply press spacebar to pause and start animation. NOTE: spacebar will activate focused widget, so if you want spacebar to only activate animation, then some extra coding will be required when a focus event occurs on anything else. Ctrl+F, Ctrl+B could toggle the anim direction similar to the way @tatarize  did his sample. Note: These should be binded to the wx.Menu properly so they work everywhere. You can just hide the main frame menubar so it cant be seen.
* wx.Slider itself could be optional(opting for just a TextCtrl). While I like sliders and they are nice to use. They will become a real problem with files that have billions of stitches moving just a pixel.
* optimize everything but keep it readable and reverse engineerable. for loop vs list comprehension. no dots. enumerate. etc. etc.

Other Thoughts.
* This really should be a singlefile standalone app/plugin. It could run off a file(wx/pyside/tk/etc), Embroidermodder python bindings, pyembroidery, inkscape, or whatever depending on the situation and how it is coded.

Ok. now that I wrote my review. Lets reverse engineer your code and make a mockup that doesnt require benchmarking. Dev in SourceCoder, see attachment sample app.
[mockup.zip](https://github.com/inkstitch/inkstitch/files/2317447/mockup.zip)

mockup


Other Resources.
wxPython [Docs](https://wxpython.org/Phoenix/docs/html/), [Demos](https://github.com/wxWidgets/Phoenix/tree/master/demo), [Builds](https://wxpython.org/Phoenix/snapshot-builds/) and whatnot can be found here.

Will wait for next code iteration/review. and will try to get source running in extensions locally. Cheers :)

p.s. Inkscape seems to be usable now. Since the .7 slow versions. +11 thumbsup to the guys who did the rewrite!

**Comment by lexelby** [comment]
Thanks for your thoughtful review!

A lot of what you've touched on here is definitely in our minds.  We're all still actively learning wxPython, so the code is evolving quickly.  Resize (and zoom/drag) are definitely things we'd love to do, but there's a lot more learning to be done :)

Individual stitch increment and entering a specific stitch number: great ideas!

> Speed controls should be separated.

It's funny, we just switched from having speed and playback direction separate to the current version where they're merged.  I haven't even had a chance to test it yet.  It's very useful to hear your user perspective on this.

Mockup: awesome!  So pretty!  Hopefully we can integrate this design sometime soon.  I love the nice lines around the two sections (the controls and the stitch view).


While we have you here... can I pick your brain about some wxPython stuff? :)  DrawLineList() is quite fast, but it seems to me that "billions of stitches" probably wouldn't be possible.  In my test with ~25000 stitches, it took over 250ms to draw a frame.  Are we missing some optimization?

The other thing about DrawLineList() is that it's not anti-aliased.  We previously used wx.GraphicsContext to get anti-aliased lines, but GraphicsContext doesn't have DrawLineList().  Would you expect GraphicsContext.DrawLines() to be heavily optimized like dc.DrawLineList()?

**Comment by lexelby** [comment]
@kaalleen Check this out: https://github.com/wxWidgets/Phoenix/blob/master/demo/DragScroller.py

Much easier than I thought it would be!  Perhaps we can work on it down the road :)

**Comment by lexelby** [comment]
You know, after testing it, I think @metallicow's spot on about keeping animation direction and speed separate.  Sorry for leading you down the wrong path, @kaalleen :(

**Comment by lexelby** [comment]
@kaalleen Just tested the latest version on my windows 10 VM.  No flickering!!! I definitely saw flickering before, so I think you've fixed it!

I also did _not_ see the weird thing wwderw saw with the slider going to the upper left.  Everything looked just as it does on Linux.

**Comment by Metallicow** [comment]
DrawLineList() is just calling the underlying wxWidgets functions which is cFamily so yes it will be basically the fastest you will get out of wxPy unless you are using wxWidgets or some other lib. What you have here is 2D drawing and the numbercrunching portion sent to will of course be better using the official bindings instead of python. If you can achieve 30fps that is ok. if you can do 60fps. that is fine. Anything more is essentially overkill as the human eye wont be able to tell the difference anyway. implement the different ways as seen in the https://github.com/wxWidgets/Phoenix/tree/master/samples/roses sample so that you can toggle various options on/off, then inject some timeit tests into it for a benchmark. make sure the tests run at least 3 times and for at least 1 min to be a better idea of the speed difference of the various drawing options.

Now if I was to stick pyembroidery inside my micropython board and stitch that inside a hacky sack with a mocap ball and toss it across the room I would probably direct you to this answer https://www.reddit.com/r/vulkan/comments/77j2sz/when_to_use_vulkan_vs_opengl/ at which point you are talking about multi-threading, multi-processing and a realtime game engine(Ex: blender eevee as open source)

You could have things setup like photoshop/krita where essentially you have a background thread/process doing all the calculations and cache them in your "photoalbum"/memory allowance, then when the gui is done drawing a imageframe it just picks the next one out of the bag and draws it in succession. 
Think of it this way... I might run a site where you can buy a custom embroidered shirt. You take a picture and upload it. The server takes the image and pseudo realistically renders it and sends back an image and slaps that on a white T-shirt. While the user is deciding to click the 'pay me button' the server is still working on the finished product file and saved in a cache. If the user sends me money the receipt has the attached work order and can be sent to whatever local shop you choose to pick it up at. At this point the shop worker loads the work order file into their machine, gets whatever colors they will need, positions the shirt and starts the manufacturing process.
All in all what you are doing is guessing what the user will do next and do it before the user actually decides to. So for example the main GUI process is just drawing a frame. The other thread(s) is doing x other frames calculations while the main one is drawing.

Whenever you are dealing with graphics, yes speed is critical. So the number crunching should be done with the fastest option.
""Sure, in terms of computer graphics, then every millisecond counts. But if you're making 2D side scrolling game. Then would it be important if the difference was 100fps, but you already got 200fps with OpenGL?""

**Comment by Metallicow** [comment]
Overall when Wrye wrote the Bashed Patch for Wrye Bash it was done in python. It wasn't until after Wrye retired basically that cBash was developed by Waruddar. But to give you a basic idea. My load order would be around 250 mods and pBash patch would take about 15 min to build. Building a cBash patch of the same load order takes about 15 seconds. Bashed patch doesn't deal with graphics, just records, but you can get the basic idea on performance differences in the 2 different implementations.

**Comment by Metallicow** [comment]
If at some point your users need more performance for whatever reasons or have some wacky idea they want to implement(like stitching the embroidermodder logo startup screen easter egg), then your next step/option would be to go full 2/3D. This is all done with a custom written widget using GLCanvas and pyopengl. As you can see my 10 line python snakey icon can be pixel stitched in 2dplane in a 3d environment. Meshes can be imported and rotated like in blender/3Dcad, so if at some point users want a product render you will need a tshirt mesh(or whatever) and the embroiderfile to pseudorender and setup gl lighting. Also overlays can be done(the white plane). This might be overkill for a svg designer for inkscape, but it depends on how much time you want to spend developing the addon. I do not have time to teach you opengl or 3D modeling, so consider that also. But just if you are curious... this is how I pulled it off in wxPython... so no... it isn't exactly the same as a scrolled window. 
pyopengl_wxpy

Another Note: Dont try to get PyGame working in wxPy. Embedding PyGame in wxPy is problematic tho(that is SDLWindow) and crashes frequently and breaks everytime pygame releases a new version. PyGame's license isn't the greatest either, so developing a public domain pygame alternative would be better done with PySDL2. Just a thought...
In the end, the bottom line is how much money/time you got to throw at the tool, so if you can afford to pay someone to do the extra fancy stuff, it really all boils down to donations/sales. If you make a quality tool, then a percentage of the users will give back...

**Comment by Metallicow** [comment]
@kaalleen I haven't even looked over the code yet or got source running locally yet, but as far as optimizing python code this would be more of a learned reaction when developing your code. Ex: I instinctively write list comps everywhere I can from the getgo unless a for loop is necessary and always pull things in locally and kill all dots. This of course took me a long time reading and testing various bits of my applications code. And after you get done fixing a massive 500+ file application to speed everything up you can, it sorta becomes like tying a shoe or riding a bike.

Start by reading this. https://wiki.python.org/moin/PythonSpeed/PerformanceTips
Next watch this. https://www.programmingtalks.org/talk/transforming-code-into-beautiful-idiomatic-python/
Before finalizing, look at your code and change all these little things if you see them in your code.
Watch the python core developers other talks for other tips and tricks, etc.
Other things like wxPy stuff can usually be benchmarked with a simple timeit test if you have any doubts whether a different implementation might be faster. Ex: benchmark two functions that do the same thing but in different ways and of course use the faster one. Just remember the zen... Readability counts.
Most widget devs browse the mailing lists too and help users with small issues and people starting wxPython.

Killing dots basic example

I see uses of enumerate and izip so this is good, just pull everything unnecessary out of your loops.

This is ez spotable nono for example. If you take all the dots out of the loops, un needed func calls, etc and timeit you will see a performance increase. I see quite a few dots in those inner loops. Every dot is a lookup in the grand scheme of everything.
```
    def color_to_pen(self, color):
        return wx.Pen(color.visible_on_white.rgb)

    def stitch_plan_to_lines(self, stitch_plan):
        self.pens = []
        self.lines = []

        for color_block in stitch_plan:
            pen = self.color_to_pen(color_block.color)
```
function calls are expensive.
```
        wxPen = wx.Pen
        for color_block in stitch_plan:
            pen = wxPen(color_block.color.visible_on_white.rgb)
```

also you might be able to shorten `self.lines.append` to just `lines_append`, this would kill quite a few more inner loop dots and assign it all after the loop finished, but this would need testing to ensure it is still working as intended.

**Comment by lexelby** [comment]
Thanks for the tips!

I'm having a bit of a hard time agreeing with the justification for "killing all dots".  For example, the code you just quoted is only run once, during the initialization of the simulator.  I don't think the incremental performance boost is worth it when you consider the loss of readability.  I think we may agree though, because I bet that's exactly what you meant by this:

> Just remember the zen... Readability counts.

It might well be worth doing this kind of optimization in the `draw_one_frame()` function.  We'll have to give it a go (though maybe not in this PR).

With @kaalleen learning programming, Python, and wxPython all at once, I'd suggest emphasizing readability first and only adding targeted optimizations where truly necessary.

Again, I think we probably agree deep down.  It's all a balance, optimization versus readability :)

**Comment by lexelby** [comment]
Looks like GraphicsContext can draw a bunch of anti-aliased lines in one frame, possibly even faster than `dc.DrawLineList()`!  I modified `mockup.py` as follows:

```
class DrawingPanel(wx.Panel):
    """"""
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.BORDER_SUNKEN, name='panel'):
        """"""
        wx.Panel.__init__(self, parent, id, pos, size, style, name)

        self.SetBackgroundColour('#FFFFFF')
        self.SetDoubleBuffered(True)

        self.Bind(wx.EVT_PAINT, self.OnPaint)
        self.lines = []
        for i in xrange(25000):
            self.lines.append((i % 3, i % 50))


    def OnPaint(self, e):
        dc = wx.PaintDC(self)
        canvas = wx.GraphicsContext.Create(dc)
        pen = wx.Pen((0, 0, 0))
        canvas.SetPen(pen)

        start = time.time()
        canvas.DrawLines(self.lines)
        duration = (time.time() - start) * 1000
        print "draw took:", duration
```

For 25000 lines, it took 25-50ms.  Since we'll be drawing groups of many lines all with the same color, this should work just fine.

@kaalleen I'd be happy to make a pass through the code.  While I do, I might see if it's possible to integrate @Metallicow's design mockup.  Not sure how hard that will be, we'll see.

**Comment by Metallicow** [comment]
The mockup was just intended to be a layout recreation. Not a example of the fastest way to draw. As long as you are not using a pure python implementation of a dc then you shouldn't have no real issues with drawing as most everything is calling the wxWidgets cFamily stuff.

As far as benchmarking: reasons to use the builtin python module instead of a quick copy and paste of time. https://stackoverflow.com/questions/17579357/time-time-vs-timeit-timeit 

My issue with the optimization was with the actual performance when loading simulate in inkscape. The test file takes roughly 6 seconds to get all records chewed up and load into the gui at 47728. I timed this by actually counting myself. So if we round that file to 50k at 6 seconds and do a bit of math then it will take 2 minutes to load a million stitch file, just by guestimates. so this [file](https://static1.squarespace.com/static/537b8325e4b065b57c13cdef/t/54049146e4b0f88422b313d7/1409585501563/?format=1000w) would take maybe 3 1/2 minutes to load() with python. It will quickly become a coffeebreak reminder the more records that need processed. Another issue is that the wxPy gui is blocking any interaction with the inkscape window also, so basically that means closing the addon. editing some stitches and then reloading simulate and chewing up the records all over again.

**Comment by Metallicow** [comment]
@lexelby 
Ok got a min to try and do a manual setup...
Dropped inkstitch.py, .inx files and lib dir from download into extensions dir.
got error for missing shapely. Used pip to install the included shapely wheel.
fired up inkscape and simulate gives me this error:
```
Traceback (most recent call last):
  File "inkstitch.py", line 4, in <module>
    from lib.utils import save_stderr, restore_stderr
  File "lib/utils/__init__.py", line 1, in <module>
    from geometry import *
  File "lib/utils/geometry.py", line 1, in <module>
    from shapely.geometry import LineString, Point as ShapelyPoint
ImportError: No module named shapely.geometry
```
Any idea whats going on here? Why is the wheel in the repo?

**Comment by lexelby** [comment]
Question: how often do million-stitch designs show up?  Is that common?

The Shapely wheel is in the repo because pypi didn't have a windows wheel available, and the source I found one from specifically requested that we not download it using automated scripts (e.g. our CI setup).

Are you running in windows?  If so, the problem is that Inkscape includes its own Python that's entirely separate from the one you installed Shapely in using `pip install shapely`. This causes huge headaches for setting up a development env in windows. :(  It's part of the reason we're using pyinstaller.

If you have a Linux machine or VM handy, I'd recommend doing your dev work there.  Otherwise, you'll need to install pip inside Inkscape's python and install the modules there.  Last time I tried that I couldn't get it to work.

**Comment by lexelby** [comment]
Okay, got a little carried away.  I've pushed a WIP version that is pretty interesting. Some notes about it:

I've restructured it around the design in `mockup.py`.  I really like the look of it with the separate bordered panes.  Keeping the code for the drawing pane and the control pane in separate classes is nice, too.

I totally reworked how the rendering speed and frame rate are handled.  The control pane sets a desired number of stitches per second, and the drawing pane does its best to hit that.  It does this by measuring how long each frame takes to render, and then figures out how many stitches it should increment by in each frame in order to hit the desired stitches per second.  The result is a smooth, consistent animation regardless of how long each individual frame takes to render.

Using `GraphicsContext.DrawLines()` dramatically simplifies the parsing of the stitch plan.  `GraphicsContext.DrawLines()` takes a series of points and draw lines between each successive point, so we don't have to convert into discrete line segments.

`GraphicsContext` also has another major benefit: transform support.  It can scale and move the design automatically without our having to re-process the point list ourselves.  This will make zoom/pan easy to implement and efficient.

One stumbling block was the fact that wx.Pen only supports line widths in even integer sizes.  To get around this, I scale up the stitch coordinates by a factor of 10, and then scale back down using `GraphicsContext.SetTransform()`.  The result is that we can effectively draw lines thinner than one pixel.  They come out looking nice due to the anti-aliasing support.

At the moment, just the UI controls work.  I plan to integrate the old code for keyboard shortcuts and window position/size as I go.  I just wanted to get this in front of you folks so you could see what I'd managed to do :)

Oh, and one more thing: I added an input box that contains the current stitch number (updated in real-time), and you can edit it to change to a specific stitch.

I think I'll go to bed now.  @kaalleen feel free to take over and push more commits while I slumber :)

**Comment by Metallicow** [comment]
Sorry but I've spent enough time on this tonight and only figured out this. I can always manage to get blender working, krita is a bit more of a pain cause linux folks think windows admin users should be limited for some odd reason. A 10 year old can unzip a portable python installation and have a hay day... But this. omg there are no words to express it. why just this one...?
```
C:\InkscapePortable\App\Inkscape>python
Python 2.7.14 (default, Jan 24 2018, 14:52:47)  [GCC 7.2.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\InkscapePortable\App\Inkscape\lib\python2.7\site-packages\wx-4.0.0-msw-phoenix/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\InkscapePortable\App\Inkscape\lib\python2.7\site-packages\wx-4.0.0-msw-phoenix/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: DLL load failed: The specified module could not be found.
>>>
```
Ill try to figure this out later....

As far as the bigger big files, usually they are art pieces, tapestries, banners or just a bunch of merged smaller designs into a single file. Not real often, but it depends on how you look at it really(folks would give us files just to inspect them test with our/their software). If you have a machine big enough to do that much then I see no reason not to test its limits. Usually bigger stuff like that quilted stuff hanging on walls in churches and banners for schools sometimes. The design Jon decided on was a cad one for Embroidermodder and he really did understand parametric modeling and understood the type of conflict detection bashed patch could do, yea he could have probably very easily imported a bunch of models chew them up and make a bigger file. As far as optimizing material he was always looking at various algorithms to reduce material cost also for the company. At one point he was looking at stuff like this. https://github.com/Jack000/SVGnest A file setup like this could very well have billion stitches if done on a quilting machine. And of course if I spent a month or so designing a nice piece of art I sure would have at least 1 made(maybe not a quilt). Costuming was something we was looking into also. If you unwrap a UV from a 3d model the line edges are essentially the fold and cut pattern. Most folks do this with paper tho tho instead of clothing. I toy around with air brushes also so the files could easily be adapted to cnc spraying for example, at which point 2 colors become a gradient. The possibilities are nearly endless when you got guys 3d printing cupcakes right. lol

**Comment by lexelby** [comment]
More stuff:

  * integrated @kaalleen's keyboard shortcut code
  * forward/backward one stitch (still need to add buttons)
  * handle window size entirely outside of simulator
  * automatically scale the design to fit in the window

The last one is especially fun.  Try resizing the window while the simulation is going.

**Comment by lexelby** [comment]
Added zoom/pan support.  When zooming, the design stays in the same place relative to the mouse pointer.  Figuring that math out made my brain hurt.

**Comment by Metallicow** [comment]
@kaalleen Here is a StaticText sample with SetDoubleBuffered(True) on the parent.
Not sure what the flickering issue was, but I have no issues with it on windows. One thing to note tho when using double buffering is that it should be properly checked on all platforms. IIRC Robin and mac users say certain things are already double buffered on mac, so this would only decrease performance, so keep that in mind. Proper checks in code for the correct OS is not always necessary, but some comments as to why you are double buffering helps others down the line when they come across it. Hope this helps.

[NoFlickerStaticText.zip](https://github.com/inkstitch/inkstitch/files/2322993/NoFlickerStaticText.zip)

Also, Timers are hardcoded at 10 or 15 in Windows IIRC, so doing Start(1) wont actually do it that fast unless you have a few hacks up your sleeve.

**Comment by lexelby** [comment]
@wwderw This last commit is for you.  The simulator window now shows the command (STITCH, TRIM, STOP, JUMP, COLOR CHANGE).  I took care to ensure that if you save as CSV, the stitch numbers you see in the UI match exactly with what you get in the CSV.  That should allow you to edit to your heart's content.

**Comment by wwderw** [comment]
YYYIIIIPPPPPIIIIIEEEEE!!!!!

I saw where it said stitch, jump etc on the appropriate spot as well.  Awesome.

That will definitely make it easier for me to apply those niche codes that I like to use.

Thank you so much!

**Comment by lexelby** [comment]
:D!  Glad you like it :)

Seems to mostly work on windows.  The labels on the slider seem to get cut off.  Not sure what that's about, but it's not that big a deal since the stitch box shows the current stitch just fine.  It also doesn't seem to be getting EVT_SIZE events on the panel.  Shrug.  The basics work fine.

I think this is pretty much ready to ship.  Could folks give this a test on various platforms?

**Comment by lexelby** [comment]
@kaalleen I realize that you asked only for help cleaning up your code, and I ended up reworking a lot of it... I hope I didn't offend you.  If I did, I'm very sorry and I hope I can make amends.

On the other hand, perhaps your quietness of the past few days only indicates that you're happily occupied with other things in your life, in which case carry on. :)

**Comment by kaalleen** [comment]
@lexelby No worries, I am all fine with changes you make ;)
I just have been terribly busy. Sorry to make you think it could have been that.

@Metallicow Thank you for your explanations, that will help me whole a lot when I do more stuff with python - or whatever language I'll have to use.

> IIRC Robin and mac users say certain things are already double buffered on mac, so this would only decrease performance, so keep that in mind.

That's what I tried to prevent with switching to AutoBufferedPaint or something like that. It will check if buffering is already on or not. I had no time looking to the more recent simulator code or your zip file for static text, but I think it's not relevant anymore. When I find the time I will look at it anyway - the curious mind ;)

**Comment by lexelby** [comment]
Oh good.  I think I'm just worried because things have been on edge lately. :)

Oh, is that what the AutoBuffered thing is for?  I think I accidentally removed that.  I'll have to readd it if you don't get to it first.

**Comment by lexelby** [comment]
This latest commit allows running the simulator by itself on any supported embroidery file:

```
PYTHONPATH=/usr/share/inkscape/extensions python -m lib.simulator path/to/myfile.jef
```

We could even package it as a stand-alone executable using PyInstaller.

**Pull request merged**
