### PR TITLE
stagger split satin rows

### PR DESCRIPTION
**Pull request by lexelby**
This adds a staggering option for split satin.  

image
image

It also adds a new "S" stitch Satin method (second picture) which makes the staggering line up more nicely.  You can also use S stitch to turn a satin into a new kind of curved fill stitch!

Staggering is accessed through the new "split method" option.  The current split method is the default (called "default" in the menu).  There's also a new "simple" method that just splits at the maximum stitch length you give it, without trying to split an even number of times.

### CODE REVIEW

**Comment by lexelby** [comment]
I couldn't resist, while I was in there I added a new satin method, "Zig-zag".  @tyrosinase I think this is something you've  wanted: a way to do the same style of zig-zag as simple satin, but in a satin column.

**Comment by tyrosinase** [comment]
Just loaded up the release because I was absurdly-oversizing some satins and 2.2.0 was just sparse around the curves. Didn't play with any of the new features yet but it did do a much better job.

Came out pretty nice for a font that was never designed for this size (if I'd paid closer attention I would have nudged the max-length to take out that short-run split in the lower right of the W, but whatever).

IMG_6220

I look forward to breaking this in ways no one ever expected.

**Review by kaalleen — APPROVED** [review]

**Comment by george-steel** [comment]
@lexelby I missed this when you wrote it, but we should probably split the default method into "even" and "random-phase" methods as they are entirely different. I would also suggest changing the UI text from "simple" to "from first rail" to emphasize that it is asymmetric.

**Comment by lexelby** [comment]
I'm not sure I understand, would you mind throwing together a PR?

**Pull request merged**
