### PR TITLE
Update of wxPython and inkscape

### PR DESCRIPTION
**Pull request by AkiraNorthstar**
Update wxPython to 4.0.3 and inkscape to 0.92.3 (always stable releases)
Inkscape Changelog: https://inkscape.org/en/release/0.92.3/
wxPython Changelog: https://wxpython.org/news/wxpython-4.0.3-release/index.html

### CODE REVIEW

**Comment by lexelby** [comment]
> Invalid output generated from extensions no longer makes Inkscape crash 

!!

Totally upgrading my inkscape now!

**Comment by AkiraNorthstar** [comment]
Jep!
Eventually it fixes the #118 issue.
wxPython in Version 4.0.2 has many fixes too [4.0.2](https://wxpython.org/news/wxpython-4.0.2-release/index.html)

**Comment by lexelby** [comment]
It fixes #118? Are you sure?

**Comment by AkiraNorthstar** [comment]
If there a (bunch) diacritic(s) in a directory name it will now work.
If the filename have diacritics it wouldn't work and shows the error as in issue #118.

**Comment by lexelby** [comment]
> If there a (bunch) diacritic(s) in a directory name it will now work.

Unfortunately, they're referring to an Inkscape issue, but I'm pretty sure #118 is a python issue in Ink/Stitch.

**Pull request merged**
