### PR TITLE
Multiple Underlays for Fill

### PR DESCRIPTION
**Pull request by kaalleen**
This will allow to add multiple underlays for fill elements.
It will be "activated" through adding a comma-seperated list of fill underlay angles.
What do you think, does it make sense?

### CODE REVIEW

**Comment by lexelby** [comment]
Wow, this is awesome!! I've wanted this feature for ages but I  couldn't see any way to do it without rewriting the UI.  This gives us the feature now, and with so little new code!  Love it.

I think we can probably make a much nicer interface in electron, but it's way better to get this feature out now as it is rather than making folks wait.

**Comment by kaalleen** [comment]
Glad you like it!

My thought was too, that with the new surface we can create a much more user friendly and also more flexible version of multiple underlays (not only an adjustable angle).

Do you think this method is "future proven"? I want to avoid incompatibility issues at a later time.

**Comment by lexelby** [comment]
It's such an elegant and simple change that I don't think it could cause any problems in the future.  At worst we could roll back the change entirely without much difficulty,  but I don't think it will come to that.

In the future, I imagine giving the user the ability to add an arbitrary number of layers of fill stitch.  No need to distinguish between to stitching and underlay, although the default would be a standard underlay+fill.

Imagine this for fill stitch on a fluffy towel:

* Layer 1: 2mm spacing, no underpath, 45 degrees, -4mm inset
* Layer 2: 2mm spacing, -45 degrees, -4mm inset
* Layer 3: 0.8mm spacing, 90 degrees, 1mm inset
* Layer 4: 0.25mm spacing, 0 degrees

The first two would make up a "knockdown" mesh that is bigger than the fill shape, to hold down the terrycloth loops.  Layer 3 would be normal underlay, and layer 4 would be the fill stitch.

So many possibilities :D

**Comment by kaalleen** [comment]
Ok, sounds great ;)
Then I'll merge.

**Pull request merged**
