### PR TITLE
Drop stringcase dependency

### PR DESCRIPTION
**Pull request by bkmgit**
https://github.com/inkstitch/inkstitch/issues/2379

### CODE REVIEW

**Comment by lexelby** [comment]
Agreed!  We don't even need the first re.sub because class names can't have dashes, dots, or spaces.  We can just use the one-liner at the end.  MIT license is compatible with ours, and I don't even think we need to worry about it for a single line like that.

**Comment by bkmgit** [comment]
Have updated it to just use a loop and check for uppercase characters. Using a table and translate() is likely faster than this and also faster than re.sub, but both are more difficult to read.  Checking for uppercase is also better than the re.sub used in stringcase since it handles utf8 for example
```python
st="Ä"
st.isupper()
```

```output
true
```
See also https://github.com/okunishinishi/python-stringcase/issues/1

**Comment by lexelby** [comment]
One thing to note is that our use of `snakecase()` is extremely limited, so we don't have to worry about things like Unicode, or speed for that matter.

**Comment by lexelby** [comment]
So with that in mind, and also considering that we've been using the stringcase implementation just fine for years, I really would prefer the simple one-liner re.sub implementation.

**Comment by bkmgit** [comment]
@kaalleen Ist das in Ordnung für dich?

**Comment by kaalleen** [comment]
I agree. This is only used to convert python class names and we do know that there will be no special characters involved. So I'd go for the one liner as well.

        string = cls.__name__
        return string[0].lower() + re.sub(r"[A-Z]", lambda matched: '_' + matched.group(0).lower(), string[1:])

An other option I could imagine:

        return ''.join([x if x.islower() else f'_{x.lower()}' for x in cls.__name__])[1:]

But there shouldn't be a problem to go with re.sub

**Comment by lexelby** [comment]
How about:

```
return cls.__name__[0].lower() + re.sub("([A-Z])", r'_\1', cls.__name__).lower()
```

No lambda needed :)

**Comment by bkmgit** [comment]
@lexelby @kaalleen  Danke schön. Combined your suggestions:
```
return cls.__name__[0].lower() + ''.join([x if x.islower() else f'_{x.lower()}' 
                                                                     for x in cls.__name__name[1:]])
```
Hopefully ok.

**Comment by kaalleen** [comment]
For me that's ok ;)
@lexelby ?

**Comment by lexelby** [comment]
Works for me.

**Review by lexelby — APPROVED** [review]

**Pull request merged**
