### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by AkiraNorthstar**
replace --no-location with --add-location=full (if --add-location not given it is "full" by default)
replace multiple --add-comments to one option
add --sort-by-file sort output by file location - default False
write out option -s to --strip-comments

### CODE REVIEW

**Comment by AkiraNorthstar** [comment]
Reference: [#232](https://github.com/inkstitch/inkstitch/issues/232)

**Comment by AkiraNorthstar** [comment]
If we work with --sort-by-file, then at least we already have something in which it appears. So you can start in the doubt Ink/Stitch and open this dialogue to recognize the meaning / sense. Yes, the extra generated lines inflate the messages.po, but providing more comfort and structure for translators.
Therefore I would find the combination of --sort-by-file and --add-location=file (with line numbers) the best solution at the moment.
If there is no reference, crowdin.com and others only refer to the line number of messages.po and not to the actual source file. This is more of a hindrance when translating into another language.

**Comment by lexelby** [comment]
> If there is no reference, crowdin.com and others only refer to the line number of messages.po and not to the actual source file. This is more of a hindrance when translating into another language.

Okay, great!  I'm glad it's helpful.  I'll merge this now so you can start using the new messages.po.

**Comment by lexelby** [comment]
I'll also go rerun `make messages.po` and commit that to master as well.

**Comment by AkiraNorthstar** [comment]
That's fine - Thanks!

**Pull request merged**
