### PR TITLE
break apart loops

### PR DESCRIPTION
**Pull request by kaalleen**
This will update the break apart extension. Now it can also split loops into separate objects. This will be very helpful for most not working fill shapes and fixes them.

Additionally I did some restructuring in the menu. It all got a little messed up. So I grouped some extensions together. Hope this will create a cleaner look.

### CODE REVIEW

**Comment by kaalleen** [comment]
The break apart code has become very good (as of my opinion). I am really excited about this. But the extension needs to be updated again when fill areas are able to do it by themselves.

@lexelby have you started to code for the crossing border fix?
If not, I'd like to give it a try within this branch - if you don't mind...

I actually just tried to dig into it. I see three different options for it - of which I would be able to code only two - while the third would be best :)

One option would be to automatically alter the path if it would throw the error otherwise. Not a good solution in my opinion - because we would want to ask the user for path operations, they could use this extension instead.

Second solution would be, to create extra (fake) fill elements with valid shapes. I tried it and it's working so far. With two problems... the param simulation doesn't like it (but I think it's fixable) and we couldn't add commands to those fill shapes - but give a warning and point to the extension.

Third option would be to do some kind of auto-routing from section to section within a single fill element (works easily for manual fill, but autofill is a bit more complex and I am afraid I couldn't code it).

**Comment by kaalleen** [comment]
Hm, the more I think about it ... I rather leave it to you. I might create a whole mess otherwise :D

**Comment by kaalleen** [comment]
I will only update this extension, for it to be able to work even if the fill will be working without giving the errors.

**Comment by lexelby** [comment]
My idea for fixing border crossings was just the `buffer(0)` trick, which it looks like you're using.  I got a little stuck when I realized that for some shapes, it removes part of the shape, like with a bowtie: https://stackoverflow.com/questions/20833344/fix-invalid-polygon-in-shapely

That made me reluctant to just automatically do a `buffer(0)`...

**Comment by lexelby** [comment]
Wow, this looks amazing!  I'm excited about it too.  This will fix a lot of the kinds of problems that have made Ink/Stitch hard to use.

> Third option would be to do some kind of auto-routing from section to section within a single fill element (works easily for manual fill, but autofill is a bit more complex and I am afraid I couldn't code it).

That's something I've been thinking about.  I think we could use `networkx.k_edge_augmentation` just like in auto_satin, then figure out what order to sew each fill section using `networkx.shortest_path`.  Then it's just a matter of using the right starting and ending points for each fill section.  Complicated, but doable.  Let's leave that for later, though :)

**Comment by kaalleen** [comment]
The main work is done by the unary_union function. It is doing a really good job on it. Very fascinating what it can do. I don't feel very good about the buffer(0) thing. But in some cases it caused troubles not to use it. In other cases, it actually causes troubles on the other side. I thought about it for a long time and then I left it in there...

**Comment by kaalleen** [comment]
> [...] I think we could use networkx.k_edge_augmentation just like in auto_satin, then figure out what order to sew each fill section using networkx.shortest_path. Then it's just a matter of using the right starting and ending points for each fill section. Complicated, but doable. Let's leave that for later, though :)

I do not understand a word, but it must be a good idea ;)

**Pull request merged**
