### PR TITLE
auto fill gap fix

### PR DESCRIPTION
**Pull request by lexelby**
A feature that's been requested so often: filling the gaps in fill stitch caused by distortion.  This branch finds the places where gaps can occur (where one section ends and it travels to another section) and continues on for a few extra rows to fill the gap.

Here's how it looks:

image
image

In this case, the extra 4 rows are marked in red.  Later on, when stitching comes back to this point, those repeated rows are doubled up.  In reality, fabric distortion means that some or all of those rows won't actually overlap.

The code does its best to continue the stagger pattern, although the distortion that creates the gap may also disrupt the stagger pattern.  I think it's probably going to look fine, but testing will be needed.

The parameter has the user specify the number of rows to add.  If they give an odd number, it's rounded up to the nearest even number.  I chose to do it this way instead of having them specify "1" to mean 2 rows, "2" to mean 4 rows, etc, because I wanted to open the door for future work in the UI.  Right now we don't have a way to do something like "enforce this value is even", but we might in the future.

### CODE REVIEW

**Comment by danielkschneider** [comment]
Thanx a lot for adding this feature. I did a quick test today (but didn't have time to test a version without gap filling, though I am quite confident that there might have been a gap). I put in an odd number (i.e. 1) since I didn't read this entry before. Unfortunately the green sparkling thread started fraying somewhere in area near the mouth, so I had to repeat 1cm. Finally, I started applying the patch by putting the glue on the wrong side. But other than that, the result is really nice ;) I cannot see any trace of these 2 extra lines that fill the gaps.

SVG of 10 cm Patch stitched with fairly standard parameters. The lettering uses a 60wt thread.
patch-100mm-ghost

Some pics:

**Comment by danielkschneider** [comment]
Here is a better (working) test: Blue patch is without gap filling and brown patch is with gap filling = 1. The blue ghost (without gap filling) in the blue patch has a slight joint problem between the eyes and mouth.  The green in the brown patch is all good. 





SVG Files:
patch-100mm-ghost-satin-last
patch-100mm-ghost-satin-last-gaps

**Comment by lexelby** [comment]
Great test, thank you!  I'm really glad the extra lines aren't visible.

**Review by kaalleen — APPROVED** [review]

**Comment by Dithermaster** [comment]
I found a problem with "Gap filling" -- it just repeats the start and end positions of the last real line, and does not follow the contour of the object. So if the edges are angled it can go outside of the object, quite visibly. 4 row gap shown here, but even 2 rows (the minimum) is visible if the angle is steep enough.
image

**Pull request merged**
