### PR TITLE
Create README_de.md

### PR DESCRIPTION
**Pull request by AkiraNorthstar**
This is a draft - suggestions are welcome!
EDIT: Sorry, forgotten [skip ci]...

### CODE REVIEW

**Comment by AkiraNorthstar** [comment]
Yes, that's sounds better! Thank you!

**Comment by lexelby** [comment]
Awesome, thank you!  Might be worth adding a note that the Background and Philosophy section was kindly translated by you folks, lest someone think I know German and start trying to speak it to me. :)

**Comment by AkiraNorthstar** [comment]
That's right. Then we should do that for all translations. Where do we prefer to place this reference? As a footnote, as a top note or even under each translated paragraph? The latter would distract from the content, right?

**Comment by AkiraNorthstar** [comment]
Yes, that's enough. The content should be in the foreground and not the translator. ;-)

**Pull request merged**
