### PR TITLE
@# - missing characters

### PR DESCRIPTION
**Pull request by kaalleen**
Addressing: #658

### CODE REVIEW

**Comment by kaalleen** [comment]
@lexelby
I noticed, that the lettering module uses the auto-route algorithm. Are you planing to change it or make it an option to the font developer?
Couldn't fonts that by choice use the auto-route algorithm always use the same file? It doesn't seem to make a lot of sense to include all the direction files if for the routing is taking care for automatically. I know, the lettering module is still in it's very first version and you have lots of plans for it. I am just curious about your thoughts.

**Comment by lexelby** [comment]
I have so many ideas!  Yes, I was definitely thinking that the font author could specify whether to use the auto-route algorithm.  I even had in mind that you could create a font with big letters, with filled letters with satin borders.  Or applique, perhaps.

I originally had exactly the same idea is you.  If we can use auto-route, we don't need to have different fonts for the different directions.  I couldn't get it to work how I wanted, though.

Imagine a letter "t".  You might make it as three satins: the horizontal cross, the top vertical part, and the bottom vertical part.  usually font designers seem to have the vertical parts sew first and overlap a little into the horizontal section, and then the horizontal section covers up the overlap to avoid gaps.

It won't work to use the auto-route algorithm directly, because it might choose to do the horizontal part first!  We have to use it with "preserve order" mode.Of course, that really only works for left-to-right and right-to-left text.  For vertical, we need a different order and we might even choose to break up the satins differently.

**Comment by lexelby** [comment]
It's all very complicated, and I have no idea if I'm taking the right approach.  I would be completely open to throwing out what I have and taking a different approach.  If you really to work on lettering, by all means take it in whatever direction you like!

**Comment by lexelby** [comment]
I was thinking it might be cool if you could tell it "do these two satins before the next one".  Some kind of grouping, and an option for auto-route satin that tells it to "respect groupings" or something?

**Comment by kaalleen** [comment]
Yes, I know. It's all very complicated. Also this describes an issue, why I don't use the auto-route function not as often as I would like to. Best solution for this would be (don't know if possible) if we could make the preserve order so, that it also break the parts if needed, but cares for the order in the overlapping parts only. I was wishing we had something like this often, but I have no idea how to approach it.

**Comment by kaalleen** [comment]
Still I think the author should have the option to disable the auto-route function. Even if we can make it work automatically. Sometimes it's good to have full control ;)

**Comment by lexelby** [comment]
Yeah!  I've had that problem, too.  I couldn't figure out how the user would say "do these satins before those".  I mean, what would that look like in Inkscape?  If you can figure that out, I can probably provide tips on how to change the auto-route code to make it work.

And yes, definitely, I intended to allow the font author to choose whether to use auto-route, and even whether to use the "preserve order" option.  With the json file there's plenty of room for more options :)

**Comment by kaalleen** [comment]
@wwderw how would you digitize an overlapping top to bottom `T`?
I think it'd be possible to also go from one section to an other with an zig-zag line on top of stitched out satin if there is no other way to reach the next section. Is that right?

**Comment by wwderw** [comment]
There are 2 ways of doing this that I try to mainly employ when I'm trying to make sure that one thing is always overlapping all instances of a particular letter (in this case, "T").

I'll do the vertical first in it's entirety and then I'll do the horizontal to finish it off (will have connector stitches as well, but let's just focus on the main outer objects).

The other way is to force it, which I think is the way that you are talking about has well.

I will do the top portion of the of the vertical, then do the bottom portion, with a slight overlap on the top portions satin stitch, and I'll do a manual zig zag stitch to get up to where I can do the top horizontal piece.

This forced method, I would think would also be incorporated into some closest connection from the current letter to the next.  If that makes sense.

**Comment by kaalleen** [comment]
@wwderw Thank you for describing it, that already gives a good picture. But maybe we should create a visual example to get a good picture? I prepared a file with two examples (T and H). Could you prepare the routing while following the rules of starting and ending point and the given order at the overlapping parts? That would help a lot! No hurry!
[AutoRoute-PreserveOrder.svg.txt](https://github.com/inkstitch/inkstitch/files/4568503/AutoRoute-PreserveOrder.svg.txt)

**Pull request merged**
