### PR TITLE
move print PDF back to web browser

### PR DESCRIPTION
**Pull request by lexelby**
The de-electronification continues!  This reverts an ancient PR that moved Print PDF over to electron.  I had to fix a few things to get everything working in the browser again.  Testing welcome, as I've only tested in Firefox.

### CODE REVIEW

**Comment by claudinepeyrat06** [comment]
i  just tested in on my mac (Monterey), it works fine with firefox, chhrome and safari.
Thanks.

**Comment by kaalleen** [comment]
Tested on Firefox, Chrome, Edge and Safari on Linux, macOS and Windows.
@rejbasket will run tests on older macOS systems soon and see how that goes (not today).

I pushed to the branch to solve a text wrapping problem which we already faced in the lettering gui for the font description text.

**Comment by kaalleen** [comment]
Works on older macOS systems as well. In that case I think we are good to go...

**Comment by lexelby** [comment]
Thanks for testing, everyone!

**Pull request merged**
