### PR TITLE
Additional details on Debugging

### PR DESCRIPTION
**Pull request by felix300F**
Adopted from debug.py

### CODE REVIEW

**Comment by kaalleen** [comment]
Thank you for working on the Ink/Stitch website. I like that you add a description for liclipse. But we do add the DEBUG and PROFILE files into the root folder directly when using a manual install and not into a /bin folder.

From your other pull request I know why you would assume that the /bin folder would be the right place. This is because you are building Ink/Stitch on windows. So maybe we could add an extra section for debugging with windows builds and keep the original path description for those two files?

**Comment by felix300F** [comment]
I wouldn't have thought that 
```python
if os.path.exists(os.path.join(os.path.dirname(os.path.realpath(__file__)), "DEBUG")):
    debug.enable()
```
in inkstitch.py behaves different, on different OS, or is the packaging different?

**Comment by felix300F** [comment]
I updated the MR, and removed the reference to /bin, but specified that it has to be in the same folder as `inkstitch.py` which should be true for all OS. 

I wouldn't like to duplicate the profiling and debugging documentation for the different OS, having an link to the page probably would be cool, but having different locations for the same information is always error prone. Furthermore there is already one windows guide which includes debugging (https://inkstitch.org/developers/inkstitch/windows-manual-setup/).

**Comment by kaalleen** [comment]
Looks good to me.
Can you also update the date of that page, so translators know that there has been an update?

**Comment by felix300F** [comment]
> Looks good to me. Can you also update the date of that page, so translators know that there has been an update?

Done

**Comment by kaalleen** [comment]
Thanks :)

**Pull request merged**
