### PR TITLE
Save some space (simulator)

### PR DESCRIPTION
**Pull request by kaalleen**
It looks as if we really should save some space in the simulator control panel.

These are my suggestions:

* combine forward and reverse animation buttons
* reduze font size for speed controls

### CODE REVIEW

**Comment by lexelby** [comment]
This does save a lot of space!  I guess people probably don't care about what the current command is most of the time anyway.

The buttons are a little confusing to me:

* the play/pause button shows a pause icon while animating
* the forward/backward button shows a forward icon when animating _forward_

Does the button show what will happen when I press it?  Or what is currently happening?  We should pick one or the other, and I vote that the button should show what will happen when you press it.

That probably means we should switch these to normal bitmap buttons rather than making them `BitmapToggleButton`s.

Other than that, looks good to me :+1:

**Comment by tyrosinase** [comment]
> Does the button show what will happen when I press it? Or what is currently happening? We should pick one or the other, and I vote that the button should show what will happen when you press it.

Interfaces disagree on this. Brothers and Janomes are the opposite when it comes to the "go" button: one turns red while it's running because pushing it will stop the machine, the other turns green while it's running because it's going. ¯\_(ツ)_/¯

Long as things are internally consistent it doesn't matter.

**Comment by kaalleen** [comment]
I didn't even notice it until now. Lex and I agreed on the following behavior:

* Direction button and play button do not switch bitmaps at all
* Direction button doesn't toggle anymore, but behaves like a normal button

I think this is much less confusing than previous behavior.

**Comment by kaalleen** [comment]
Sadly wxpython is down at the moment (since yesterday I suppose?!?).
All linux builds will fail. Nothing we can do about it.

**Review by lexelby — APPROVED** [review]

**Pull request merged**
