### PR TITLE
Fix custom lock

### PR DESCRIPTION
**Pull request by kaalleen**

### CODE REVIEW

**Comment by lexelby** [comment]
Oops.  Guess who didn't test custom lock stitch? :open_mouth:

**Comment by lexelby** [comment]
I pushed a commit, I hope that's okay.  Feel free to get rid of it if you don't like it.  I looked at what I wrote before and I clearly was halfway in the middle of a thought that I never finished.  I think I wanted to avoid reaching into the CustomLock object and setting its path, because that runs the risk of accidentally applying one custom path to _all_ custom locks.  Your way totally worked, but I was worried we might accidentally break it in the future and it would be really confusing.  It's late here and I might be overthinking this.

**Comment by kaalleen** [comment]
That'd would be totally fine. Except ... I don't see the commit? :D

**Comment by lexelby** [comment]
......... lol I did say it was late!  I'll push later today.

**Pull request merged**
