### PR TITLE
fix inx generation

### PR DESCRIPTION
**Pull request by lexelby**
Fixes the following issues with INX generation:
  * didn't properly handle unicode strings
  * Install extension was missing
  * added context for the "English" string

@AkiraNorthstar It appears that I set a trap for you! ;)  I intended the string "English" to be translated to the German word for "German", not the German word for "English".  It's used for the submenu in the Extensions menu.  I added a context comment to make that obvious.  Sorry about that!

I realize that this could be problematic if I actually need the string "English" translated to the German word for "English" elsewhere in Ink/Stitch.  I think that's pretty unlikely, but if we need that, I'll figure out a solution then.

### CODE REVIEW

**Comment by lexelby** [comment]
another bug to be fixed in a future commit: I forgot to populate layer_commands and object_commands in the template call.

**Comment by AkiraNorthstar** [comment]
Hmmm ...
If I switch a language, will the other languages be displayed in the last selected language?

Example:
Main language to native language:
Switch 1: "english" -> "german"

Native language to the main language:
Switch 2: "German" -> "English"

Is that understandable?

**Comment by lexelby** [comment]
I'm sorry, I can't understand what you're trying to say.  :(  Maybe screenshots would help?

**Comment by AkiraNorthstar** [comment]
Forget the whole thing! I worked with an "old" version.
A change between languages as I thought, does not exist.
We generate the languages among each other under `Extensions -> Ink/Stitch`
I assumed, for whatever reason, that we "hide" all other the languages.
So: false alarm ;)

**Comment by lexelby** [comment]
Oh, okay :)

**Comment by AkiraNorthstar** [comment]
Some translations (older ones) not shown in "Install Addons":
screenshot_inkstitch_01
screenshot_inkstitch_02
screenshot_inkstitch_03

**Comment by lexelby** [comment]
> There is a broken picture file too ;)

Ugh, I have no idea why it does that.  I gave up on fixing that last time I worked on this :)

> Or do I still have to wait for the "rebase" #291?

Nope, other way around.  That branch needs to rebase on this branch, which would pick up the fix for the unicode crash.  Waiting is fine too though.

**Comment by AkiraNorthstar** [comment]
It works!

Only the broken picture is still there.
Which image should be displayed there? Respectively, where is the file called in the sourcecode?
In [install.py](https://github.com/inkstitch/inkstitch/blob/master/lib/extensions/install.py) i don't see anything about a icon/picture... However, I can also overlook something :)

**Comment by lexelby** [comment]
Oops!  I accidentally merged this in as part of #292.

**Comment by lexelby** [comment]
> Which image should be displayed there? Respectively, where is the file called in the sourcecode?

I think it's just a default image added by wx.MessageDialog.  I guess maybe there's something wrong with the build process on windows that causes it not to include the image file for that icon?

**Pull request merged**
