### PR TITLE
render single point elements

### LINKED ISSUE #569: Fill ValueError: A LinearRing must have at least 3 coordinate tuples
I had made an embroidery file and successfully saved it to my desktop as both svg and PES file.  I came back to my computer a few days later to work on another project and couldn't remember if I'd saved the file or not, so when prompted on closing, I tried to save it again, and got this error:

Traceback (most recent call last):

  File "inkstitch.py", line 44, in <module>

    print >> sys.stderr, traceback.format_exc()

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\output.py", line 48, in effect

  File "lib\extensions\base.py", line 185, in elements_to_patches

  File "lib\elements\element.py", line 268, in embroider

  File "lib\elements\element.py", line 321, in validate

  File "lib\elements\fill.py", line 148, in validation_errors

  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper

  File "lib\elements\fill.py", line 136, in shape

  File "lib\elements\fill.py", line 136, in <lambda>

  File "site-packages\shapely\geometry\polygon.py", line 240, in __init__

  File "site-packages\shapely\geometry\polygon.py", line 494, in geos_polygon_from_py

  File "speedups\_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py

ValueError: A LinearRing must have at least 3 coordinate tuples

It seems to have saved as SVG before closing, but I'm not sure what happened here.  This might just be user error, and if so, I'm sorry for bothering you.  :)  So far I'm on the very beginning of the Ink/Stitch learning curve but really impressed with what you've managed to do so far.

### PR DESCRIPTION
**Pull request by kaalleen**
Fixes #569

### CODE REVIEW

**Comment by kaalleen** [comment]
Hm, I have to think about it a little more. It will create an embroidery element and still confuses the rendering.

**Comment by lexelby** [comment]
Which columns on the task prioritization board should I look at if I have spare time?  I can't tell if some of the columns might be leftover from awhile ago.  As far as I'm concerned you can get rid of the old stuff on the board of you want.

**Comment by kaalleen** [comment]
I did do every new there. Kept me busy for quiet a while ;)

For you I would like to have a look at the "requires review" column. But this when you have the time to do so. Also the "possibly fixed" column would be interesting to get through.

**Comment by kaalleen** [comment]
The feature requests could get some more ordering though. It has become a pretty long list. But this I will save for an other time. At least I am now up to date with all our issues ;)

**Comment by lexelby** [comment]
Thank you!  It's really going to help me to have that list!  My email inbox is currently VERY full and I fear it may explode soon ;)

**Comment by lexelby** [comment]
Also it feels way easier to find a few spare moments to go through that list, rather than to try to catch up on everything :)

**Comment by kaalleen** [comment]
Thanks for your work today. I know I am throwing a lot of code into here lately and it's much to review. I would like to merge more on my own, but just starting with programming and all, I feel better if someone else looks over my coding ideas.

**Comment by kaalleen** [comment]
Ok, how about this. Instead of ignoring or throwing error messages, we could also just make it valid and render it. Troubleshoot will point to it as a small fill and additionally we could create an other troubleshoot extension named something similar to 'cleanup document', or 'remove small objects'. Could also have a threshold value.

**Comment by lexelby** [comment]
No problem!  I think our new system will make it much easier for me to keep up with you. :)

I was just thinking the other day that it's been really cool to watch you learn as you go.  I really don't feel like you count as "just starting with programming" anymore. :) I'm so happy that Ink/Stitch can provide this learning opportunity for you.

**Comment by lexelby** [comment]
Oh sorry for my comment, I think I'm behind :)

**Comment by lexelby** [comment]
Your idea sounds good to me :)

**Comment by kaalleen** [comment]
> I'm so happy that Ink/Stitch can provide this learning opportunity for you.

Thanks to you. It's great to learn with a project like this!

**Comment by lexelby** [comment]
One thing though: as you're developing your programming style and gaining experience, make sure you also use sources other than just me.  It's no good if you become a clone of me, because I have plenty of bad habits! ;)

**Comment by kaalleen** [comment]
Oh ok, it's good to know whom I can blame when someone complains about my style ;)

**Comment by kaalleen** [comment]
Do you think this one can go as is? The mentioned cleanup extension I actually plan for an other PR.
Life is changing here again and this will reduce the time I can spend coding for Ink/Stitch.

**Pull request merged**
