### PR TITLE
Added Violin Serif and Chicken Scratch fonts

### PR DESCRIPTION
**Pull request by kaalleen**
As discussed in #2531

@safire3002 I renamed the fonts and updated the preview images. Additionally I added keywords and also inserted a glyphs list to the json files for new filter options in the lettering module. I hope everything is to your liking.

If you want to test it, here you go: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-safire3002-add-instrument-and-reenie

Please note, that convert to satin in current releases has problems due to some dependency issues. Therefore I wouldn't recommend to use this release as a permanent work base.

### CODE REVIEW

**Review by lexelby — APPROVED** [review]

**Comment by lexelby** [comment]
I love both of these fonts!

**Comment by safire3002** [comment]
Thank you!! ❤️

**Comment by kaalleen** [comment]
@safire3002 Do you think we good to merge this into Ink/Stitch?

**Comment by safire3002** [comment]
I think so as long as everyone has added/edited to their satisfaction.

**Comment by kaalleen** [comment]
Ok, then I'll merge the pull request. It'd be nice if you could add 

éèêëÉÈÊËÜÄÖäöüß

later. They are needed by a lot of Ink/Stitch users.
@safire3002 are you interesting in adding these glyphs?

**Comment by safire3002** [comment]
definitely in the future! i just have to find time amidst life’s craziness.

**Comment by claudinepeyrat06** [comment]
@safire3002 
Hi, i'm currently working on updating inkstitch fonts. Would you mind if i do a few changes to your fonts ?  I really like violin but some satin columns are really very wide and it could be a problem for many embroidery machines. In chicken scratch a few glyphs do not have  a final trim command. May i  fix that ?  
Maybe also add the missing glyphs so that French and  German  are  happy using with your fonts

**Comment by safire3002** [comment]
Hi,

Totally good with the chicken scratch changes, but can we just split the
satin stitches instead with Instrument? I’d like to maintain the
integrity/design of the original font as much as possible.

**Comment by claudinepeyrat06** [comment]
@safire3002 
Sure, split satin  is a very easy way to fix this problem, I will do that then . Thanks for answering my question. Do you have by chance any real life embroidery picture of your fonts that I could include in the ink/stitch documentation ?

**Comment by safire3002** [comment]
I do, though they’re of certain phrases and not the entire alphabet. Is
that okay?

**Comment by claudinepeyrat06** [comment]
yes absolutly, that would be great.

**Comment by safire3002** [comment]
@claudinepeyrat06 Sure! 
cringe
josh-navy

**Comment by claudinepeyrat06** [comment]
Thanks, love your blue shirt

**Comment by claudinepeyrat06** [comment]
Thanks. Pictures added.

**Pull request merged**
