### PR TITLE
Update zip.inx

### PR DESCRIPTION
**Pull request by AkiraNorthstar**
fix typo / delete third quotation mark

### CODE REVIEW

**Comment by AkiraNorthstar** [comment]
It also had no effect on the presentation and on the function.
But I have the following (double entries):
doubleentries

**Comment by lexelby** [comment]
Yes... unfortunately, that's where our idea for localizing INX files breaks down.  All languages' translations will appear there.  I could perhaps add the language name to the format description, like "Ink/Stitch: Deutsch: Barudan Stickformat (.u01)"?

**Comment by AkiraNorthstar** [comment]
I can live with it right now. If other languages come to it, then it will be a long list ... I have moved the _en_US.inx files, that is synonymous.
It annoys me something that it does not work that way. ;-)

**Comment by lexelby** [comment]
Yup, I've seen that.  I based Ink/Stitch's internationalization support around the method that they used.  Unfortunately that doesn't help for INX files. :(

**Pull request merged**
