### PR TITLE
Added Instrument Serif and Reenie Beanie fonts

### PR DESCRIPTION
**Pull request by safire3002**
I hope I did this right

### CODE REVIEW

**Comment by kaalleen** [comment]
Thank you for all the work you've put into the two fonts. The commit looks good so far (haven't tested the fonts yet).

Are you a member of the Ink/Stitch community already? If not, I can add you to it. The reason I am asking is that it will be easier for folks to test your new fonts, when they can download a pre-release with the fonts included. That would require you to create a new branch directly in the Ink/Stitch repository. But I think we are good for now as is. That's for the next time. If you have questions, please ask.

Could you remove the ttf files? We do not really need them in there.

**Comment by safire3002** [comment]
@kaalleen I'm listed as a contributor? I don't know if that helps lol. I've removed the ttf files from my repository; let me know if that showed up. Reiterating I have no idea what I'm doing

**Comment by kaalleen** [comment]
Yes, you are a collaborator already. But as I said, I think we are good for now with the fork. The ttf files still seem to be there though. Maybe you didn't push your update? What were your steps so far?

**Comment by kaalleen** [comment]
Before I forget about it ... The license requires new names for derivative works. Means, we can chose a new name.

**Comment by kaalleen** [comment]
@safire3002 Thank you for your work so far.
How do you think we should go on from here?
Do you want to do more work on it or do you want someone else to take over?

**Comment by safire3002** [comment]
@kaalleen Is someone else able to take over? It sews out pretty good on what I've done, but implementing it into the code has proven harder than I thought. Thank you!

**Comment by kaalleen** [comment]
Yes sure, we can take over from here. Maybe you want to decide on new font names though? For legal reasons we'll need to rename them.

**Comment by safire3002** [comment]
How about condensed serif? Is that too basic?

**Comment by kaalleen** [comment]
Possibly yes. How about adding your nickname `Safire condensed serif` / `Safire instrument` or use an instrument you like e.g. `Violin Serif`?

**Comment by safire3002** [comment]
Oh yes! I’ll take Violin Serif.

**Comment by kaalleen** [comment]
Ok, great :)
What about Reenie Beanie? Any name preferences?

**Comment by safire3002** [comment]
Hmmm… Chicken scratch? :)

**Comment by kaalleen** [comment]
Closing in favor of #2703

**Pull request closed without merging**
