### PR TITLE
Add lmde6 32bit build

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by rejbasket** [comment]
To build 32-bit version of inkstitch would require python and pip packages compiled for 32-bit. Why are you installing NodeJS? Inkstitch currently doesn’t need NodeJS anymore. I suggest follow our build tutorials and test locally. Although the tutorials for local build are written for macOS, linux version could be built with some modifications to the steps involved.

**Comment by bkmgit** [comment]
Possible solves https://github.com/inkstitch/inkstitch/issues/3239

@rejbasket Inkscape and Ink/Stitch will work on a variety of machines, in particular with low specs.
As Python does not distribute wheels for 32 bit linux, and these may take a long time to build, having
an archive for easy installation would help a wide variety of people try and use Ink/Stitch.

Node is not required for building Ink/Stitch, but for running the checkout and upload action scripts.

The current script targets Linux Mint Debian Edition, but could be made for just Debian.

**Comment by bkmgit** [comment]
@lexelby @kaalleen Would this be considered? Tested the lmde ([Linux Mint Debian Edition](https://www.linuxmint.com/download_lmde.php)) tar.gz build and it is ok.  The other builds fail because of the signing key.

**Comment by kaalleen** [comment]
Thank you for all the effort. Maybe for this one it'd be nice if you could make it a branch of the Ink/Stitch repository directly, so we can test the build system fully. You already have write access :)

**Comment by bkmgit** [comment]
Closing in favor of https://github.com/inkstitch/inkstitch/pull/3298

**Pull request closed without merging**
