### PR TITLE
Fix mac build

### PR DESCRIPTION
**Pull request by kaalleen**
I am not clever with this building stuff ... but can't seem to find where we install gettext in macOS at all? Might be overseeing it - because it did work before ... ?!?

### CODE REVIEW

**Comment by kaalleen** [comment]
Doesn't work at all. Went back to the origin. Don't know why it's not working. `brew link` should do the same as the other settings I've tried out.

**Comment by lexelby** [comment]
I _know_ this worked in the past.  No idea why it's breaking now.  Maybe we're supposed to have `gettext` in the `brew install` line?

**Comment by lexelby** [comment]
Woo, I think I fixed it!  The `::add-path::` is GitHub magic that tells it to update the PATH variable for all following build steps.  Otherwise the PATH would only get updated for the dependency installation and wouldn't work for the `make dist` step.

I still have no idea why this randomly stopped working.

**Comment by kaalleen** [comment]
Oh great, thank you, that worked!

**Comment by kaalleen** [comment]
I merged it already, it's working great (finally) and it will prevent us from getting these annoying error messages all the time. Hope that is ok with you.

**Comment by lexelby** [comment]
Of course it's okay!  Like I said, my free time is severely limited, so please don't let me hold you back.  It's easy to fix things if need be :)

**Pull request merged**
