### PR TITLE
add running stitch tolerance param

### PR DESCRIPTION
**Pull request by lexelby**
This adds an option in Stroke and Auto Fill, "running stitch tolerance".  The tolerance tells Ink/Stitch how hard it has to try to make running stitch match the path you give it.  The lower the tolerance, the closer it must adhere to the path, and the more stitches will be required.  A higher number tells Ink/Stitch that the stitching can deviate from the path more, with the result that some corners may be rounded.

@tyrosinase, this one's for you!  This should give you the ability to customize how tiny those stitches are in your frog's toes (re: [this comment](https://github.com/inkstitch/inkstitch/issues/1688#issuecomment-1153282267)).  It'd be cool if you could give this a try and let me know what you think.

### CODE REVIEW

**Comment by tyrosinase** [comment]
Okay, but first I gotta figure out how to install it. Here's where I admit I have never fully understood the interaction of releases and merges and patches and pushes and checkouts on Github.

(Git came along after I left software development, and while I've used it on personal projects, it's all been single-user milestones with no branching at all.)

**Comment by kaalleen** [comment]
Here you go (in the release section): https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-running-stitch-tolerance

**Comment by tyrosinase** [comment]
Hmm. If I just set stitch tolerance to a giant number, will it keep stitches at the given stitch length? Because I have two issues that I can think of: one, when stitching on unbacked vinyl (clear, mostly), if the stitches are too close together the vinyl will crack there. And two, when topstitching the stitches should always be the same size (or pretty close). Having a minimum stitch length would fix both problems, but it looks like stitch tolerance will at least make it able to mimic the previous behavior.

This is with tolerance cranked to, IIRC, 5mm (or "just try to keep it on the same embroidery field, okay?" level)

image

It does pretty well there; the inter-toe stitches are 0.861mm and 0.856mm and while it cuts that one corner a smidge that's fine. (Also, shout-out to mystique spandex for being able to handle high-tension turning and stuffing WITH A SEAM ALLOWANCE LESS THAN HALF A MILLIMETER, fabric is amazing.)

**Comment by tyrosinase** [comment]
(that was also with 2.5mm stitch length, fwiw; each toe is ~25mm long)

**Comment by lexelby** [comment]
I'm not sure I understand your question, but here's how it works:

1.  It takes the beziers you give it and converts them to a sequence of many line segments with a high resolution.  This is called a LineString.
2.  It removes as many points as possible from the LineString as long as the resulting LineString never deviates from the original LineString by more than the tolerance.
3. It saves all the points in this new LineString -- these are the "Important" points.  Each Important point will be stitched.
4.  Next, it breaks up the LineString from step 1 into sections that start and end with an Important point.
5. It considers each of these section one by one.
6. For each section, it divides it up into stitches of *equal* length that are as long as your stitch length or maybe a bit shorter.

So the tolerance and stitch length settings interact together to determine where the stitches will end up.

**Comment by tyrosinase** [comment]
I thing that boils down to yep, I can still make it act like it used to in cases where it needs to.

**Review by kaalleen — APPROVED** [review]
Looking good - except for the guided fill error which should rather be fixed in the guided fill branch.

**Pull request merged**
