### PR TITLE
Add bean stitch repeat pattern

### PR DESCRIPTION
**Pull request by kaalleen**
This is based on a feature request I have received (not on GitHub).
It's is an addition to the bean stitch. If you enter space separated multiple integer values, it will repeat the stitches with the given pattern. For example "0 1" will do one normal stitch and then a triple stitch, etc. Something like this: -=-=-=-=

### CODE REVIEW

**Comment by george-steel** [comment]
Perhaps, for more flexibility, the param could be a sequence of relative motions, so `1` would be running stitch, `1 -1 1` would be bean stitch, `-1 2` would be a backstitch, `1 1 -1 1` would be your alternating stitch, etc.

Of course, another option which allows for arbitrary stitch patterns (even with a horizontal component) is to use the pattern along path LPE.

**Comment by lexelby** [comment]
I love this!  This is a really simple way to add awesome new functionality.

We've discussed running stitch patterns in the past, but that's a much bigger undertaking.  This gets us part of the way there really easily.

One thing:  I think we use commas to separate multiple underlay angles.  Maybe we should use commas for this one too?

**Comment by lexelby** [comment]
For running stitch patterns, including George's backstitch idea, I wonder if one could use ripple stitch to achieve that...

**Comment by kaalleen** [comment]
> One thing: I think we use commas to separate multiple underlay angles. Maybe we should use commas for this one too?

I think that was a terrible choice (sorry for that). I actually think we maybe should change the separator for the underlay angles. This is the reason why we cannot introduce decimals with commas instead of points, which could be useful for people from some parts of the world :D 
That's why I used space as we have it now for the pull compensation params.

**Comment by kaalleen** [comment]
> Perhaps, for more flexibility, the param could be a sequence of relative motions, so 1 would be running stitch, 1 -1 1 would be bean stitch, -1 2 would be a backstitch, 1 1 -1 1 would be your alternating stitch, etc.

Nice idea, maybe material for a new param, but we should not break the original bean stitch.

**Comment by kaalleen** [comment]
> For running stitch patterns, including George's backstitch idea, I wonder if one could use ripple stitch to achieve that...

Not sure what you mean? If we introduce a param to do these patterns, we can use it for all those stitch types that come out of a stroke I assume?

**Comment by george-steel** [comment]
> > One thing: I think we use commas to separate multiple underlay angles. Maybe we should use commas for this one too?
> 
> I think that was a terrible choice (sorry for that). I actually think we maybe should change the separator for the underlay angles. This is the reason why we cannot introduce decimals with commas instead of points, which could be useful for people from some parts of the world :D That's why I used space as we have it now for the pull compensation params.

Il the svg spec, we use commas when additional list entries create more things (such as more underlay angles create additional underlay layers) and spaces when additional entries split what the single number applies to (such as pull compensation sides or the running stitoh cycle).

**Comment by kaalleen** [comment]
I doubt that our users know the svg spec, for them it is inserting multiple values in all the use cases and it may be confusing if it is a comma here and a space there.

Plus I really would like to allow comma decimals at some point, because that is common in many places in the world and having comma separated values in our params really stops us from that.

**Comment by lexelby** [comment]
Oh yeah, I forgot about that!  Yes, space is definitely the right choice here.

**Comment by lexelby** [comment]
> Not sure what you mean? If we introduce a param to do these patterns, we can use it for all those stitch types that come out of a stroke I assume?

Oh, I was just thinking out loud, not making a suggestion for this pull request.  I was just thinking that it _might_ be possible to make a bean stitch using only ripple stitch, without using the bean stitch option at all.  I'm not sure if it would work.

**Comment by kaalleen** [comment]
@lexelby What do you think how we should handle the comma for the underlays?

**Comment by lexelby** [comment]
I think we should support spaces for underlay too.  Ultimately I want to entirely revamp how we do multiple underlay layers, and make the UI support it more directly.  Then we won't have the user entering lists in a single text box.

**Comment by lexelby** [comment]
I'm not sure I like breaking backward compatibility though... I meant split on space and comma, like `split(' ,')`.

**Comment by kaalleen** [comment]
I think multiple underlay isn't a widely recognized feature. Most people still duplicate their elements to make lace, etc.
As long as we split at the comma, it's hard to introduce the comma decimals. My suggestion would be, to remove commas at the end of each angle, so we can be sure it was meant as a separator. So they are save if they used both, space and comma (such as "20.5, 45.3").

**Comment by bianchifan** [comment]
@kaalleen 
You're faster than lightning!!
Will test it next weekend.

**Comment by lexelby** [comment]
You know, after thinking on it, maybe we shouldn't be afraid of breaking backward compatibility, especially for a good cause.  We can just put a note in the release notes and people can fix their SVGs.

**Comment by tyrosinase** [comment]
"People can fix their SVGs" is... not trivial for some of us.

**Comment by kaalleen** [comment]
Are you using the multiple underlay functionality in your shop files?

**Comment by tyrosinase** [comment]
I don't know... not on purpose, but if it's something that auto-route does or something then yes. It's just... I didn't know the running-stitch tolerance change was going to affect me either, and it broke almost everything. I don't have it in me to fix *all* the designs again.

**Comment by kaalleen** [comment]
I understand your concern, but in this case you really would know if you used it. This is about entering multiple comma separated angles for fill underlays. Most people don't even know that it is possible.

**Comment by tyrosinase** [comment]
Ah, okay. I hadn't been following closely but there was an earlier mention of breaking bean stitch and between that and holiday run-up exhaustion I wasn't sure if it was time to just Craigslist the embroidery machines and go sit and watch the ocean or what.

**Comment by kaalleen** [comment]
No worries, we are not breaking bean stitch, just adding options to it.

But yes, people will need to update their multiple underlay angle (if they did not use a space after the comma). Future versions require a space in between the underlay angles.

**Pull request merged**
