### PR TITLE
add extension to swap satin column rails

### LINKED ISSUE #74: SatinColumn Start/End Points
Swapping the stitch order of a Satin Column is possible, but it's a pain and you lose all of your embroidery parameter settings.  It should be pretty easy to write an extension to swap the order.  Later on, this extension could be turned into a more generalized tool to set the starting/ending points for all kinds of embroidery objects, not just satin columns.

original issue description follows:

---------------------------------------------

I know we can't on the fly change start/end points of various embroidery objects.  However, given that we can predict run stitch start and end points due to the 1st and last node, could we do the same thing with SatinColumns?

Given the attached:

satincolumn setup

Do you think that would be possible?  Just something to help predict start/end points.  I don't necessarily know how we would be able to get it done for fills, but if we can help predict start/end points that would preclude the need to be able to have on the fly editing abilities for start/end points.

I know I used a simple shape for this example, but this should be able to be applied to any SatinColumn object regardless of shape (just so long as it doesn't confuse the extension for rendering stitches).

### PR DESCRIPTION
**Pull request by lexelby**
This adds a simple extension to flip the selected satin columns left-to-right. 
For example, if you have a satin column that starts on the left rail and ends on 
the right, this will make it start on the right rail and end on the left.  Nothing else about the satin is changed.

I got sick of breaking apart my paths, relinking them in the correct order, and 
setting the satin column params again, so I finally got around to writing this :)

Also includes my take on the Ink/Stitch QR code patch ([picture](https://github.com/inkstitch/inkstitch/issues/167#issuecomment-401553091)).

closes #74

### CODE REVIEW

**Comment by lexelby** [comment]
@wwderw this one is relevant to your interests

**Comment by lexelby** [comment]
I'm really loving this thing where I can add new extensions without bloating the size of the release archive.  Now it's super-easy to dash off a new extension.

**Comment by lexelby** [comment]
> Oh yeah!!!!

All I can think of is:

mr_koolaid

:D

**Comment by readymotion** [comment]
Can't wait to try this one this will save some time

**Comment by kaalleen** [comment]
Works great for me ... looking at the qr code patch I also can clearly see why it is coming at this point ;)
I believe this is going to be useful for all of us!

**Comment by lexelby** [comment]
> looking at the qr code patch I also can clearly see why it is coming at this point ;)

As it turns out, no!  The pixels were easy.  Since they're perfect squares, I was able to use combinations of "flip horizontally" and "flip vertically" to get their stitching routed correctly.  I used the keyboard shortcuts `H` and `V`.

I made this extension when I was doing the brackets :)

**Comment by kaalleen** [comment]
Oh I see, interesting, haven't thought about that ;)

I gave it an other test run and this time it didn't flip directions if rungs were present.

**Comment by lexelby** [comment]
Excellent, thanks for testing!  Could you post an svg with the offending satin column object so I can try it out on my end?

**Comment by kaalleen** [comment]
Yes sure. I recreated something like that for you. It's just a very simple setup for test reasons. Two satin columns. The one without rungs works, facing no issues. The other one with rungs on the left side wouldn't swap the rails. I believe it actually did work the other day...?!

[flip-satin-rungs.zip](https://github.com/inkstitch/inkstitch/files/2156697/flip-satin-rungs.zip)

**Comment by lexelby** [comment]
Hah!  I must have been asleep at the wheel when I coded this up the first time.  Try now. :)

**Comment by lexelby** [comment]
Weird, apparently the travis settings got changed to disable automatic building.  Fixed!

**Comment by kaalleen** [comment]
Thanks, fixing travis makes testing a lot easier ;)
It's working now, even satin columns with rungs!

**Comment by lexelby** [comment]
Yay!

**Pull request merged**
