### PR TITLE
Fix syntax and enhance descriptions in Inkscape Embroider extension.

### PR DESCRIPTION
**Pull request by jdieg0**

### CODE REVIEW

**Comment by lexelby** [comment]
You have the ability to merge stuff, @AkiraNorthstar. :)  I have the `master` branch set to "protected" which means that a pull request has to have an approval from someone with write access before you can merge it.  You have write access though, so you could just approve and merge if you wanted to.  I mostly did this to make sure that everyone is seeking feedback on their changes, that's all.

**Comment by lexelby** [comment]
Thanks, @jdieg0!

**Comment by AkiraNorthstar** [comment]
That's fine! I'm a little bit reserved, it's your code after all. Great that we can help you like this.

**Comment by lexelby** [comment]
It's open source for a reason. :)  I couldn't do all this alone.  Remember that even in the incredibly unlikely event that I totally disagree with something someone does, all we have to do is revert.  That said, waiting for me is fine too if you feel more comfortable :)

**Pull request merged**
