### PR TITLE
add bean stitch option

### PR DESCRIPTION
**Pull request by lexelby**
Bean stitch! (finally)

### CODE REVIEW

**Comment by kaalleen** [comment]
Works fine ... with a dotted line! :)
But it seems to break simple satin (continuous line) functionality.

**Comment by lexelby** [comment]
Whoops!  Should be fixed now :)

**Comment by kaalleen** [comment]
Yes, it's working. Thanks :)

**Comment by wwderw** [comment]
For instance, have options for where it does either 3 strokes within an area or "expand" that to 5 strokes within the same area.

Could probably tweak that some more by having options for % of overlap etc (or how far back it goes in other words).

Thoughts?

**Comment by lexelby** [comment]
The thing is, I don't have a clear idea of what you mean by "expand".  It has to end where it started in order to make the next stitch, so it's not clear to me where all the needle strokes go.  I'll try to come up with a drawing showing what I mean later today.

If you can show me an example from Wilcom that would be really helpful.

**Comment by wwderw** [comment]
[Bean Stitch.zip](https://github.com/inkstitch/inkstitch/files/2259164/Bean.Stitch.zip)

I've done 4 sections here with different options.  The screenshot lists the important options that I changed.

Only one that I didn't use was the overlap option.

**Comment by lexelby** [comment]
Ah, I suspected it had to be something like that.  For 3-stroke, it seems less like widening, so much as a kind of stair-step zig-zag pattern.

I'd wonder if this really counts as "bean stitch" since I imagine with the overlap you'd stop getting the characteristic "bean" pattern, but whatever. :)  Yeah, I can definitely do that.  I'll take a swing at it when I get a chance, but I may want to save this for down the road if it ends up overly complicated.

**Comment by wwderw** [comment]
No worries.  Extra options can wait.  As far as this branch goes for me, it's good to go.

**Comment by lexelby** [comment]
Looking at how they arranged the 3 versus 5 strokes, I'm getting some ideas.  It seems to me that their goal is to try to ensure a flat right and left edge when possible.  If I sketch out some ideas for 7 or 9 strokes, there doesn't seem to be a general rule that I could just code.  I'd want to carefully design a stitch pattern tailored to a given number of strokes.

To me, that suggests a new feature: patterned running stitch.  You could give it pretty much any path you want as the "pattern" and it would replace each stitch in a standard running stitch with that pattern.  Widened bean stitch would be one application, but really, the sky's the limit.  It's the natural complement to pattern fill.  And it's actually a super-simple feature to implement.

I'll put together a feature request later and we can hash out some ideas.

**Comment by wwderw** [comment]
>To me, that suggests a new feature: patterned running stitch. You could give it pretty much any path you want as the "pattern" and it would replace each stitch in a standard running stitch with that pattern. 

If I'm understanding this correctly, are we talking about a motif run stitch?

**Comment by lexelby** [comment]
Hmm, looking at pictures, it seems like maybe that's what I'm describing.  It's a bit hard to tell for sure just from screenshots.

**Pull request merged**
