### PR TITLE
Brothread 80 spool palette

### PR DESCRIPTION
**Pull request by kuperov**
Hello Ink/stitch maintainers!

This PR provides a color palette file for the 80 polyester spool kit from New Brothread. Thread codes, names, and colors are derived from [this image](https://cdn.shopify.com/s/files/1/0456/1413/7500/products/NewbrothreadJanome80Colors500MEmbroiderythreadkit-3.jpg?v=1622086511) on the Brothread web site. RGB color triplets were sampled from the swatches in the image.

I generated the file using my own python script. However, I don't know your codebase and you might have a more systematic way to generate the palette files. I am open to feedback and would be more than happy to provide the data in a more appropriate form if you prefer.

Kind regards,
Alex

### CODE REVIEW

**Comment by kuperov** [comment]
Hi @kaalleen, thanks for the review. I have changed the tab to spaces. I'll check out the new palette creator too, it sounds very handy. :)

**Review by kaalleen — APPROVED** [review]

**Comment by kaalleen** [comment]
Thank you. We possibly should adapt the our code, so it can handle the tabs, instead of you having to include those spaces.

I approved your pull request, so you can merge it when you feel ready.

**Comment by kuperov** [comment]
Thank you!

**Comment by lexelby** [comment]
Oh awesome, thank you!  I have exactly this thread set.

**Pull request merged**
