### PR TITLE
add stitch plan extension

### PR DESCRIPTION
**Pull request by kaalleen**
Creates a stitch plan extension as proposed in #206

### CODE REVIEW

**Comment by lexelby** [comment]
Nice!!

The stitch plan isn't shifted over properly in my test:

stitch_plan_preview

**Comment by lexelby** [comment]
Oh, I know what's going on here.  I might have the viewbox in my SVG set weirdly.

I think we can fix that and also make your code simpler.  Instead of using `unittouu`, we should just be able to take the third number in the viewBox and use that as the translation amount.  The viewBox is defined as "the size of the canvas in user units", which is exactly what we want.

**Comment by kaalleen** [comment]
Hm, ok yes, that makes sense. Thanks for having a look into it.

**Comment by kaalleen** [comment]
Are we going to remove the embroider extension in favor of the stitch plan extension?

**Comment by lexelby** [comment]
Hmm, what do you think?

We've had one or two bugs recently that made it so that File -> Save As didn't work.  The workaround was to use Embroider instead.  

There's also one thing Embroider can do that Save As can't do: you can set the "collapse length", which is really just the threshold for adding a JUMP instruction.  I actually used that.  I want to add a Document Settings thing for stuff like that.  We do kind of have that in Print PDF but this setting would be a bit out of place there...

I think we should probably keep Embroider, but maybe have it just create machine embroidery files and not show the stitch plan?  What do you think?

**Comment by kaalleen** [comment]
I had those bugs in mind when I was asking the question. I still wanted to bring it up, because removing the embroider extension was our plan in above mentioned issue.
I would plead for leaving it alive and "as is" for now.

**Comment by lexelby** [comment]
I agree, let's leave it as is.  I sort of have this vague idea of declaring version 2.0 sometime after we get everything converted over to Electron.  Maybe then we can change how Embroider works :)

**Pull request merged**
