### PR TITLE
Add gradient fill support

### PR DESCRIPTION
**Pull request by kaalleen**
Wel... it's a start ...

### CODE REVIEW

**Comment by lexelby** [comment]
Interesting! Can you post a screenshot of what this looks like?

**Comment by kaalleen** [comment]
Here you go

gradient

I think it would be better to (also) add an extension to convert a gradient into the color gradient blocks - so they are editable afterwards.

**Comment by lexelby** [comment]
For the amount that this complicates fill_stitch, I wonder if maybe we should do only the gradient blocks extension.

**Comment by kaalleen** [comment]
I see what you mean. My concern here is more about the routing from one block to the other and possible jump stitches if one block doesn't connect directly with an oher block of the same color. In the case of the image (I posted above) this would happen if you move the gradient more to the left. Therefore I was undecided on that matter myself.
But I really, really do like the possibilities it opens to users. The ease to try out and test and update their gradients. Even if they later in the process will turn this into the actual solid color blocks.

**Comment by kaalleen** [comment]
Ok, I removed it from the fill stitch. It will only convert to color blocks now.

**Pull request merged**
