### PR TITLE
Simulator settings window

### PR DESCRIPTION
**Pull request by kaalleen**
* Sets the view buttons to the side of the simulator (to gain space).
* Adds a simulator preferences button

Under the hood:
* split huge simulator file into it's panels and windows files

Please test thoroughly and comment on visual change!

simulator_sidebar01

simulator_sidebar02

### CODE REVIEW

**Comment by kaalleen** [comment]
I had some feedback, until now it has been positive.
I think I'll merge this in, if there is something wrong with it, we have a greater chance to get feedback when it is in main.

**Comment by tyrosinase** [comment]
image

Tentatively, I like it. I still would like to maybe see some suggested width in there for 40wt, but maybe that can just go in docs. (This is .30mm; might have to play around with it next to some stitched-out designs to come up with the most accurate coverage representation.)

**Comment by tyrosinase** [comment]
If it isn't too difficult, having this apply to the PNG export would be very useful.

**Comment by kaalleen** [comment]
Shouldn't be too difficult. But can you make it's own issue? It's going to be lost in here.

**Pull request merged**
