### PR TITLE
fixes

### LINKED ISSUE #572: Error when saving any Embroidery Format.
Hello, for some reason after I have finished my embroidery design and go to save it I receive the error seen in the screen capture. I have tried saving all different embroidery formats and still receive the error. I also tried reinstalling inkstitch and still got the same error. Anyone have any ideas what may be the issue?
Screen Shot 2019-11-09 at 12 43 03 PM

### PR DESCRIPTION
**Pull request by lexelby**
The previous solution to fix Python 3 didn't work on the output extension (Save As embroidery formats).  The output extension doesn't emit proper UTF-8-encoded data, at least for some formats.  It's not supposed to either -- it's binary data.

Instead of trying to write UTF-8 to stdout from stub.py, we should instead write binary data in the correct manner for Python 2 and 3.  For extensions that emit UTF-8 encoded data (Embroider, Params, etc), Inkscape will decode the UTF-8 data itself, and Stub doesn't need to.

fixes #572

### CODE REVIEW

**Comment by lexelby** [comment]
@kaalleen Amazing news!! This latest commit fixes print / realistic preview on mac!!!! I rented one of those cloud mac desktop things and installed Inkscape.  I tested it and figured out what the problem is.  It's so simple it's a total facepalm.  Ink/Stitch wasn't waiting for the GUI to exit and was just terminating, so the GUI had no server to connect to on localhost:5000.  That's why we got a blank screen.

Now I just need to figure out what's up with the windows build...

**Comment by kaalleen** [comment]
Wow, that is really great news! I haven't thought of that.
If we get the new simulator working for all operating systems, we can replace the old one entirely before the next release.

**Comment by lexelby** [comment]
Yup. :D  The only thing holding back the simulator is that building on Windows is currently broken.

**Comment by lexelby** [comment]
@kaalleen This branch contains a working Windows build using GitHub Actions!  Now we won't be stuck with Travis, which seems to be getting increasingly inconsistent and unstable.  It's also really great because we don't have to use Wine anymore!

Next steps:
  * get it to do the dev-build-* release thing like our travis config did
  * get the mac/linux builds working too
  * release a new version of Ink/Stitch with the electron simulator and the working mac print pdf!

After that we can start on Params or other parts of the GUI.  Things are looking good.

**Comment by kaalleen** [comment]
Interesting idea!
I just had a quick look in the documentation.

Do you know if it is possible to build for other (older) macOS versions than Catalina?
On the first view it looks like they are only supporting the latest macOS version?!?

**Comment by lexelby** [comment]
Yeah, I saw that too. :(  I wonder if maybe it is possible to target older versions while building on Catalina?

**Comment by lexelby** [comment]
Looks like they only have xcode 11+ on the mac build machines, which means we would only support mojave and up.  Honestly, given the amount of random build failures travis has been giving us, I still feel like we should switch to github actions, even though we'll drop support for older macs :(

I have the release creation stuff almost working.  Just waiting on a fix or workaround for this bug: https://github.com/marvinpinto/actions/issues/10

**Comment by kaalleen** [comment]
Ok, I see. That's a little drawback, because we had a lot of requests from Sierra users. But Sierra users can rely on older version of Ink/Stitch until they update their system. "High Sierra" users maybe will be able to use the Mojave version. I got the impression that it had been working the other way around.
But I agree with what you've said about Travis. So this seems to be a better way to go.

**Comment by lexelby** [comment]
I think we might be able to set up a "self-hosted runner" that can build Ink/Stitch for older macs.  All we need is someone to donate either a Mac server or money to rent one.  This explains how to build pyinstaller apps for older macs: https://gist.githubusercontent.com/phfaist/a5b8a895b003822df5397731f4673042/raw/74977524aec942a423d496c381842d09d3c80fbb/environment-pyinstaller-osx-compatibility.md

**Comment by lexelby** [comment]
Woohoo, the automatic releases plugin is fixed!  Now we can finish switching to github actions.  The Windows build works, no more Wine! :D

**Comment by BrendanSimon** [comment]
I'm trying to run the basic demo test

https://inkstitch.org/docs/basic-usage/

I get the following error

```
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 75: invalid start byte
```

Is this error fixed by this PR?

If so when will there be a new release with this fix?  Unfortunately I have nothing to play with if I can't save files in the correct format :(

Thanks, Brendan.

**Comment by lexelby** [comment]
Hi, Brendan!  Yes, that bug is fixed in this branch.  Right now we're held back from creating a new release because our build system kind of crumbled and we're rewriting it.  My free time has been fairly limited lately, but I'm hoping to have things fixed up within a few weeks.

Until then, you may be able to avoid that error by using the Embroider extension to export machine embroidery files rather than File -> Save As.

**Comment by lexelby** [comment]
We're really close!  https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lneva-stdout-encoding

**Comment by lexelby** [comment]
If any mac/windows users could test, that would be great.

**Comment by kaalleen** [comment]
Linux says:

```
Traceback (most recent call last):
  File "site-packages/wx/lib/intctrl.py", line 509, in OnText
AttributeError: 'IntCtrl' object has no attribute '_IntCtrl__oldvalue'
```

**Comment by lexelby** [comment]
Yeah, I saw that. :(  Honestly, I have no idea how that's happening.  I guess maybe it's a wxPython bug?

**Comment by kaalleen** [comment]
Ok, I have received some test reports for macOS and Windows.

### MacOS (Catalina)
... is a pain - if downloaded through the browser. The user would need to manually allow every single binary file to be executed.
This can be avoided, if the file is downloaded via curl:

`curl -LJO https://github.com/inkstitch/inkstitch/releases/download/dev-build-lneva-stdout-encoding/inkstitch-refs-heads-lneva-stdout-encoding-osx-en_US.zip`

wxPython parts of Ink/Stitch are raising an error which we have already seen before:

```
This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac.
```

Good news about electron! The print preview works without any problem on macOS (Catalina).

MacOS versions prior to Catalina won't work (as we expected).

### Windows
Same error as mentioned in my last post (for linux)

```
Traceback (most recent call last):
  File "site-packages/wx/lib/intctrl.py", line 509, in OnText
AttributeError: 'IntCtrl' object has no attribute '_IntCtrl__oldvalue'
```

### Linux
... everything works fine now...

Except for an error which can be seen when running the lettering module (download version only):

```
Traceback (most recent call last):
  File "lib/extensions/lettering.py", line 241, in apply
  File "lib/extensions/lettering.py", line 195, in update_lettering
  File "lib/lettering/font.py", line 128, in render_text
  File "lib/lettering/font.py", line 151, in get_variant
KeyError: u'\u2192'
```

**Comment by danielkschneider** [comment]
Hi all,
I tried under Linux and both the french and english version seem to work ok.

Under Windows, I can see the same trace as @kaalleen when I parameterize something. This seems to be harmless although it can confuse the user.

> ### Windows
> Traceback (most recent call last):
>   File "site-packages/wx/lib/intctrl.py", line 509, in OnText
> AttributeError: 'IntCtrl' object has no attribute '_IntCtrl__oldvalue'
> ```

In addition, when Inkstitch cannot copy with overlapping nodes (typically the ones that InkStitch creates for the circle/oval/arc object) I once got the following

 Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound  method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x105AA828>> ignored

Most often, parameterizing a circle did produce the expected error message about overlapping node. However, I got the above after smoothing (CTRL-L). File attached.
[drawing-param-bug.zip](https://github.com/inkstitch/inkstitch/files/4066943/drawing-param-bug.zip)

**Comment by lexelby** [comment]
See #603

**Comment by kaalleen** [comment]
Ops, that went wrong. Hm.

**Comment by lexelby** [comment]
Well, that was painful.  It's so tedious fixing bugs in other software unrelated to Ink/Stitch.  But it's done!

Now I can get back to the interesting work and fix the bugs you folks found in our stuff :)

**Comment by lexelby** [comment]
This latest commit should fix the mac framework error.

**Comment by lexelby** [comment]
@kaalleen I haven't been able to reproduce your error with Lettering.  Does it still happen for you?

**Comment by lexelby** [comment]
@danielkschneider Not sure about that STRtree error.  I thought I'd fixed that, but apparently not?  In any case I don't think it's related to this branch specifically, so I'm going to leave it for later.

**Comment by kaalleen** [comment]
Yes, it's still there, but only when I download the new release.
In manual install I wouldn't  receive the error message.

Now it reads:
```
Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/lettering.py", line 241, in apply
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/lettering.py", line 195, in update_lettering
  File "/home/runner/work/inkstitch/inkstitch/lib/lettering/font.py", line 128, in render_text
  File "/home/runner/work/inkstitch/inkstitch/lib/lettering/font.py", line 151, in get_variant
KeyError: u'\u2192'
```

**Comment by lexelby** [comment]
Huh, weird.  It didn't do it when I downloaded the release.  I'll try again.

**Comment by lexelby** [comment]
https://github.com/actions/setup-python/issues/23 covers the issue with pip refusing to install the wxpython wheel when we use actions/setup-python to install python.  Once they fix that we can stop doing `apt-get install python2.7`.

**Comment by lexelby** [comment]
Hmm, I still don't get the lettering error.  Could you run `ls -l inkstitch/fonts/*` in your inkscape extensions directory and paste the result here?  I'm wondering if the font SVGs didn't get unpacked properly or something...

**Comment by kaalleen** [comment]
Oh yes, of course. Stupid me: â??.svg
Everything works fine, if I unzip through the command line.

I just wonder, if this is still an issue, because @Augusa mentioned the same thing in #603

**Comment by kaalleen** [comment]
I got more feedback for this branch.

macOS: everything works fine (if not downloaded through a browser)
windows: works fine (except for reports about the language issue)
linux: everything good (if unziped correctly ;) )

**Comment by lexelby** [comment]
OMG I think we're almost ready for a release!! For the Mac thing, I think the time is coming soon for us to have a proper installer and sign our releases.

**Comment by kaalleen** [comment]
> I just wonder, if this is still an issue, because @Augusa mentioned the same thing in #603

Turns out it is!
In the windows files we are missing the font SVGs completely.
My guess would be, this is due to the file name encoding as well?!?

**Comment by danielkschneider** [comment]
> OMG I think we're almost ready for a release!! For the Mac thing, I think the time is coming soon for us to have a proper installer and sign our releases.

Hello, I just tried the new version on both Windows and Linux. On both machines I removed InkStitch files from the extension folder and then downloaded the latest french zip from https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lneva-stdout-encoding  6573b16. I did not try other language versions. From what little I understand, it just seems that you got some wrong paths.

The Linux version is totally broken. I get the following trace whenever I try an operation.

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 8, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/__init__.py", line 1, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/auto_satin.py", line 5, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/i18n.py", line 6, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/utils/__init__.py", line 3, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/work/inkstitch/inkstitch/lib/utils/geometry.py", line 3, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/.local/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/.local/lib/python2.7/site-packages/shapely/geometry/base.py", line 18, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/.local/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "/home/runner/.local/lib/python2.7/site-packages/shapely/geos.py", line 196, in <module>
  File "/home/runner/.local/lib/python2.7/site-packages/shapely/geos.py", line 184, in _geos_version
AttributeError: 'NoneType' object has no attribute 'GEOSversion'
[20690] Failed to execute script inkstitch

Under Windows, I cannot use the fonts. Other bugs seem to have gone :)
Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\extensions\lettering.py", line 241, in apply
  File "d:\a\inkstitch\inkstitch\lib\extensions\lettering.py", line 195, in update_lettering
  File "d:\a\inkstitch\inkstitch\lib\lettering\font.py", line 128, in render_text
  File "d:\a\inkstitch\inkstitch\lib\lettering\font.py", line 151, in get_variant
KeyError: u'\u2192'
Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\extensions\lettering.py", line 241, in apply
  File "d:\a\inkstitch\inkstitch\lib\extensions\lettering.py", line 195, in update_lettering
  File "d:\a\inkstitch\inkstitch\lib\lettering\font.py", line 128, in render_text
  File "d:\a\inkstitch\inkstitch\lib\lettering\font.py", line 151, in get_variant
KeyError: u'\u2192'

**Comment by lexelby** [comment]
Weird, I thought I tested both windows and Linux.  Maybe I didn't properly delete old files before unzipping the new version.  Thanks for letting me know, I'll try to get these fixed up today or tomorrow.

**Comment by lexelby** [comment]
Okay!  The windows font issue was indeed a problem with the unicode filenames.  It's an obscure bug in `python -m zipfile`, so I switched to 7zip on windows.  I wish I could use 7zip on all 3 platforms, but it apparently isn't installed in the mac build runners.  Shrug.

The Linux issue was due to the release of Shapely 1.7.0 on Tuesday. :)  A workaround we had been using previously now broke things so I removed it and everything is now happy.

**Comment by lexelby** [comment]
I think this is finally ready to go!  Last call, I'm gonna merge it in the next few days and start rebasing other branches so they will use the new build system.

**Comment by KaiBuskirk** [comment]
Super Happy! Y’all Rock!

**Pull request merged**
