### PR TITLE
WIP: Params -> electron

### PR DESCRIPTION
**Pull request by lexelby**
This is the first step  of moving the Params dialog to Electron.  I decided to take this opportunity to re-envision how Params works.  A couple problems with the current Params implementation drove my thinking:

* Auto-generating the settings dialog from `@param` decorators is cool, but it is also really limiting.
* The way the settings tabs are selected to be shown is convoluted.
* The whole "dependent tabs" thing is really convoluted too.
* The thing where it says "these settings will apply to # objects" is also confusing.
  * it's not clear to the user _why_ some settings apply only to some objects

I wanted to go a little out of my way to make this more understandable for users -- and pretty, while I'm at it.  I have the Params dialog show a list of objects that are selected as thumbnails. Each one has icons showing whether they have stroke fill, or both set, and whether they're a polyline or clone.  The settings tabs will also have those icons on them so that it's really clear which settings apply to which objects.  To drive the point home, when you select a tab that applies only to objects with a stroke set, those thumbnails will be highlighted, and all the rest will be dimmed out.

Next up: the actual settings tabs :)

### CODE REVIEW

**Comment by lexelby** [comment]
This one's gonna need a major rewrite for Ink/Stitch 2.0.

**Comment by lexelby** [comment]
My plan was to put all of the full stitch underlay stuff as a smaller v-card inside the fill stitch tab, kind of like how I did basic satin and satin column in the satin tab.

My end goal is to have a way for the user to create layers for satin in whatever order they want.  If they want center walk underlay, then E stitch, then contour underlay, they could have it.  We would need some kind of list of layers on the left and then when they select one, the settings would appear on the right.  And all of that would be in the SatinStitchTab.  

That's what I was thinking, anyway.  Does that make sense?  Maybe I should draw a mockup...

**Comment by lexelby** [comment]
Oh, and the same thing for fill underlay too -- and we already have the option for multiple underlay layers in the code, I think?

**Comment by kaalleen** [comment]
Yes, totally makes sense. We have been talking about it already. I thought we will need the templates anyway, so I set them up just the same way as the other ones.

**Comment by lexelby** [comment]
This branch brings a lot of deep structural changes to Ink/Stitch.  It's kind of all-or-nothing which isn't great.

For now, we've decided to hold off on this one in favor of #1548.  That one will have a huge positive impact on our users, and as a bonus, it includes some of the structural changes from this branch.

**Comment by lexelby** [comment]
This is way old at this point and we may be moving away from electron, so I'm gonna close this.

**Pull request closed without merging**
