### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by lexelby**
Enjoy!

### CODE REVIEW

**Comment by AkiraNorthstar** [comment]
@kaalleen : Can you look over the last translation of mine please? For some translations I am not sure about the wording. That would be very kind of you. Tell me if you notice something.

**Comment by kaalleen** [comment]
@AkiraNorthstar I actually think you did a really good job, thank you for all the work! It's not easy to translate all of it with those embroidery terms.

**Comment by lexelby** [comment]
Especially when I sometimes just make up those terms... ;)

**Comment by lexelby** [comment]
I wish CrowdIn didn't create these gigantic pull requests.  Maybe I should remove the languages from the project that don't have any translations yet.  My only fear is that we don't have a good way for folks to request that we add a language so they can translate for it...

**Comment by AkiraNorthstar** [comment]
Can we separate the translations from the rest?
As a submodule or as a separate repository?
So the english language file could stay with inkstitch.

Or does one of you have another idea?

**Comment by lexelby** [comment]
Hmm, yes, I think that would be possible.  The question is, would it help?  We'd still have the big pull requests, just in a different repository.

I'm actually happy with having these pull requests in this repository.  The problem I'm having is that it's just hard to read them, since there are pages and pages of changes in each one.  Do you find it easier than I do?

**Comment by AkiraNorthstar** [comment]
At the moment, each approval of the respective language is triggered by the proofreader, right? Is there a "mass approval" for you as the project manager? Or do you have to approve each language and translation individually?

**Comment by AkiraNorthstar** [comment]
Or can we exclude files? https://github.com/crowdin/crowdin-cli#ignoring-directories

**Comment by lexelby** [comment]
> At the moment, each approval of the respective language is triggered by the proofreader, right?

Yes, but I have CrowdIn set to add translations to GitHub even before they're approved.  My thinking is that it's quite easy to revise a translation in a later version, so why wait for approval?

But of course I'm not the main user of CrowdIn.  It occurred to me that it makes more sense for you folks to manage it rather than me, so @AkiraNorthstar and @kaalleen I've set you two as Managers in the CrowdIn project.  Feel free to change the settings to whatever you think is best.

> Or can we exclude files? crowdin/crowdin-cli#ignoring-directories

Well, we want to translate them, right? :)  I think CrowdIn only pays attention to `messages.po`, which is built by the `Makefile`.

To me, the biggest problem is that every time I change the code, the strings in messages.po move around and the line number comments change.  Then CrowdIn copies those changes out to all 30 languages.  The "real" changes from people adding new translations get lost among the huge number of comment and reordering changes.

I have this option set, but it doesn't seem to work:

> ☑ Skip untranslated strings
> If checked, untranslated strings will not be included into the exported file.

**Comment by danielkschneider** [comment]
Hi, 
Could you approve and merge the french translations in your next release (1.20) ?
No hurry, but I'd like to test these a bit and make sure that there is meaning....
- cheers ! Daniel

**Comment by AkiraNorthstar** [comment]
Approved!
Thanks Daniel

**Comment by lexelby** [comment]
@danielkschneider Previously, we had it set up so that crowdin would create PRs like this one with new translations, but that process had a lot of deficiencies.  Now, a daily cron job pulls in all newly-approved translations from CrowdIn and commits them directly to master.

However, a recent change I made broke last night's run, so I'll fix it and kick off a new one now.  Sorry!

**Comment by lexelby** [comment]
Fixed.  Sorry for all the commits on master; that's the only way to test the cron job :(

@danielkschneider Now that your french translations are committed to master, I've created a branch to cause Travis to build a new development release for you.  It'll show up on the [releases page](https://github.com/inkstitch/inkstitch/releases) as soon as it's built.

**Comment by danielkschneider** [comment]
Hi
@AkiraNorthstar  I did not understand that I have to approve and that I can (there were 2-3 pages left for approval). I do that now :)

So: the french inkstitch-test-fr_FR-linux-x86_64.tar.gz release worked fine but I will have to test a new version.

**Pull request merged**
