### PR TITLE
Adding and updating fonts

### PR DESCRIPTION
**Pull request by LaureFR38**

### CODE REVIEW

**Review by kaalleen — APPROVED** [review]

**Comment by lexelby** [comment]
@LaureFR38 Is this done or are there more fonts you intend to add?

**Comment by LaureFR38** [comment]
> @LaureFR38 Is this done or are there more fonts you intend to add?

No, no more news. Give me a few days we need to check that they're all ok.

**Comment by lexelby** [comment]
Okay, take your time.  I wasn't trying to rush you, just checking in :)

**Comment by lexelby** [comment]
I rebased this branch on master to pull in our latest work, hoping maybe that would fix the build failure.

**Comment by lexelby** [comment]
What happened?  @kaalleen did you close this accidentally?

**Comment by kaalleen** [comment]
Sorry, I was short on time and didn't write anything about it. This branch behaved oddly on a rebase. So I thought it wasn't worth the time to go through the process and upload the fonts to a new branch directly. See #1121

**Pull request closed without merging**
