### PR TITLE
Tie everything

### PR DESCRIPTION
**Pull request by kaalleen**
This aims to give users more control over ties.

Feature request: #1032

### CODE REVIEW

**Comment by lexelby** [comment]
Nice work!  I'm impressed by how you added the dropdown param type.  You made it look easy! :)

While we're working on the ties option, I wonder if we can make it more clear to users.  If I set "tie in", I'm not telling Ink/Stitch that it _must_ add lock stitches before that object.  I'm just telling it that it's allowed to.  If lock stitches aren't needed (because the previous object is less than the collapse length) then it won't tie in.

I'm thinking of something like calling the option "Allow lock stitches: ", and make the options "before", "after", "both", and "neither"?  What do you think?

I wonder if we should stop using the term "tie" since that doesn't seem to be a common way to refer to this.  Everyone seems to call them "lock stiches", from what I've seen on embroidery forums.

**Comment by kaalleen** [comment]
Yes sure, let's rename it.
Thanks for the input.

**Review by lexelby — APPROVED** [review]

**Comment by lexelby** [comment]
I added a little note for our poor translators ;)

**Comment by kaalleen** [comment]
Thanks

**Pull request merged**
