### PR TITLE
Update manual setup and install instructions with per locale releases

### PR DESCRIPTION
**Pull request by Katee**
These changes don't make sense to publish on the website until a release that is built per locale is out: #437

I did not test these changes. I was expecting a `Gemfile` in the `gh-pages` branch to install all the correct plugins and so I could run `bundle exec jekyll serve`.

### CODE REVIEW

**Comment by Katee** [comment]
Done for the installation instructions and the developer instructions.

I'm going to leave un-merged for now as this should only go out with the next release. Feel free to merge when desired. You can also update this branch. I'm not 100% sure about terminology around Ink/Stitch, and I often make silly grammatical errors.

**Comment by kaalleen** [comment]
Looks good so far, thank you for your work on this. I would appreciate if we also could update the date in the header, so the translated versions of these pages would complain about being outdated.

If you don't mind I would also like to push the changes in the menu selection into this PR (deleting every `> English` and `> Deutsch` from the docs). I'll wait for your answer if you are ok with it - you can also do it yourself if you want to. If we remove both (English and German) at once with an automated routine, I'd say we don't need to update the dates in the headers.

**Comment by kaalleen** [comment]
>  I was expecting a Gemfile in the gh-pages branch to install all the correct plugins and so I could run bundle exec jekyll serve.

We are using the minimal mistakes theme, which you can set up locally:
https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

**Comment by lexelby** [comment]
> I'm not 100% sure about terminology around Ink/Stitch, and I often make silly grammatical errors.

Thanks!  Looks great to me.

**Comment by Katee** [comment]
Heads up, I won't be able to make any changes until late tonight or
tomorrow morning as I am don't have my laptop with me. You are welcome to
make changes to this branch. I will keep in mind that the dates need to be
updated in the future.

**Comment by kaalleen** [comment]
Ok, I just wasn't sure if I should interrupt here ;)
Hope I caught them all.

> I will keep in mind that the dates need to be updated in the future.

This is easy to forget, I do that all the time. But also I feel lazy to update the German version right away. I don't like doing things twice. Later then I would forget which changes have been made, so it's best to keep the dates updated.

**Pull request merged**
