### PR TITLE
simulator fixes

### PR DESCRIPTION
**Pull request by lexelby**
Fixes a couple of problems with the simulator.

The color bar sometimes showed an extra bit of some other color at the end and was too wide.  We weren't cleaning up the list of color sections when loading a new stitch plan, oops!

Command symbols would sometimes be in the wrong positions.  I think this is similarly because we weren't clearing the marker lists when loading a new stitch plan.

The current and total stitch displays would be weird while rendering a stitch plan.  Now they're blank, which seems more reasonable.

I switched the simulator back to wxpython.  We're nearing feature parity and we'd ultimately like to get rid of electron.

I separated the different types of command symbols into rows like in the electron simulator so that commands of different types don't overlap.  Commands of the same type can still overlap, as in the electron simulator.

On Linux, when running Params, if you pressed space bar, it would stop the animation AND toggle a checkbox.  Now focus is set to the simulator panel itself and the checkbox is not toggled.

### CODE REVIEW

**Comment by kaalleen** [comment]
Nice work. I changed the extension title from simulator/realistic preview to simulator
Also I added a color picker button to change the background color.
It sure can be improved. But I ran out of time so I thought to share the idea already now.

**Comment by kaalleen** [comment]
Maybe we can connect the initial color with the document color or something.

**Comment by lexelby** [comment]
Ooh I love the idea of only showing the jumps when they check the box!

**Review by kaalleen — APPROVED** [review]

**Comment by kaalleen** [comment]
I'm going to merge this. We can add more updates if necessary later in an other branch.

**Pull request merged**
