### PR TITLE
add new fonts

### PR DESCRIPTION
**Pull request by Tina-Chris**
Claudine and me will upload to this branch the fonts created within the "international foundry" group. 
1st try : Cherry for Kall Een was uploaded to check if I can push to this branch. 

Next we want to do the followings points 

- homogenize text in json files
- check glyph files for hidden paths etc.
- check accents for tie in and out compatibility with the current main.

### CODE REVIEW

**Comment by lexelby** [comment]
I hope it's okay with you, I fixed up the spelling of @kaalleen's name :)

**Comment by Tina-Chris** [comment]
Hi Lex. Thanks for pointing this out. This upload  was only a test if  the push  will work for me. More will be coming within the next weeks. 
Tina

**Comment by claudinepeyrat06** [comment]
Hello,
Could someone give me push access to this branch? 
Thanks
Claudine

**Comment by kaalleen** [comment]
Nice work!
I think we should add `.DS_Store` to the ignore file, because we got a lot of those files in this branch and we really don't need them.

**Review by kaalleen — APPROVED** [review]

**Pull request merged**
