### PR TITLE
Namespaced Attributes

### PR DESCRIPTION
**Pull request by kaalleen**
This is to solve issues #201 and #480

### CODE REVIEW

**Comment by lexelby** [comment]
That's so clever, using the attribute namespace transition as a way to handle the underlay default changing!

What happens if they had enabled underlay previously though?  I think this would set it to false?

**Comment by kaalleen** [comment]
Ops, so right. I've corrected it.

If no other "embroider_" attribute has been set on the object, fill_underlay will switch it's value from False to True - which, I think it won't be too bad. Also the fill_underlay param will be set on other non-fill-elements. I don't think it's much of a problem though...?!?

**Comment by lexelby** [comment]
Ah, that makes much more sense, thank you!

This is a pretty good time to look over all the other params.  Any more defaults we should change?

**Comment by lexelby** [comment]
>  Also the fill_underlay param will be set on other non-fill-elements. I don't think it's much of a problem though...?!?

Nope, shouldn't be a problem at all.

**Comment by lexelby** [comment]
This looks great so far!

I wonder, do we really need `INKSTITCH_ATTRIBS`?  I'm worried that we'll forget to add new attributes to the list.

I think maybe you created that so that we're not constantly calling `addNS` over and over again.  That may be a good use for a function with the `@cache` decorator instead?

**Comment by kaalleen** [comment]
Hm, I don't know. I don't think it is possible to forget adding them ... you will get an error if you do and test it only once :)

At first I was annoyed by having to add all the attributes into a list and thought that there must be a better solution for it (like the one you suggested). On the other hand I thought it delivers a good overview of the attributes we have and also we keep the tags all in the same place. I haven't tested your suggested solution yet. Maybe it's the way to go, but I don't think it's all bad to have the ATTRIBS list.

I wouldn't know about any other default setting that need a change.
Until now we have no complaints...

**Comment by lexelby** [comment]
Good argument!  You've won me over :)

**Comment by kaalleen** [comment]
Yay, I'll merge it then :)

**Pull request merged**
