### PR TITLE
meander fixes

### PR DESCRIPTION
**Pull request by lexelby**
Fixes a couple meander bugs:

* incorrect break in meander edge pair loop
  * meant that meander gave up too easily and sometimes left a huge chunk of the shape unfilled
  * now meander paths also have fewer voids  
* sometimes the graph didn't fill the entire shape
  * this was a separate reason for missed areas in the shape
* a couple tiles had extra edges that confused meander

### CODE REVIEW

**Comment by kaalleen** [comment]
Nice nice nice. This is so much better now :)

**Review by kaalleen — APPROVED** [review]

**Comment by lexelby** [comment]
Now this adds a "clip" option, so you can make sure a shape is filled entirely and hide the outer bit with satin:
image

**Comment by lexelby** [comment]
:arrow_up: that uses:

```
expand = 4mm
smoothness = 0.3mm
```

**Comment by lexelby** [comment]
And now I've added one more param, an angle to rotate the meander pattern by.

**Comment by kaalleen** [comment]
Nice :)

**Comment by kaalleen** [comment]
Do you think this is ready to be merged to you you want to do more work on this one?

**Comment by lexelby** [comment]
Nope, it's ready!

**Pull request merged**
