### PR TITLE
 Remove extra self param from store_preset call.

### PR DESCRIPTION
**Pull request by redhat421**
It looks like this prevents adding new params presets.

### CODE REVIEW

**Comment by redhat421** [comment]
Note that this is my first pull request, sorry if It's a horrible mess. :-)

Thanks for making InkStitch! It's awesome.

**Comment by lexelby** [comment]
What the... how did I never notice that?!  Thank you so much!

Welcome to the project!  We're more than happy to discuss pull requests and work together on them, so please don't hesitate at all to create one.  I'm glad you like Ink/Stitch!

**Comment by lexelby** [comment]
I've granted you write access to the repository.  That allows you to push branches, which will automatically trigger a Travis build.  Once a build completes, you'll see a pre-release show up here: https://github.com/inkstitch/inkstitch/releases

That allows you to test out your changes and see if they work.  This one's so simple I'm just going to merge it. :)

**Comment by redhat421** [comment]
Awesome!

Thanks again for the quick review and welcome. :-)

**Pull request merged**
