### PR TITLE
migrate install extension to electron

### PR DESCRIPTION
**Pull request by lexelby**
This gets us one step closer to getting rid of wxGTK!  This implements the GUI for the "install add-ons" extension in electron.

In the process, I once again came face-to-face with the fact that I have absolutely no design sense.  To deal with that, I added [Vuetify](https://vuetifyjs.com) to the project.  Vuetify makes it super easy to create beautiful UIs with the Material design, which I think is a good fit for Ink/Stitch.

This sets us up for the big one: moving the Params extension to electron.

As part of implementing this, I realized that there's really no point in installing the symbols anymore.  We have extensions to add command symbols for the user, and it does a better job and is less confusing.

### CODE REVIEW

**Comment by lexelby** [comment]
@kaalleen I'm going to go ahead and merge this so that I can continue on, but I just wanted to make sure you saw it because you've been so involved in our previous UI designs.  If you don't like vuetify for some reason, let me know :)

**Comment by kaalleen** [comment]
Don't worry to remove it, this was the plan of the whole electron conversion. I haven't had time to look into vuetify yet, but if you enjoy working with it, it will be fine for me. But I have an other question about this pull requests. I am wondering why we would remove the symbols.svg file for the command symbols?

**Comment by kaalleen** [comment]
I am just right now reading this comment here (sorry, I can't follow all the activities at the moment) ;)

> As part of implementing this, I realized that there's really no point in installing the symbols anymore. We have extensions to add command symbols for the user, and it does a better job and is less confusing.

I am still wondering... Does it mean, we will add commands with the extension, but will not display the symbols anymore? How will users define the spot, where e.g. a fill should start, etc.?

**Comment by lexelby** [comment]
Oh, Inkscspe will still show the symbols!  We don't have to install Ink/Stitch's symbols.svg to make them show up.  The only reason to install symbols.svg would be to make it so the user can manually add symbols using the Symbols tool in Inkscape.

All that said, I just realized that the "add command" extensions use symbols.svg themselves, so removing it definitely wasn't the right thing to do! I'll re-add it when i get a chance.

**Pull request merged**
