### PR TITLE
Zigzag line to satin

### PR DESCRIPTION
**Pull request by kaalleen**
meander_stroke_to_fill

When creating satins people may develope different styles to create them. In Ink/Stitch people seem to avoid the struggle to build up their satin columns. With the live path effect method we now already offer an alternativ. This one here is yet an other method to create them. One of the annoying things when creating satins is that you cannot do it all in one run. you create first one rail, then the other and then the rungs. This is somewhat time consuming. With this method you meander from one rail to the other, while creating the rungs on your way.

### CODE REVIEW

**Comment by bianchifan** [comment]
Just tested with my fill-test svg with added meander
1. Ripple stitch seems ok on the first view
2. Auto fill sucks on one object, job (running) stich much, much too denses, same on outline plus some breaks

Bildschirmfoto vom 2023-03-11 13-40-52

3. Meander convert worked pretty fine but the result do not load in params.
Bildschirmfoto vom 2023-03-11 13-37-29

**Comment by kaalleen** [comment]
Thank you for the feedback and testing.

1. great :)
2. your running stitch setting for that specific fill is at 0.2 mm
3. Nice catch, I have to update the stroke style to no dashes

**Comment by kaalleen** [comment]
Updated the whole thing. Now there is two styles how this can be created. The new style actually has a longer path... but maybe it could be useful to convert a embroidery satin back to a svg satin (if we do not think about underlay etc., just the pure zigzag).

zigzag_to_satin

**Comment by rlevine** [comment]
Just for fun, I tried ZigzagLineToSatin on a fill shape I've been trying to recreate, and got this result. Not what I expected!
(And yes, I know my original is a sparse fill with underlay, but I was curious what would happen. :)

Options were smoothing, but no  rungs.

zigzag_to_satin_fun

**Comment by rlevine** [comment]
Heh. Missed the "sawtooth" pulldown!

**Comment by rlevine** [comment]
Ok, here's the sawtooth version. Much better, but what causes some of the zigs to stop short of the rails? 

zigzag_to_satin_more_fun

**Comment by rlevine** [comment]
Ah. Short stitch distance. Getting closer.

**Comment by lexelby** [comment]
Cool!  Thanks for renaming, I wasn't sure about adding two new "meander" features in one release :)

**Comment by lexelby** [comment]
I wonder if the zigzag version should be changed to expect a zigzag like simple satin produces, looking like `VVVVVVVV`.  

And what if it could take a path that isn't a perfect zigzag and detect the corners automatically? Imagine, our users could sketch a satin by drawing a zigzag directly and converting it!  Then they could tidy up the rails.  I would especially love that because I have a touchscreen.

**Comment by rlevine** [comment]
And the last of the series, with rail tidying. :)

zigzag_to_satin_last_of_the_fun

**Comment by kaalleen** [comment]
> I wonder if the zigzag version should be changed to expect a zigzag like simple satin produces, looking like VVVVVVVV.

Hm, maybe as an extra zigzag method? They way it is now you just draw the rungs if you want to think it that way.
I was thinking about the zigzag too, but then again you would need to calculate the rungs. They could be placed down from the zigzag point to the midpoint between the two zigzag-points from the other side. 

However after I've been excited about the zigzag method I actually found it easier to work with the square method on my touchscreen.

**Comment by kaalleen** [comment]
@rlevine thanks for testing and posting images while you are learning to work with it! That is interesting to see.

**Comment by rlevine** [comment]
@kaalleen you're very welcome. Thanks for adding this - it's a nice bit of code. I hope my noodling isn't distracting for you folks. I'm very much in "sponge" mode, playing with the extensions and watching the code run, trying to absorb enough to contribute intelligently.

**Comment by lexelby** [comment]
Keep noodling!

**Pull request merged**
