### PR TITLE
WIP: Example file for Software Freedom Day

### PR DESCRIPTION
**Pull request by bkmgit**
@Tina-Chris @Moini @bianchifan @claudinepeyrat06

### CODE REVIEW

**Comment by kaalleen** [comment]
Nice, thank you!

This logo is licensed under Creative Commons Attribution 3.0 unported: https://wiki.softwarefreedomday.org/Logo#The_logo
Could you add a attribution layer with an ignore layer command? Also make a comment that the logo has been modified for embroidery.

An other thought... just if you like. I think for some operating systems/users (especially on macOS) the example file folder has become a bit inaccessible. What would you think if we put this on the website into the tutorial section? Ideally this could also show how it looks like when it is embroidered.

**Comment by bkmgit** [comment]
Added license information. A preview of current file:
SFDpreview
Example shirts (slightly older version of file used)
SFDsharti

Can create something similar to:
- https://inkstitch.org/tutorials/ripple-monochrome/
- https://github.com/inkstitch/inkstitch/blob/gh-pages/collections/_tutorial/en/applique.md

**Comment by kaalleen** [comment]
Good job, it's really looking good - and definitely worth to show up in the tutorial section. Prepare the page as you like it best. When you need help to get started with the website, just ask what you need to know.

Could we have that attribution layer visible? It is just text and Ink/Stitch will ignore it anyway. I would opt in for an ignore layer command nevertheless, just in case that text will be rendered directly in future.

**Comment by bkmgit** [comment]
Closing in favor of https://github.com/inkstitch/inkstitch/pull/2530

**Comment by bianchifan** [comment]
there is a little problem with you svg, it does not work with Janome machines!
 and some others do cut stitches longer thean 12.7 mm automativcally!
But your satin contain stitches will nearly 15mm lentgh..
Inkstitch output with JEF format will produce  a corrupted embroidery.
Bildschirmfoto vom 2023-10-02 13-57-12
Bildschirmfoto vom 2023-10-02 14-05-07

**Comment by bkmgit** [comment]
Thanks for the feedback.  Typicallly use DST files, the embroidery of the long stitches was done with care by an expert using custom embroidery settings.  It is possible to use a fill stitch instead of long satin stitches.  Let me know if that would work for you.
SFDEmbroiderFilledSun
SFDEmbroiderFilledSunPreview

**Comment by bkmgit** [comment]
@bianchifan Thanks for your feedback. Will update tutorial to include both forms of the sun, and indicate that one of them uses long stitches that maybe problematic.  Image of stitchout of svg file linked above is below. Other feedback is warmly welcomed.
SFDFilledSunStitchout

**Comment by lexelby** [comment]
@bianchifan I don't think that's quite true.  I had a Janome machine and I was able to do stitches longer than 12.7mm.  It's possible to do stitches up to around 38mm with the default machine settings.  You can go longer then that if you set the "jump trim" setting in the machine's settings to more than the default (3).

Did this design actually cause incorrect cuts on your Janome?

**Comment by bianchifan** [comment]
@lexelby THX for diving in!
I have no Janome and no inaccurate cuts, my w6  machine comes from Happy Japan and uses DST ;)
But I've learned  at a german forum that there should be problems with stitches longer than 12.7mm on Janome machines. To be accurate, on MC500e and MC550e. In a "parallel forum" same discussion and there was pointed out the possible solution with jump stitches. But another guy who owns a SWF 6-needle claimed also 12.7 mm as max. possible stitch lenght.
Please have a lokk at my pcs above.. InkStitch JEF output routie substitutes stitches longer than 12.7mm by trim commands!

> It is possible to use a fill stitch instead of long satin stitches

Yeah, but it's also possible to use two satin rows, one wide and one small. Or two rows stitched into each other. Or...,or..., every guy who likes to stitch it out can change the params

**Comment by lexelby** [comment]
Yikes, I see what you mean in the picture and it is _definitely_ not supposed to do that!

Stitches longer than 12.7mm are split up into JUMP+STITCH, or JUMP+JUMP+STITCH, etc.  The problem is that JUMP+JUMP+JUMP is interpreted by the machine as TRIM, so stitches longer than 3 x 12.7 (38.1mm) will result in a trim.  That is true for both JEF and DST, and also most other formats.

I had a Janome mc400e, and I tested all this extensively.  It definitely did work in the past.  I'll try to figure out why it's now doing those extra trims in the middle of the satin.  Looks like a bug.

**Comment by bkmgit** [comment]
@bianchifan   https://inkstitch.org/tutorials/software-freedom-day/ Danke schön! Übersetzungen und Verbesserungen willkommen.

**Comment by kaalleen** [comment]
Hm, I think many machines will cut the thread when a stitch is longer than 12.7. Although on some machines this could be avoided, I think we should be careful to offer files that have longer stitches than that (except this is made clear in the description or if the design serves a special purpose that makes it necessary).

Also if this is meant for wearable items, the washing machine may not be nice to the stitch out when stitches are longer than 7 mm (I've heard). Maybe it'd be good if we keep that in mind.

**Comment by tyrosinase** [comment]
Seconded,. The reason most machines auto trim long stitches by default is because you almost never want them for real. They pull, they are easily snagged, they do not stay smooth and attractive, etc. 

Plus, it's two separate arcs. Much more professional to have it continue through that area unmerged, as two adjacent satins.

**Comment by lexelby** [comment]
Fringe is an example of a use for >12.7mm stitches.  Not super-common but not exactly incredibly rare either.

I really haven't ever seen a machine that would cut a 15mm stitch automatically... Which machines do that?

**Comment by bkmgit** [comment]
Modified to use 2 paths and satin stitch for the sun.
SFDEmbroider2PathSun
SFD2PathsPreview
Can add a further update to the tutorial and get a stitchout.

**Comment by kaalleen** [comment]
sdf_info_before

This is still more than 12.7. JEF exports will miss some stitches. What if you move it just a little bit to the top, expanding the smaller part while making the top part smaller? Also stitches on the sun could be placed a little bit nicer with rungs.

sfd_info

I also noticed, that the green bottom line is an extra subpath. This will not cause problems with the newer Ink/Stitch versions, but maybe worth fixing too.

Here the svg (just those two little adjustments and an additional running stitch at the end of the sun to avoid a jump).

sfd

**Comment by kaalleen** [comment]
> I really haven't ever seen a machine that would cut a 15mm stitch automatically... Which machines do that?

Actually I am not sure which machines exactly. I can stitch out super long stitches with my machine if I turn off the trim. But with default settings not. So if we offer files with stitches > 12.7 we need at least a warning and also a hint for jef file users that it won't work for them.

For a motive like this (especially when the example image is embroidered on a shirt) I think we should avoid long stitches if possible since it will have an impact on the quality and durability of the stitch out.

**Comment by tyrosinase** [comment]
> I really haven't ever seen a machine that would cut a 15mm stitch automatically... Which machines do that?

The Janome defaults to cutting anything over 3mm, which seems a bit overkill to me.  I like to use a 3mm satin to cover minky/velvet applique wherever I can, to conceal all the fuzzy. A 3mm cut doesn't leave any room for rounding error.

(I've started changing it to 2.9mm, because I can't count on customers having changed their defaults, but I didn't even realize the default was so brutal until I bought a new machine. The previous owner of my first had bumped the autotrim out to, I forget, 6mm?)

**Comment by lexelby** [comment]
Ah, I forgot about the autocut setting.  You can turn that off though, right?

**Comment by kaalleen** [comment]
Woah, if they use these settings by default, we actually don't need to worry that any janome machine owner doesn't know how to change the trim settings :D

**Comment by tyrosinase** [comment]
> Ah, I forgot about the autocut setting. You can turn that off though, right?

Yup, though for designs I sell I try to assume the buyer hasn't (and isn't aware of it).

I'm kinda concerned about it being 3mm, that's *so* narrow - I'm now wondering if there's ever been a case where someone's machine has trimmed just one or two rounded-too-long stitches out of a 3mm satin and just hasn't mentioned it to me.

**Comment by lexelby** [comment]
Okay, I've done a ton of digging and I have a bit more of a clue of what's going on here.

First of all, the thing where loading a saved JEF back into Inkscape shows trims for long stitches, as seen in the second picture of [this comment](https://github.com/inkstitch/inkstitch/pull/2525#issuecomment-1745264065).  Those trims are a bug in Ink/Stitch's JEF _reader_, not in the writer.  Those trims are not actually there in the JEF file.

For some reason, the JEF reader is coded to treat a JUMP of longer than 3mm as a TRIM.  This is _not_ the same thing as the 3mm trim setting @tyrosinase mentioned.  I see no reason why JEF would treat a 3+mm JUMP as a TRIM, but to know for sure, we'd need to test it with a Janome machine.

**Comment by tyrosinase** [comment]
I wonder if it's related in the sense that they're...hmm... trying to make it duplicate what the machine actually does (by default)? Like, trying to read it how the machine will? (Or rather, how they assume it will.) The fact that they're both 3mm seems significant.

Anyway, I just made an absurdly increasing satin, and sure enough loading the jef back in cuts off very early, and tunes back in only at the lockstitch. Loaded it on the machine, and things got even funnier.

Here's what the screen looks like.

IMG_7331

That's it cutting out at the 3mm point, but then drawing two bits of the long stitches and the lockstitch. It looks like that even if I turn off autotrim BUT HERE'S WHERE IT GETS WEIRD: if I step it through the stitches, it bounces back and forth through the un-drawn area. So I slapped a piece of scrap stabilizer in a hoop and told it to stitch and it does BUT it pauses and makes the little trimmer "gronk" in between each stitch. I took video but naturally it's too big for Github, if I can remember how kdenlive works I will trim it down, but it definitely changes its behavior over 3mm wide. Still stitches out, but I think I could hand-sew it faster.

I don't know if that's the machine or the file, but it is surely acting like it's got a trim after each punch. (If it *is* the file it is 100% weird to me that the machine would honor it by going through the internal actions of the trim without actually cutting the threads.)

**Comment by tyrosinase** [comment]
Wait wait wait, that's not even 3mm where it changes over, that's 12mm. And the spots where it shows up again on the screen are 24mm and 36mm.

image

(This may be why I've never encountered it; I've done things with long jumps but probably never anything over 12mm)

**Comment by tyrosinase** [comment]
May have overtrimmed the video but you get the last two normal stitches and then... whatever this is.

https://github.com/inkstitch/inkstitch/assets/9473609/e1f541c2-8d08-447a-8a5a-b760ec6c2664

Kaalleen will probably have more insight than I do, because I always thought that *was* the trim noise.

**Comment by lexelby** [comment]
Ah, that!  Yes, I remember that from my mc400e.  I think that noise you're hearing is the jump solenoid or something analogous.  I think it's holding the thread in place while the hoop moves so that more thread is pulled out of the spool and bobbin.  It will do that anytime it gets a JUMP instruction -- even short ones.  My brother pr machine does it too.

Commercial machines do something different: the jump solenoid kicks in and disengages the needle up-and-down mechanism for one stitch.  That allows the machine to continue at full speed and just skip stitching for a jump stitch.  It's pretty cool to watch.

In short: it's doing exactly what we've instructed it to do.  Jump for some amount and then stitch.  It's successfully making a satin that's greater than 12.7mm, right?

As to the 3mm thing, I thought of the same possibility, but in looking at the code, it only treats a JUMP of >3mm as a trim.  It doesn't treat a STITCH of greater than 3mm as a trim.  I think from what you're saying that the machine will treat even a STITCH of >3mm as a trim with that setting enabled?

I think I might be being confusing here. :)  In most machine embroidery formats, there's the concepts of JUMP and STITCH.  STITCH says "move the hoop this amount and then drop the needle down to make a stitch".  JUMP says "move the hoop this amount and DON'T drop the needle".

**Comment by tyrosinase** [comment]
Ah yes, I wondered if it wasn't something giving a little extra hold to the thread so the overlength satin didn't overwhelm the tension system. So a "jump" is different than a stitch for it, where I'm guessing it's the same for a [low-end, at least] Brother; my PE800 would cheerfully leap from corner to corner hauling the thread behind, without taking any particular precautions. Just full "human said I should make a stitch this long so it must be fine!"

**Comment by tyrosinase** [comment]
ALLLLLSO

💡 I bet this explains why despite the 3mm default being super-close to the satins I make, I haven't run into cases where my satins get randomly trimmed: it only applies the auto-trim to *jumps* and knows the difference.

That makes much more sense to me now.

**Comment by lexelby** [comment]
Ah!  So the machine _does_ behave the way the JEF reader code interprets it.  Interesting.

This suggests that with the default settings, 12.7mm is, in fact, the biggest stitch size, because Ink/Stitch will convert a bigger stitch into a JUMP+STITCH with a JUMP bigger than 3mm.  It could conceivably do a 15.6mm stitch without triggering the 3mm trim.

This also explains why I did _was_ able to sew bigger stitches than 12.7 with no problem: the first thing I did when I got my machine was to disable auto-trim; I remember doing it.

**Comment by tyrosinase** [comment]
> Ah! So the machine _does_ behave the way the JEF reader code interprets it. Interesting.

Well... probably? I don't have any non-Ink/Stitch files with XXL jumps to absolutely confirm it with. I could pester someone with Embrilliance to make me one though, if we really wanted to be sure.

**Comment by lexelby** [comment]
Nah, that's not necessary.  I remember my experimentation on the mc400e now and this all matches up.

**Pull request closed without merging**
