### PR TITLE
origin and stop position

### LINKED ISSUE #124: "Frame Out" Functionality
Main purpose of this is for when the machine stops with the hoop in an outward position to make it easier to apply the fabric when doing appliqué. 

It doesn't get stitched, it's a series of jump stitches that go to a certain spot (use the guide lines, just label them "frame out" instead of "embroidery origin" to keep them separate).

Initially discussed in issue #112, I would suggest making it available even if not being used with the appliqué function mentioned in #112, in case there are different needs for a particular project.

### LINKED ISSUE #192: Use marker instead of guides for origin
In https://github.com/lexelby/inkstitch/issues/20#issuecomment-395492965, I had the idea of using Inkscape's Symbols tool together with the Connections tool to add command markers that Ink/Stitch can see.

We could use the same technique for the embroidery origin.  Instead of having to set up two guides and name them properly, one could just drag an icon to the right spot.  It'd be much easier from the user's perspective.

There's also a pretty good reason to do this from a code perspective.  The code involved in parsing the guides is pretty horrible, due to one or two bugs in how Inkscape includes the guides in the SVG.  I'd really love to be able to get rid of that code.

How would people feel about replacing the guides?

### PR DESCRIPTION
**Pull request by lexelby**
This branch adds commands for the embroidery origin and stop position.

fixes #124 
fixes #192 

# Origin

Notably, this branch **removes the "guides" method of specifying the origin**, as discussed in #192.  I know this may break some existing SVGs, but the code for parsing the guides was really gross and it's super easy to add the new symbol.

There's no extension to add the Origin symbol since it's a "global" command, not attached to a layer or an object.  You can just open the Symbols tool and drag it out there wherever you like.  For this to work you'll need to re-run "install Ink/Stitch add-ons for Inkscape" after installing this version.

# Frame Out, a.k.a. Stop Position

Just like the Origin, this is a "global" command, so you'll need to drag it out from the Symbols tool.  Place the Stop Position command wherever you like.  Every time Ink/Stitch processes a Stop command (attached to an object), it will insert a jump to the spot marked by the Stop Position before inserting the stop instruction.

------------------

Do you think we need another commands extension, "Add Global Commands" or something?  Or is dragging these out from the Symbols tool okay?

cc @wwderw

### CODE REVIEW

**Comment by wwderw** [comment]
>Do you think we need another commands extension, "Add Global Commands" or something? Or is dragging these out from the Symbols tool okay?

I keep on going back and forth here.

Dragging out the symbols when necessary is easy enough for me as I'm used to having the symbol docker right handy.

What makes me wonder is the lay user going to be able to handle that?  Howe discoverable is it for them?

I personally think it's fine, I just don't know about the lay user.

**Comment by wwderw** [comment]
Just did a quick test.  Origin command worked fine.  The frame out command, it only stopped where it was attached to an object, not to where the global command was.

**Comment by AkiraNorthstar** [comment]
sorry for this request:
> AkiraNorthstar requested a review from kaalleen 3 minutes ago
> AkiraNorthstar removed the request for review from kaalleen 3 minutes ago

just had a cramp on my hand - I should take a break.

**Comment by lexelby** [comment]
> I personally think it's fine, I just don't know about the lay user.

You know, this is a good point, and it's the kind of thing I was thinking when I created the other two extensions.  I think I will add another one for this.  What can it hurt, after all?

**Comment by lexelby** [comment]
@wwderw could you post your SVG and the DST (or whatever other format)?

**Comment by lexelby** [comment]
The latest commit adds an "Add Commands" extension to handle the Origin and Stop Position commands.  Now that I've done it, I'm glad I did.  It made sense to me to put all 3 command-base extensions into their own submenu, so now it's:

```
Extensions
  └ Ink/Stitch
      └ Commands
        └ Add Commands...
        └ Add Layer Commands...
        └ Attach Commands to Selected Objects...
```

**Comment by wwderw** [comment]
I haven't gotten the new version yet (hopefully later on this evening or tomorrow I'll be able to try it out), but here is the files that I used for the earlier test.

[Frame Out Test.zip](https://github.com/inkstitch/inkstitch/files/2320047/Frame.Out.Test.zip)

This is just random, no discernible pattern, just try mess with the origin and do the frame out function.

**Comment by wwderw** [comment]
I think I know what happened with my test.

I think I used the wrong symbol.  I used the regular pause symbol for the frame out, when it's the eject symbol, based on the updated PR and using the Add Command function of the extension.  

I'll try this new version either tonight or tomorrow and I'll see if that's the cause.

**Comment by lexelby** [comment]
Ah!  Well, that right there is a great argument for the new extension.

**Comment by wwderw** [comment]
Worked flawless on my end.

**Comment by lexelby** [comment]
Yay!

**Pull request merged**
