### PR TITLE
expose the trim_after param in the interface

### PR DESCRIPTION
**Pull request by george-steel**
This provides an alternative to the connector-based commands (which inkscape can't copy-paste) allowing for re-usable embroidery elements with trims. `trim_after` has been around for a long time as a hidden param, but never exposed.

### CODE REVIEW

**Comment by lexelby** [comment]
I dunno... What do you think, @kaalleen?

**Comment by george-steel** [comment]
For me the other big advantage (besides copypasting) of a trim param over instead of a trim is that in introduces less clutter into the object list, making panelizing and color-sorting easier.

**Comment by kaalleen** [comment]
I'm all for it. Commands often cause trouble, slow down the system, etc. There is a lot of cursing out there too :D 

I think, that they are very useful if you need to define a certain spot for functionality (start, end, etc.). For trims (and stops) they are maybe not that useful. We had a discussion about this topic a while ago in #1628

**Comment by lexelby** [comment]
Alright, let's do it!

**Comment by kaalleen** [comment]
Same thing for stops?

**Comment by george-steel** [comment]
> Same thing for stops?

Done. Is this ready to merge @kaalleen?

**Comment by george-steel** [comment]
When we fix groups to resolve #1696, we should probably make this add a only single trim when applied to a group (after the last element) instead of inheriting to each element of the group and trimming after each one. Tagging that issue as a reminder.

**Review by kaalleen — APPROVED** [review]

**Comment by kaalleen** [comment]
We should also consider to add an option on how to add trims for the lettering and the auto-route satin extensions (Add trim as: symbol or param).

**Pull request merged**
