### PR TITLE
add reverse one rail param

### PR DESCRIPTION
**Pull request by lexelby**
Turn this:

image

into this:

image

with this:

image

It's about darn time I got around to this.

### CODE REVIEW

**Review by kaalleen — APPROVED** [review]

**Comment by george-steel** [comment]
Why is this necessary when the reverse tool already exists?

**Comment by rlevine** [comment]
Ease-of-use: it's more efficient. Instead of 

- backing out of params
- click on one rail
- do the reverse
- look for the almost-invisible arrows to verify the path was reversed
- re-open params

I just click on one checkbox. (And it's even worse if I have to break up the path, which seems to be needed occasionally in Inkscape on a mac.)

**Comment by lexelby** [comment]
Also: lots of users don't have any clue what's going wrong.  They think they've followed the directions and Ink/Stitch explodes.  This gives them a fighting chance of figuring it out.

I'm tempted to auto-detect a reversed rail and fix it automatically, but I know that in some rare cases you want that.

**Comment by rlevine** [comment]
I’d vote for auto-detecting and leave the checkbox, making the rare case optional.

**Comment by lexelby** [comment]
Tempting... @kaalleen, what do you think?  Should we automatically fix a reversed rail, and give them a checkbox for the rare case when they want the rails to be going in opposite directions?

**Comment by kaalleen** [comment]
As long as it doesn't behave odd often I don't really care. I'm just afraid that the ui is getting long and we have no grouping for options yet.

**Comment by kaalleen** [comment]
It won't add an option though...

**Comment by Jeidsgn** [comment]
I like more that they leave it optional, if they cancel it completely, things like this could not be done to us
image

**Comment by kaalleen** [comment]
Nice, thanks for sharing. The intention is not to disable to possibility to do this. ... But we may break existing designs by reversing it automatically ...

**Comment by lexelby** [comment]
Good point.  Maybe another use for the version number thing we were discussing :)

**Pull request merged**
