### PR TITLE
Update pyembroidery

### LINKED ISSUE #516: Ink/Stitch (or pyembrodiery) cannot read vp3 files with true trims in them
When reading a vp3 file which contains true trims (trims which are not only a colour change), Ink/Stitch (pyembroidery) reads it wrong. 

As can be seen in below picture, a lot is missing. Both stitches and colours. To the left is Premier, to the right is the interpretation by Ink/Stitch (pyembroidery):
Artboard 1

Enclosed are the files behind above views, containing the example, of a vp3 file which is fully readable in both Wilcom TrueSizer and Premier. But not in Ink/Stitch. It is collected as a zip ([vp3 with trim.zip](https://github.com/inkstitch/inkstitch/files/3475693/vp3.with.trim.zip)):
- vp3 file with trims that work in vp3 (outline cat face p0.0-006 wilcom from dst.VP3)
- screendump of how it looks in Premier, Husqvarna vp3 reading software (outline cat face with trims in vp3 read by Premier.PNG)
- screendump of how it looks in Ink/Stitch, reading using pyembroidery (outline cat face with trims in vp3 read by InkStitch.PNG)

### LINKED ISSUE #703: Support Color File Formats (EDR, INF, COL)
Looking at the pyembroidery repository I noticed, that there are color file formats present.
Maybe we also could support them?

Reference: https://github.com/EmbroidePy/pyembroidery/pull/78

### PR DESCRIPTION
**Pull request by kaalleen**
We do need an update of our pyembroidery library.
This is the first test to accomplish that.

Fixes #516
Fixes #703

### CODE REVIEW

**Comment by kaalleen** [comment]
What's new in here:

**Embroidery formats (read)**
* .hus: Husqvarna Embroidery Format
* .zhs: Zeng Hsing Embroidery Format

**Color formats (read & write)**
* .col : Color format.
* .edr : Color format.
* .inf : Color format.

**Stitch formats (read  & write)**
* .pmv : Brother Stitch Format.

**Image (write)**
* .png : Portable Network Graphic (line art)

**G-Code**
* The export file format is not .txt anymore but **.gcode**

**Plus bug fixes**

**Review by lexelby — APPROVED** [review]

**Comment by kaalleen** [comment]
Yes, thanks for searching the corresponding issue. I added it to the list :)

**Comment by JSEHV** [comment]
Can it be pulled into a development release, so we can test it out?

**Comment by lexelby** [comment]
Sure!  Every branch gets a development build automatically.  Here's the one for this branch: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-pyembroidery-update1435

**Pull request merged**
