### PR TITLE
prevent mac build freeze

### PR DESCRIPTION
**Pull request by lexelby**
I'm sick of the mac build getting canceled after 6 hours when signing never completes.

### CODE REVIEW

**Comment by lexelby** [comment]
of course now it's not freezing up...

**Comment by lexelby** [comment]
Great! I'll close this.

**Comment by kaalleen** [comment]
Maybe I was wrong. Electron builder is now updated and it still fails sometimes.
I'm going to reopen this one...

**Comment by kaalleen** [comment]
Closing again :D

We do not really need to sign with the electron builder, we sign it later on anyway.

**Pull request closed without merging**
