### PR TITLE
deal with None encoding in python 2

### PR DESCRIPTION
**Pull request by lexelby**
Fixes the issue mentioned in https://github.com/inkstitch/inkstitch/pull/489#issuecomment-515785200

cc @kaalleen

### CODE REVIEW

**Comment by kaalleen** [comment]
Oh, ok. Looks like I was doing it a bit too complicated ;)

**Comment by lexelby** [comment]
Oh, your code style was fine.  It's just that apparently sometimes `sys.stdout.encoding` can be `None` in Python 2, in which case we get an exception.

**Comment by kaalleen** [comment]
I had a different approach for it in the macOS version branch - and it was too complicated.
I just saw that the error appeared after the python3 changes, so I was checking for python versions, instead of simply handling the `None` :D I removed the extra code when I saw this branch here.

**Comment by lexelby** [comment]
Oh!  I understand now :)

**Pull request merged**
