### PR TITLE
Support various macOS Versions

### PR DESCRIPTION
**Pull request by kaalleen**
I have no idea what I am doing.
Just hoping, that it is really that easy...

Well, we'll see.

### CODE REVIEW

**Comment by kaalleen** [comment]
We created builds for various macOS versions. Travis said, it was successful. Yet I have no possibility to test the outcome. It would be nice to get test results for these three macOS versions:

**macOS 10.14	(Mohave)**
Download: https://github.com/inkstitch/inkstitch/releases/download/dev-build-mac-version-test/inkstitch-mac-version-test-osx-xcode11-x86_64-en_US.tar.gz

**macOS 10.13	(High Sierra)**
Download: https://github.com/inkstitch/inkstitch/releases/download/dev-build-mac-version-test/inkstitch-mac-version-test-osx-xcode9.4-x86_64-en_US.tar.gz (nothing should have changed, but it'd be good to test it nevertheless)

**macOS 10.12	(Sierra)**
Download: https://github.com/inkstitch/inkstitch/releases/download/dev-build-mac-version-test/inkstitch-mac-version-test-osx-xcode9.2-x86_64-en_US.tar.gz

**Comment by kaalleen** [comment]
I had the mac versions tested and they were working fine (even on sierra, which we could support now!). But there was an issue with electron (print). All versions had the same issue: first the electron part had to be given special permission to start. Then it opened, but displayed no content (white page). With the manual install everything worked fine.
Second issue is within the simulator. The newly added scale was upside down on all three systems?!?

**Comment by kaalleen** [comment]
I got the confirmation that on the latest Ink/Stitch release we have the same issue about the print preview - tested on high sierra (the content of the electron window is absent and just white).
The same issue was reported by @ALPHAMOTIF a while ago: https://github.com/inkstitch/inkstitch/issues/474#issuecomment-503909912

This is a bigger concern since we are planning to convert the whole gui into an electron app and it should be running on all systems.

Notarizing apps seems to be mandatory in future, otherwise the electron app cannot be opened and mac users will receive a message shown in this article: https://electronjs.org/docs/tutorial/code-signing

**Comment by lexelby** [comment]
Hmm, I see.  If signing apps is required, I wonder why ink/stitch itself doesn't have to be signed?

**Comment by kaalleen** [comment]
> I wonder why ink/stitch itself doesn't have to be signed?

I wondered about that too. My only explanation would be, that it recognizes only the electron part as a standalone application. But I am not very familiar with the mac operating system. Maybe it is also a problem that might be solved when we move them template into the electron app itself?!?

**Comment by kaalleen** [comment]
The last build of this branch failed, but I only changed names of the output file from lower to upper case. How can I ask travis to run the build process again? (I deleted the upper case builds from the release page).

**Comment by lexelby** [comment]
I have no idea. :(  I think Ink/Stitch is also in a .app directory?  Very confusing.

**Comment by lexelby** [comment]
You can re-run a build by clicking the "restart" button on the build details page.  If that doesn't work, just push an empty git commit (`git commit --allow-empty`)

**Comment by kaalleen** [comment]
> I think Ink/Stitch is also in a .app directory? Very confusing.

I don't know, honestly.

> You can re-run a build by clicking the "restart" button on the build details page.

Ah, thanks for the hint! I just never tried to login on the travis page. And I thought I was missing out something :D

I am just still not sure, if we should also go for el capitan, since we had requests for it. But I've read somewhere, that electron only works up from sierra. I don't know if that it true or not.

The electron white page has nothing to do with this pull request. Do you think we could merge this? 

Changes on the stub.py have to go into the next release. Otherwise we will get many complaints, since we build with python 2 and not with python 3. (TypeError: decode() argument 1 must be string, not None)

**Comment by lexelby** [comment]
Oh right, thanks for the reminder on the decode() None thing.  I opened #503 to fix that (I think)

**Comment by kaalleen** [comment]
Doesn't seem to do the trick for El Capitan. But we have macOS versions for Sierra, High Sierra and Mojave. Electron (print preview) doesn't work correctly, but this is also the case for master. This basically adds support for Sierra (10.12). I am going to merge it now.

**Pull request merged**
