### PR TITLE
Language-Stylesheets for Print-PDF

### PR DESCRIPTION
**Pull request by kaalleen**
Reference: #1131

@AlexxNB this uses an additional stylesheet now. What do you think?

### CODE REVIEW

**Comment by AlexxNB** [comment]
Neat, thank you! This solves issue.

Only one moment maybe...  Perhaps we can separate default font to the `en.css` or `default.css` and include this if there no CSS file for current locale? There may be some unexpected issues when we will rewrite styles, maybe not...
 and then
And one more thing =)  We can add a set of CSS custom properties like `--font`, `--font-details` and then locale css file will be something like this: 

```css
@font-face {
  font-family: 'FiraSans';
  ...
}

@font-face {
  font-family: 'FiraSans Condensed'; 
  ...
}

:root{
   --font: 'FiraSans', sans-serif;
   --font-details: 'FiraSans Condensed', sans-serif;
}
```

This may give more independency from markup, you can change document structure in future, but with `font-family: var(--font)` appearance won't break.

**Comment by kaalleen** [comment]
> Only one moment maybe... Perhaps we can separate default font to the en.css or default.css and include this if there no CSS file for current locale? There may be some unexpected issues when we will rewrite styles, maybe not...

I think there is not really a need for that. CSS overwrites everything with the language files from the default (if you write the classes correctly, which I didn't in the first place, sorry for that). But I like to keep the default, just in case someone misspells something in the language file (as I just did), so this is kind of a fallback. If you set your fonts in `body` and `condensed` correctly, it will not use the fonts defined in the main file at all.

My css knowledge has aged a little. But when I see your code it looks like you are expecting scss to be used. We only use simple css in the print-pdf extension. But this task works as well with simple css. I just added a 'condensed' class. It is a good idea to not bind it to job-details as before, but create an extra class for it. Thank you for the hint.

**Comment by AlexxNB** [comment]
> My css knowledge has aged a little. But when I see your code it looks like you are expecting scss to be used.

No, custom properties are native CSS variables.

**Comment by kaalleen** [comment]
Oh, ok :)

Just as a side note. If you want to work on this branch, you can just push your improvements into it. My CSS knowledge is really getting old, so you may improve this if you like. Looks like you know whole a lot more than I do :)

**Comment by AlexxNB** [comment]
I don't think that we need some other changes right now. I'll fix `ru.css` if necessary...

**Comment by kaalleen** [comment]
Ok, great. Then I will merge it into the main branch.

**Pull request merged**
