### PR TITLE
fix linux build

### PR DESCRIPTION
**Pull request by kaalleen**
apt-get update

### CODE REVIEW

**Comment by lexelby** [comment]
This is like a game of whack-a-mole! Sheesh.

**Comment by kaalleen** [comment]
Wow, this is so annoying. At least linux is working :D 
Shall we use this branch for the upcoming mac fix too?
But just to say... this is not what I am good at.
Maybe it'd be better if you take your chances on this whenever you find the time?!

**Comment by lexelby** [comment]
Sure, we can use this branch for both.  I'm reticle at Mac too though!  I'll see what I can do.

**Comment by kaalleen** [comment]
Great, this is working now. Thanks. I will merge it.

**Comment by lexelby** [comment]
Oh good! Lucky guess :)

**Pull request merged**
