### PR TITLE
GPL-3.0-or-later

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
https://github.com/inkstitch/inkstitch/issues/1047

I copied the license header to README.md and inkstitch.py.  I placed the GPL in the LICENSE file.  I added LibreJS license tags to any JS I came across.

### CODE REVIEW

**Comment by kaalleen** [comment]
Nice thank you.
@lexelby could you have a look at it?

**Comment by lexelby** [comment]
Thanks! This is my first open source project, so I'm kind of new to the licensing thing.  Can you help me understand what drives these changes?

**Comment by TechnologyClassroom** [comment]
The license headers go at the beginning of files that contain code.  The full text of the license goes in the LICENSE file.

The other changes have to do with JavaScript licensing with LibreJS.  Those are not as common.  They add comments before and after JavaScript code snippets to signify the license of individual pieces.  When run, these are ignored unless the user is blocking all scripts that do not explicitly state a license.

**Comment by lexelby** [comment]
Are you saying we need the license header at the top of every single Python and JavaScript file?

What are the consequences of we don't do that?

**Comment by TechnologyClassroom** [comment]
Yes, it is best practice to have the headers at the top of each file.

1. The license header signals whether it uses this license version only or any later version.  In this case, it differentiates between whether it is GPL-3.0 or GPL-3.0-or-later.
1. If the files get separated, you want others to still know they can use the code under a free license and what project it came from originally.

If you do not add license headers, the world does not end.  It is just best practice.

**Comment by lexelby** [comment]
I don't know... I'm having a hard time justifying it in my mind.  There are a lot of Python files, and the header is a long chunk of text.  We'd have to somehow modify every file when it changes, or worse yet, track who holds copyright on pieces of individual files... It all just seems onerous.

As I understand it, our copyright exists whether we declare it or not.  If the files get separated from the project, so be it; the people involved can come here to see what their rights (and responsibilities) are.  

I think our intent is clear.  Do you think it's not?  Am I missing a legal subtlety?

**Comment by TechnologyClassroom** [comment]
The copyright lines of all of the headers do not need to match across the project so this is more of a one time onerous task.

**Comment by lexelby** [comment]
I just saw #1047 and realized that perhaps I should address my questions to @donaldr3 :)

**Comment by lexelby** [comment]
@kaalleen What do you think?

**Comment by kaalleen** [comment]
Hm, I am unsure about this. My first reaction has been the same as yours.

Then I did some research.

GPL howto:
https://www.gnu.org/licenses/gpl-howto.en.html

They clearly state, that it should be in every file header and give a reason here:
https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile
(Possibility for the code to become nonfree under certain circumstances).

Next I have been looking at the source code of various open source projects. All of them had the information included in the header.

So maybe it's not a bad idea after all. But it would be quiet a lot of boring work to do.
----
Javascript links: https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by kaalleen** [comment]
From an Inkscape file:

```
 * Authors: see git history
 *
 * Copyright (C) 2018 Authors
 * Released under GNU GPL v2+, read the file 'COPYING' for more information.
```

**Comment by lexelby** [comment]
Hmmm.  I still think the risk of individual source files being disconnected from the project is overstated, but I do like that "see git history" method.  Short, sweet, and no need to keep it updated.  I think we should also remove the individual names from the COPYING file since they're very outdated -- you're not even in the list!

Adding to every file is easy with `sed`.  I'll take care of it when I get a chance.

**Comment by kaalleen** [comment]
Ok, great.

Just a short notice, so we will not forget. When updating the license file we will need to keep in mind to check the about extension. It reads the license and displays it to the user. I don't know how inx templates will handle long text. Maybe we need to update it or even remove the license info from there.

**Comment by lexelby** [comment]
Closing in favor of #1083

**Pull request closed without merging**
