### PR TITLE
Fill Centerline

### PR DESCRIPTION
**Pull request by kaalleen**
Adds a method to generate a centerline for polygons.

### CODE REVIEW

**Comment by kaalleen** [comment]
I'm going to merge this. Since it is a separate extension it will not harm any other functionality.

This is a bit like the centerline tracing from Inkscape itself, except that it works on vector graphics. Additionally it is able to take in cut lines to improve the result.

fill_to_stroke

**Comment by lexelby** [comment]
Your A makes me think... Maybe we could use this plus auto-route satin to make a true "automatic satin" extension that converts arbitrary shapes to satins?

**Comment by kaalleen** [comment]
Actually I thought to use this extension and go a little further. When they defined their cutlines well, we could check where the centerline ends and know at which parts of the fill we need to cut open. This way we could even keep varying width. .. Rails may be a little bit more tricky though. Don't know if that all together would work well enough. If not, I thought, we could do what you said.

**Comment by lexelby** [comment]
I was thinking we could create rails by drawing a line perpendicular to the centerline and seeing where it intersects with the fill border.  Do that enough times and maybe you'll be able to turn the result into rails...

**Comment by kaalleen** [comment]
Oh yes of course :)

**Pull request merged**
