### PR TITLE
Software freedom day tutorial

### PR DESCRIPTION
**Pull request by bkmgit**
@kaalleen It may take a few days to get a stitchout. Any other suggestions for improvements are welcome.

### CODE REVIEW

**Comment by kaalleen** [comment]
Thank you for preparing the tutorial with such a detailed description.

Just one remark. List point 10 has a space before the dot (10 .Text). This won't work. Is has to be 10. Text

The following you can ignore if you like, but I think it would increase readability. Set empty lines in between the list points and before and after the images. For this to work you'll have to set spaces at the beginning of each new line of text to bring it on level with the list. For example three spaces when list number is one digit (8. ) or 4 spaces for the 2 digit list points (11. ) 

This would look like this:

```
[...]
9. For each of the rays, break up the paths into two lines with an equal number of
   nodes.  Add a starting segment with a beginning lock stitch on the portion of the
   ray furthermost from the sun. Create a reversed ending segment with with only an
   ending lock stitch on the portion of the ray closest to the sun.

   ![Screen shot of a ray showing dotted starting, left and reversed ending right segments](/assets/images/tutorials/software-freedom-day/SFDTutorial15.png)

10. For each of the letters, break up the paths into two lines with an equal number of
    nodes.  Add a starting segment with a beginning lock stitch. Create a reversed ending
    segment with with only an ending lock stitch.

    ![Screen shot of a letter showing dotted starting, middle and reversed ending segments](/assets/images/tutorials/software-freedom-day/SFDTutorial16.png)

11. If the embroidery machine used supports a [...]
```

**Comment by bkmgit** [comment]
Done.

**Comment by kaalleen** [comment]
Nice, it's looking much better now.

Can you set an indent for this code block as well (in point 12)? Otherwise point 13 will be displayed as an other point 1 and the following line will also have issues.

```
CC BY-SA 3.0 Deed Unported
https://creativecommons.org/licenses/by-sa/3.0/
Modified for embroidery from the originals
https://wiki.softwarefreedomday.org/Logos
```

**Comment by bkmgit** [comment]
Thanks. Done.

**Comment by kaalleen** [comment]
Thanks, looks good to me. I'll approve the changes, then merge when you feel ready.

**Review by kaalleen — APPROVED** [review]

**Comment by kaalleen** [comment]
Oh, I was a little bit fast here. Could you update the permalink? Right now it is /tutorials/applique/ which would be a conflict with the applique page.

**Pull request merged**
