### PR TITLE
add ties checkbox

### PR DESCRIPTION
**Pull request by kaalleen**
Adds a "ties" checkbox to stroke params.
Cannot find the issue where it was requested right now...

### CODE REVIEW

**Comment by lexelby** [comment]
Hmm... I wonder if maybe we should do this using a visual command instead, so that we can support all kinds of objects at once?

**Comment by kaalleen** [comment]
Hm, looking at the code I would totally agree. But I think having it as a checkbox actually has an advantage: users can save their favorite method to the stitch preset without having to add commands to all the objects. They can easily select their own settings from the Params menu. What do you think?

**Comment by lexelby** [comment]
That is a very good point!  What if we put the ties param in EmbroideryElement so that all objects have it?

**Comment by kaalleen** [comment]
> What if we put the ties param in EmbroideryElement so that all objects have it?

Sounds good. I've included it there.

**Comment by lexelby** [comment]
How about this, to avoid having to set `stitch_as_is` in every Element subclass?

**Pull request merged**
