### PR TITLE
Experimental realistic stitch preview branch

### PR DESCRIPTION
**Pull request by capellancitizen**
A first attempt at adding realistic stitch preview to the stitch preview, which might be a start for #2770. Beyond just plumbing in the "realistic" option into the extension, the current filter causes Inkscape's rendering to lag significantly because it's fairly complex. I optimized/simplified the filter to one that runs much quicker, mainly by cutting down the number of steps and manually specifying a bounding box for the filter. The end result looks slightly different, but hopefully still acceptable:

Current:
current_realistic
New:
new_realistic

If you drag around the preview stitch plans, the stitch plan in `new_realistic.svg` (generated with this patch's filter) can be dragged with less lag than `realistic.svg` (using the current realistic filter).
[previews.zip](https://github.com/inkstitch/inkstitch/files/14971800/previews.zip)

There is a snag though, in that if you don't specify `inkscape:auto-region="false"`, [Inkscape will recalculate the region (see issue #6667 in Inkscape)](https://gitlab.com/inkscape/inbox/-/issues/6667) - in this case going from 102% the size of the region to 640% of the size, making the calculations more expensive then they need to be. Unfortunately, if you *do* specify the size, it puts up an error message because Inkscape apparently doesn't recognize its own `inkscape:auto-region` parameter when parsing extension output. [I've opened inkscape #10227 to follow up on this.](https://gitlab.com/inkscape/inbox/-/issues/10227)

errormessage

So that remains a blocker of sorts: If we remove the `inkscape:auto-region` parameter it runs slowly: better than the current filter, but far slower than we'd probably want given it has to process something like 36x the pixels. With that parameter, it performs reasonably even with ~5000 realistic fill stitches on-screen.

### CODE REVIEW

**Comment by lexelby** [comment]
Wow, nice!  Thank you for working on this.  As it turns out, @kaalleen and I were just talking the other day about doing something like this, so it's excellent timing that you're working on it.

I pushed a commit that seems to fix the inkscape XML parsing error by gratuitously re-declaring the inkscape XML namespace.  Shouldn't be necessary, but it gets the job done, so great!

**Comment by lexelby** [comment]
I added a few commits, I hope that's okay!  I noticed that the filter always showed up black, even for colored thread.  I did have to add one more filter effect to restore coloration.  I also adjusted a few of the settings, including switching to a `feDiffuseLight` (I didn't even know that existed!), and I like the result better.  What do you think?

I really wish we could avoid the thing where you see a lighting difference between sections of fill stitch that abut but are stitched at different times.  This does at least make that less severe.

**Comment by capellancitizen** [comment]
Yeah, by all means, go ahead and commit to the branch as you like. I thought I tested for the filter working with other colours, but I clearly regressed when trying to simplify it down, whoops. I think diffuse lighting vs specular lighting probably doesn't matter much when the areas are (realistically) only going to be tiny regions - Though FYI I think the most recent commit is using specular lighting, not diffuse. I might suggest changing the azimuth so it points from the top, if only because that's where the light will most likely shine on the embroidery if you were to hold it up in front of you like how it's shown on the screen.

> I pushed a commit that seems to fix the inkscape XML parsing error by gratuitously re-declaring the inkscape XML namespace. Shouldn't be necessary, but it gets the job done, so great!

Good fix. It is redundant, but if it makes Inkscape happy...

**Comment by capellancitizen** [comment]
I changed the way the "whiskers" on the realistic stitch are set up to provide a better boundary around the realistic stitches, I noticed it could still get cut off at some angles. Plus extra comments, because who doesn't love those?

**Comment by lexelby** [comment]
Oops!  I meant to say _distant_ light, not diffuse.  Diffuse didn't really look all that good when I tried it.

**Comment by lexelby** [comment]
I was tinkering around with the filters in Inkscape and got some interesting results.  What I really want is for satins to look like real satins, that is, it sort of emerges as a wormy-looking body, not a ton of individual stitches.  I noticed that I got a cool effect if I just do Path -> Combine:

image

But of course, that gets rid of the texture of the stitches themselves.  So I made a copy before combining.  I did Combine on the one lower in the stack, and I left the upper one uncombined.  I removed that last `feComposite` so that the top one is just black and white again.  Then I set the Blend Mode to Hard Light in the Fill and Stroke settings for the group.  I lowered the opacity to 20%, and I got this:

image

This gives the kind of emergent shape I want, plus the texture of the threads, for not much more computation than what we already have.  What do you think?  Here's the SVG -- interesting that it renders differently in the browser :)

lex_realistic

**Comment by capellancitizen** [comment]
Ooh, that looks really good! Could you zip that .svg and post it here? I'm getting the issue where github mangles the SVG file again. Wrapping it in a .zip protects it.

**Comment by lexelby** [comment]
Oh sorry, here it is:

[lex_realistic.zip](https://github.com/inkstitch/inkstitch/files/14986482/lex_realistic.zip)

**Comment by capellancitizen** [comment]
image
Hm. This approach doesn't seem to work out the box in every case. There's some more tuning to do here.

As for implementation, doesn't seem like inkex has a path union function out of the box, but I guess we have shapely and other things to accomplish that. Alternatively, we might be able to get the same effect basically by applying a `filter` to the stitch group itself.

A problem that I definitely have with it is that the filters seem to have all kinds of internal artifacting, like the rectangles in the center of the circle fill in the attached screenshot. I suppose these are inherent problems with using the gaussian blur of the alpha channel as a heightmap if the filter's rendered at a lower resolution or something. I'll tinker with it over the next few days and see if I come up with anything, everyone else if free to do so as well.

**Comment by lexelby** [comment]
Maybe we need a blur after the specular lighting to smooth the artifacting?  I know that's another filter and will make things slower, but we can borrow an idea from the electron side to fix that: call out to inkscape in a subprocess to render the filters down to a PNG and include that in the user's SVG instead.

**Comment by lexelby** [comment]
A little blur does get rid of the artifacting quite nicely.  Here's a look at my two-layer approach on a real design:

image

It's pretty good, although I'm still not a fan of the way that stitches seem to get darker and darker, as if there's an implied Z increase when stacking paths.  Here it is with only the lower layer:

image

(ignore the jumps, I made this when I had a machine that couldn't trim)

I wonder if we can handle the stitch texture with simple paths with stroke and fill, perhaps with gradients or something.  That would make this whole thing much less computationally intensive, too.

**Comment by lexelby** [comment]
I made the stitches thicker to reduce the gaps between stitches for typical row and zig-zag spacing.  I also added the gaussian blur, let me know what you think.

**Comment by capellancitizen** [comment]
Earlier when I was tooling with this, I did also have a gaussian blur after the lighting to avoid the stair stepping, but then it does make it heavier once again. I wonder if we can just tweak that initial gaussian blur and/or the lighting parameters like the height to minimize the stair-stepping in the first place, it's annoying to have to go over the whole image again in another pass.

 > The gaussian blur height map thing was the best I could come up with, but I would love to see another approach if you can think of one. We could also scrap SVG filters entirely and use 3d rendering -- I just have no knowledge of 3d programming.

I have a little background in 3d graphics, so I was considering possibly stealing the technique of [deferred shading](https://en.wikipedia.org/wiki/Deferred_shading), but for CSS. I was considering if we could skip the gaussian blur by baking the heightmap into the shape by way of a gradient or even a texture. That approach, we could basically have the stitches render out a height map and alpha mask, then a filter on the stitch group applies the specular lighting and the colour tint. Worst case, that would mean performing the lighting calculation on many pixels that are inside the stitch layer's bounding box but outside the stitch area, but we would avoid the duplicate costs of overdraw, especially for completely occluded stitches like underlay, and a lot of satins and fills would probably have a lot of overdraw. It also probably means we need one filter definition for each colour because I don't think you can parametrically pass parameters to the filter like you can with most 3d shaders. This is all theoretical though, so please take it with a grain of salt.

To get proper lighting effects without filters at all we'd probably need gradient meshes or something? That's outside my scope of knowledge.

**Comment by capellancitizen** [comment]
new_realistic_deferred
[new_realistic_deferred.zip](https://github.com/inkstitch/inkstitch/files/15017790/new_realistic_deferred.zip)

Here's an example of deferred shading like I mentioned, though the heightmap generation is still built off of gaussian blurring. If you disable the filter on the stitch group element itself, you'll see the stitches render out as a heightmap. The performance seems to be kind of a wash, the matrix multiplications to remap to/from the alpha channel probably don't help. Shrug.

**Comment by lexelby** [comment]
Ah, I think I understand, you're hoping that doing specular lighting only once might save time on rendering?

**Comment by capellancitizen** [comment]
Indeed. However it doesn't seem like it saves us much, because it requires we do additional colorspace matrix transforms that seem to cancel out the benefit. It could possibly be useful if we can change the stitches to produce their heightmap to skip the gaussian blur on each element, but I'm not sure there's a good way to do that with SVG. The cleanest way I could think to do that would be to render out a heightmap texture where the center is stretched, much like in a 9-patch UI element, but if there's a way to do that with SVG I don't know it.

I think if we take the realistic preview as it is in the branch right now, that's probably a good functionality win for now even if the realistic preview doesn't end up looking any prettier than it currently does. With the optimizations it's at least fast enough to not drag Inkscape to a crawl. 

For other possible improvements, I suppose we could eke out a bit more performance by removing underlay stitches from the realistic preview, because they'd be covered by the other stitches, and unlike the simulator you can't step stitch by stitch through the pattern. It might be possible to streamline the transforms applied to the path elements too: I did a quick optimization so that the transform matrix is calculated once and applied once to the path, rather than being applied multiple times, so at least there's a little improvement in speed rendering the realistic stitches.

**Comment by kaalleen** [comment]
I just had the chance to test this branch and I like what I am seeing so far!!! Also the performance has improved a lot for simple designs. However when I try this on a complex design and try to zoom in, Inkscape doesn't respond anymore and I had to exit Inkscape without a chance to save (if I wanted to). So we definitely have to think about performance. Removing all the underlay seems reasonable, but at times the top stitching isn't so dense and sometimes the underlay is part of the design. So we must be careful with removing it.

Not sure but maybe it actually would be best to render the stitch plan for realistic preview to png instead of using the svg filters directly as we have to expect that it will be used on complex designs on slow computers?

**Comment by capellancitizen** [comment]
Yeah, we can render it out to a png and embed that, same as alt-b.

**Comment by lexelby** [comment]
Yeah, I definitely think we should render to PNG if we can pull it off.  You're right that it's better now than it was before.  I think we should merge this as it is and do further improvements in later PRs, just to avoid a mega-PR if nothing else.  :+1:?

**Review by lexelby — APPROVED** [review]

**Comment by capellancitizen** [comment]
I'd be fine to merge, then, as rasterization will introduce a bit more complexity, assuming @kaalleen is fine with it. But then, the rasterization probably won't add *that* much additional complexity, it'll call out to inkscape via `inkex.Command` to render it to png.

**Comment by capellancitizen** [comment]
Rasterization wasn't too complex to add. I think it probably makes some sense to go down this route. Only thing is, we probably want to allow the user to say what resolution they want the preview to be rasterized, rather than a fixed value. Do we have a preference between:

- Number field below the realistic checkbox letting the user input a resolution multiplier (that just goes ignored for non-realistic output)
- Replacing the realistic checkbox with a "preview type" dropdown with options like "simple" (or whatever we want to call the non-realistic option), "realistic 2x", "realistic 4x", "realistic 8x", "realistic 16x", "realistic vector (slow)"

**Comment by kaalleen** [comment]
I'm fine if it goes into an other pull request.
For the selection I'd prefer a dropdown (second option).

**Comment by capellancitizen** [comment]
image

How it looks now. I'm happy with it, open to feedback of course.

**Comment by lexelby** [comment]
How much time does x16 actually take vs x2?

**Comment by capellancitizen** [comment]
Ballpark experimentation, if I take a single square of 140mmx140mm with default fill settings (~37k stitches):
- Simple visualization (missing the cache, so including the actual stitch planning): ~11s
- Simple visualization (All others from here out are cache hits): ~2s
- Realistic x2: ~29s (incl. ~2s loading time)
- Realistic x4: ~33s (incl. ~2s loading time)
- Realistic x8: ~36s (incl. ~2s loading time)
- Realistic x16: ~51s (incl. ~2s loading time)
- Realistic Vector: ~12s to finish loading (incl. ~2s loading time) to ~25s to finish rendering all stitches, ~15s for each additional re-render

The increased resolution doesn't matter much up to x8, and x8 is probably a good enough factor to look good at a reasonable zoom. The rasterization round trip takes up about 10-12 seconds on top of the realistic stitch rendering in the first place.

**Comment by capellancitizen** [comment]
I'll merge this tomorrow if there are no objections.

**Comment by lexelby** [comment]
I tend to be a fan of avoiding giving users more options if I can avoid it -- especially if those options don't do anything useful.  If the resolutions below x8 don't matter, let's skip them, especially since it doesn't take much more time to do x8.  Perhaps "standard" and "high quality" instead of x8 and x16?

Other than that, merging sounds good to me. 👍

**Pull request merged**
