### PR TITLE
Fill Pattern

### PR DESCRIPTION
**Pull request by kaalleen**
Well, here is just the beginning, just what I have put together today.

My idea would be to have the user apply a pattern to their element. We could use the color of the stroke, which then should set for the element. Then we use the path of the pattern to cut through the actual fill rows later on.

I have prepared it so far, that we recognize the pattern path and apply all the possible transforms. Next we would need to make it a tiled pattern which covers the original element, before we can use it to cut through the lines.

What do you think of it so far? Do you have an idea how to proceed and create the full pattern?

### CODE REVIEW

**Comment by kaalleen** [comment]
Looks like I got lucky when I tested the transformations the first time. I just wanted to test them again and it's not really pushing the shape into the right spot. Maybe I should have a closer look at it again...

**Comment by lexelby** [comment]
Oh wow, I had no idea about SVG's fill pattern stuff.  I really like the way you're going with this.  Way easier for the user to understand than what I had been thinking.

Seems to me like the hard part here is to ensure that we can calculate the tiled pattern in Ink/Stitch exactly as the user sees on the screen.

I was hoping maybe the new `inkex` for Inkscape 1.0 might support patterns, but it doesn't, at least it doesn't expand the tiling for us.  I can't find any existing library that does that.  So I guess we're on our own.  We'll have to read and understand the SVG spec and properly parse and render the patterns.  I think that's going to become much easier with inkex 1.0, especially when you consider that patterns can themselves have objects with fill patterns (augh).

I did notice one thing that I hadn't realized about Inkscape 1.0: you can put an extension, including its INX files, in its own directory!  That would make the installation process _way_ easier.

Maybe we should start working on the switch to inkex 1.0?

**Comment by kaalleen** [comment]
> Maybe we should start working on the switch to inkex 1.0?

That's what I have been thinking. I already started to work on it. It's quiet a lot to do since many functions have changed and my time is very limited recently. I could prepare a pull requests so we can follow the update process better, but it is still in the very beginning.

**Comment by lexelby** [comment]
Sure, opening PRs sounds good.  I'm not really sure how to start, since we need to transition to python 3 as part of this...

**Comment by lexelby** [comment]
Oh wow, it turns out I'm wrong about that!  Inkex 1.0 supports python 2 and 3.  Since inkex < 1.0 only supports python 2, that pretty much tells us what order to do things in: we should switch to inkex 1.0 first and then convert to python 3.

**Pull request closed without merging**
