### PR TITLE
switch from libembroidery to pyembroidery

### PR DESCRIPTION
**Pull request by lexelby**
Ink/Stitch now uses pyembroidery for reading and writing embroidery files.  All mentions of libembroidery have been replaced.

Much of the related code is significantly simplified, and none of it is made more complicated.  Several nasty hacks are a thing of the past.  This diff has a lot of red in it. :D

Thanks, @tatarize!

### CODE REVIEW

**Comment by lexelby** [comment]
I integrated #228 into this while I was in there.  Memo to self: probably need to integrate the fix for https://github.com/inkstitch/pyembroidery/issues/48.

**Comment by wwderw** [comment]
I'm wondering, should we include a CSV in the zip exporting function as well?

It's not a demanding thing at all, I just wondering if it would be worth it enough to include that option for the zip exporting function and save as copy function?

Thoughts?

**Comment by wwderw** [comment]
> I'm happy enough to include CSV functionality, if you the  user think it is useful.  I know you've mentioned in the past that you  like to tinker with the CSV file.

I do like to tinker with it, especially when I was using Thred, as that enabled me to add trims etc in manually.  Tedious, but it made for more production friendly designs.

>That said, there is no CSV reader in pyembroidery, so it wouldn't be possible to modify the CSV file and reload it...

My workflow is/was to use the standalone portable libembroidery CLI tool.  Although with the change in those 5 formats, it may not viable any more.

**Comment by lexelby** [comment]
Ah!  Well, good news: this PR already includes a replacement cli tool, `pyembroidery-convert`.  Hopefully that should give you what you're looking for.

**Comment by tatarize** [comment]
It wouldn't be too hard to add a reader for csv files. The writer was only to help with debugging, but I matched libembroidery formatting but it would provide some extra degree of interoperability. If you'd want it for your workflow, just raise an issue on pyembroidery.

**Comment by tatarize** [comment]
Also, inkstitch/pyembroidery#48 could be made default instead, it just that it seems like a breaking change. It's literally change a True to a False. I have some plan to include needle information in color changes which would also be breaking. Switching a default at 1.3.0 wouldn't be an issue. It woulda been default but I foreswore breaking changes after this pull started being built.

**Comment by lexelby** [comment]
@wwderw I'm wondering if I still don't quite understand how C00/STOP works.

@tatarize seems to think my understanding is incorrect (https://github.com/inkstitch/pyembroidery/issues/48).  My understanding of things comes from our conversation here: https://github.com/inkstitch/inkstitch/pull/29

Let's imagine a design with a very simple applique.  The design is:

1. some other part of the design, intended to be sewn in black (maybe some satins or something).
2. TRIM
3. JUMP to where we want to do applique
4. black running stitch around a circle for 50 stitches (tack-down)
5. COLOR CHANGE
6. black satin around the circle

My understanding is that you'd want me to insert an "artificial" color change into the design after the TRIM at step 2.  Then you'd assign your codes like this:

1. start of design: C01 (needle 1, let's say that's the one that has black thread).
2. artificial color change (before the tackdown): C00
    * says to continue sewing with black thread and halt the machine at the _next_ color change
3. color change at step 5: C01
    * says to sew the satin circle with black

The key here is that, from my understanding of our conversation, C00 says "continue sewing with the previous color, then halt the machine next time you find a color change".


@tatarize seems to think it works differently than this.  He'd want no color change to be added after the TRIM.  Then we'd do:

1. start of design: C01 (black)
2. COLOR CHANGE after the tack-down: C00
    * says to halt the machine _immediately_
    * after resuming, it will continue sewing with the needle that was selected previously

The key here is whether the halt occurs at the point where you set C00, or at the next color change.

As far as I can tell, some machine file formats actually have a concept of "STOP", while most just encode a "STOP" in the same way as a color change.

**Comment by wwderw** [comment]
Let me create a file using the pyembroidery dev version and see how it shows up on my end.

The way it works in Wilcom and the way that we had it InkStitch before is what I'm used to.  The biggest change that we would have to do is how it's represented on the PDF print out.

Let me create a quickie with a stop and see how it fairs with the latest dev version.

**Comment by wwderw** [comment]
Well, that didn't get too far.
Params generated this error:

py params error

**Comment by wwderw** [comment]
> The key here is whether the halt occurs at the point where you set C00, or at the next color change.

I missed this the first go around.  You are going to want the stop at the point that it's inserted.  This is especially going to be the case for the custom stop point of #160.  We aren't going to want it to go at some other point later on down the line, but exactly where it's placed.

**Comment by lexelby** [comment]
Oops.  I'll fix that crash tomorrow, sorry!

> I missed this the first go around. You are going to want the stop at the point that it's inserted (the way it has been in Ink/Stitch). This is especially going to be the case for the custom stop point of #160. We aren't going to want it to go at some other point later on down the line, but exactly where it's placed.

Understood, but that's not quite what I'm asking.  On your machine, do you set C00 at the _start_ of the tack-down stitches or at the _end_?

**Comment by wwderw** [comment]
> On your machine, do you set C00 at the start of the tack-down stitches or at the end?

You would actually have a stop **at the end** of the placement stitch, which would come before the 1st tack down.

The stitch schema for a cutting in place applique object is: Placement (stop) -> 1st Tack Down (stop) -> 2nd Tack Down (Maybe stop, just depends on the situation) -> Cover Stitch.

The original tick box operation provided the necessary functionality.

**Comment by lexelby** [comment]
Okay, got it.

Just to clarify, it seems like this is a reversal of what you said in #29?

> C00 does 2 things. 1, it tells the machine to use the previous color assigned (if this is at the beginning of the design, it uses whatever needle is active on it right then, if that is the wrong needle, the operator will have to change it before starting the design) and when the machine hits the end of this color block to stop.

**Comment by wwderw** [comment]
I think I know what's going on:

>if this is at the beginning of the design

I think this is the concerning phrase.  "If this" isn't in reference to the stop, but if the placement stitch (for this example) is at the beginning of the entire design.  You don't have the ability to enter C01 first, because it didn't have a color change to begin with.

The operator would have to manually change the machine to the C01 (in this example) before the pattern even starts.  Otherwise, if the last needle that was used in the previous project was say C15, it would use C15 then do it's first stop.

**Comment by lexelby** [comment]
Okay, so now you seem to be contradicting this:

> You would actually have a stop at the end of the placement stitch, which would come before the 1st tack down.

I'm still just not getting this at all.  I think the only way I'm going to understand is to see this in action.  Can you make a video for me, showing me how you load a design with a stop in it and program the machine?  Go ahead and use wilcom to make the test design, and post the DST too.  I don't want you to use inkstitch because I don't want my previous attempts at implementing this to affect what you do. 

It'd really help to see examples of both scenarios: tack-down as the first element in the design and as a later element.  I'd also need to see the screen as you enter the various commands and needle assignments.

I'm sorry, I know I'm asking a lot here.  This is a great example of when it would be really useful for me to have access to a commercial embroidery machine.

**Comment by wwderw** [comment]
stitch list

Let's assume that the above is our needle assignments.  Everyone one of those has a stop.  No true color information.

The stops themselves happen at stitch 411, 929, 1513 and at the end of the design (which is going to happen anyway).

When you have C00 listed as the very first "color" assignment, the machine uses whatever color that is the active one (the last one used in the previous pattern that was stitched out).  The user has to advance to the correct needle when they have something like this.  That's what I was talking about when C00 falls at the beginning.  That first stop actually isn't until 411.

**Comment by tatarize** [comment]
In my little SWF single head machine it has a list of needles, usually this is:

1 2 3 4 5 6 7 8 10 11 12 14 15

Needle 9 and 13 have issues so we skip them. 

However if this is set in the machine to be;
1 2 3 4 4 5 1 2

This means we start with needle one. At color change we switch to 2, then 3, then 4, then we stop. This stop is the first time the machine requires human interaction since initially starting. Once we do what we need to do, we press the start button again. It continues with needle 4 unless we changed the active needle. Then turns to needle 5 at the next color change and needle 1 (which at this point might have a different thread depending on what the stop was for) then the next to needle 2. Then stop at the end of the of the file. 

But, the encode for it is \x00\x00\xC3 which is stop, and color change depending on context. 

We have sometimes entered this to be:
1 1 1 1 1 1 1 1 1.

Which means changing the thread on the first needle each time it stops. And thus doing all the color changes ourselves (which is what you get with single needle machines).

At the format level, they all generally say the same thing, and notably because this is sometimes done differently at the format level and should actually be a job left to pyembroidery. Admittedly some of this is ambiguous in the pyembroidery code and will have to be better sussed out, but generally stop is a stop without moving on to the next color, and color_change is a stop with moving on to the next color. Sometimes this info is in the file. It's usually in the color list, or the color_change_to_this_needle information and quite often you enter it into the machine.  In a number of cases, I'm still not quite sure because it depends so much on the machines in question.

**Comment by wwderw** [comment]
Do you send directly from the computer to machine without exporting to a format or do you export to DST (or whatever format) and move that to the machine?

If using DST, I can't imagine our experiences being different.  I could see it being different if using the computer connected to the machine.  

However, I'm just speculating.

**Comment by tatarize** [comment]
There's a usb slot on the little computer it runs. Loads the design from that. Then has a list for what order the needles go in the software. The computer hooks up to the stepper-motor, and controls that. We've been really tempted to dump the software, I'm pretty sure it runs DOS. And is actually a PC.

**Comment by wwderw** [comment]
So it reads like it goes from computer to machine.

This is probably were the difference is coming in.  If you were to export the design, put it on a CF/Jump Drive/Whatever conveyance of choice (probably not supported on your rig without retrofitting), then everything would need to be manually inputed in by the user for the colors/needles, stops etc. 

Most commercial software allows still for direct connection and the numbers that are associated with colors translate to needle positions.  So when you use direct connection, you bypass needing the screen that I showed.  I don't use that method, even when all my Windows instances were direct on hardware, I never did use it.

I can see how that situation would change the context of everything.

**Comment by lexelby** [comment]
@wwderw What is the purpose of setting C00 for the "0st" box at the top?  What are you telling the machine to do?

**Comment by lexelby** [comment]
Okay, got it.  So this really does mean that C00 boils down to:

1. Continue sewing using the currently-selected needle.
2. At the _next_ color change down the line, stop before continuing.

@tatarize: see what I mean?



@wwderw What happens if you don't bother with C00 at all, and just set a C01 twice in a row like tatarize suggests?  Does it stop when it gets to the second C01?

**Comment by wwderw** [comment]
I could put them all at C01 and it will only stop at the end of the design.  C00 has to be there on my Barudan machine for it to invoke a stop at any point other then the end of a design.

**Comment by wwderw** [comment]
I'm thinking, because tatarize is going through computer software, things are being handled via software that amount to the same thing that I'm doing, just not as visual apparent.

But not seeing what's going on at the machine, I'm speculating on that.

**Comment by lexelby** [comment]
Got it.  So we truly do need to introduce an extra color change, at least on Barudan machines.  And the Wilcom design you showed me in some other issue seemed to show that as well, where the software automatically broke a color block at stitch 50.

**Comment by wwderw** [comment]
> So we truly do need to introduce an extra color change, at least on Barudan machines.

Since it's the DST file version, I would say that any full fledge commercial machine would support that as well.

If I was running Direct Connection via software, I think it might show up differently on my end since I'm not having to deal with the embroidery machines own control panel, but the software.

**Comment by tatarize** [comment]
So when you say you trigger the sequins by setting it to like C01 or something, you actually set that like that?

My reading of this seems to be the C- elements are totally custom commands. Like you define them in particular ways but they could do things like trigger the sequin mode or stop, or change needle depending. And they don't have a 1 to 1 relationship with something like the DST commands?

**Comment by tatarize** [comment]
What you said sounded a little ambiguous as to the swf machine. The rig, has it has its own computer. Internally. With a screen and a floppy drive.  If I want to run a design I boot the embroidery machine up, put in a usb drive with the design and press the buttons to load the design. I really do just move the thumbdrive to the machine and put it there and set the settings.

**Comment by tatarize** [comment]
For example internally the U01 format will do:
* STITCH: 0: Number 9
* STITCH: 2525: Number 10  (Jumps some just after this)
* STITCH: 6811: Number 11 (Jumps some just after this)
* STITCH: 7488: Number 12 (Jumps some just after this.)

I take that first command encoded as the number 9 there to mean some kind of init, I take the next control values of 10, 11, 12 as color changes. But, if they should rather be read and written as meaning other things? They could mean color_change and in this case they do, but that initial command thing actually sets the stops.

**Comment by tatarize** [comment]
But the C00, c01-c15 and S0 and S1 commands are written to the file? And you can set the order to get the functionality you want? If you set the sort of first master command to C00 it uses whatever needle it's on. If you set it to C01 it goes to the first needle then anytime it has a C00 that c00 will mean stop? And C07 would mean needle 7 or so?

**Comment by wwderw** [comment]
> But the C00, c01-c15 and S0 and S1 commands are written to the file?

No, color changes are written to the file.

If you were to look at the same DST file in say Wilcom, without any reference of stops (or sequins), it would be nothing but color changes.  I don't know about the inner workings of the file, just how it would visually appear to me in an embroidery program.

How we know when to use what (if needed) would be communicated via the pdf stitch chart.

**Comment by tatarize** [comment]
In DST the color change command is the stop command. It's coded as 0x0000C3. That's the only command possible for that.

In U01, there's a command byte. In the test copy of the file I have. The commands are:
0 = Stitch
1 = Jump
9 = Starting command (Stitch 0)
10,11,12 = Color Changes.
18 = End of document. (last Stitch)

It seems like this might be the same as that.  That this is the binary encoding of that screen.

**Comment by tatarize** [comment]
In most of these cases there's no difference between stop and color change. You enter that into the sequence in a way that makes it stop but if you reload the file, it can't even tell the stop from the color change and ends up with an added color-change. This will certainly be true for .dst and .exp however if it is the case that these needle commands and sequin commands are core to the format in U01 they actually need to be relayed to the software unhindered as these commands would be fundamentally important to understand what that format wanted. Or more or less what it expected.

A 20 color sequence seems to go:
1   1001  0x09   0   0
2793   1010  0x0A   0   0
4706   1011  0x0B   0   0
5518   1100  0x0C   0   0
7292   1101  0x0D   0   0
9183   1110  0x0E   0   0
11013   1111  0x0F   0   0
12546   1001  0x09   0   0
13688   1010  0x0A   0   0
14553   1011  0x0B   0   0
16897   1100  0x0C   0   0
17675   1101  0x0D   0   0
19008   1110  0x0E   0   0
20372   1111  0x0F   0   0
21151   1001  0x09   0   0
22986   1010  0x0A   0   0
24580   1011  0x0B   0   0
25909   1100  0x0C   0   0
26792   1101  0x0D   0   0
28252   1110  0x0E   0   0
29779   11000  0x18   0   0 END

These seem like the needles. While it loses the colors it might have this other sets of information. I might even be able to process S0 and S1 if need be. 

It really looks like 1xxxx is the command sequence for C0? So C00 would be 1000 and C01 is 1001. And this is just writing C01, C02, C03, C04 C05 C06, C07, C01, C02, C03, C04 C05 C06, C07,

**Comment by tatarize** [comment]
This would seem like it would mean that written files should start with C01, then write C00 for all stops and color changes unless it's actually expected to do the do the needle sections. But, that wouldn't be too hard. It would mean encoding an actual stop is start with a C01 command. Then stops are encoded C00 and color changes are implemented by selecting the needle with that color. Unless I'm missing something this wouldn't require some weird fanangling, it would be even more straightforward as to what stop means.

**Comment by tatarize** [comment]
From a pretty deep manual somewhere for something: http://techindex.barudan.net/Acrobat/Manuals/XTInst%20XT_Instruction_Manual_V1_r1(E).pdf

1. Function Codes No. Code Function
0 0 Normal Stitch 
1 JP Jump Stitch
2 L Low Speed
3 LJ Low Speed Jump
4 H High Speed
5 HJ High Speed Jump
6 T1 Top Thread Trimming
7 T2 Bobbin Threading 
19 G1 Group 1 
20 G2 Group 2 
23 SE Sub End 
32 C00 Stop
33 C01 Needle Bar 1 
34 C02 Needle Bar 2 
35 C03 Needle Bar 3
36 C04 Needle Bar 4 
37 C05 Needle Bar 5
38 C06 Needle Bar 6
39 C07 Needle Bar 7
40 C08 Needle Bar 8
41 C09 Needle Bar 9
42 C10 Needle Bar 10
43 C11 Needle Bar 11
44 C12 Needle Bar 12
45 C13 Needle Bar 13
46 C14 Needle Bar 14
47 C15 Needle Bar 15
64 S0 Sequin OFF
65 S1 Sequin ON
67 SJ Sequin Jump
68 CC Chain Stitch
69 CL Loop Stitch
70 PR Presser foot height
71 SPL Normal Embroidery
72 ST1 Taping & Cording Embroidery (R)
73 ST2 Taping & Cording Embroidery (L)
74 SZ1 Zigzag Embroidery (L)
75 SZ2 Zigzag Embroidery (R)
76 SC1 Coiling Embroidery (L)
77 SC2 Coiling Embroidery (R)
78 LN Nipple Movement
79 LZ Zigzag Movement
80 HSP Head Selection Pattern
81 FMP The point of flame moving

**Comment by tatarize** [comment]
BEVT is older but, the point is still the same. The code for stop is C00. If you don't set the initially code to C00 but rather to the correct needle everything seems perfectly reasonable and these commands should likely be very similar to what's given in the manual.

http://barudan.fr/wp-content/uploads/2014/07/BEVT_Instruction_Manual_EN.pdf

It sounds like it has all perfectly reasonable functions. But, setting that bit to C00 at the start makes it work strange.

**Comment by wwderw** [comment]
>But, setting that bit to C00 at the start makes it work strange.

Setting it at the beginning is not typically what does go on.  I only mentioned it for when it does happen, what has to be done at the machine for the operator since it doesn't have that previous color info.  I've only encountered 7 times when I actually had to do it that way.

**Comment by tatarize** [comment]
Seems like Lex shouldn't have to jump through any hoops then. Should just treat C00 as stop and C01-C15 as needles. And always open with the actual first needle if this stuff is being written out.  Any chance you have some U?? files with some fancy commands? Or that shift to needles beyond the 7th needle?  Seems like a little bit of mapping these commands would be helpful, especially given a number of formats follow the same scheme. My guess is they use similar controller stuff and it wouldn't be hard to map it out effectively. But, it sounds like U?? would have even fewer problems and not require any trickery. C00 is stop. C01... is a color change.

**Comment by wwderw** [comment]
>Any chance you have some U?? files with some fancy commands?

I could work up some just really basic designs (squares, run stitches, circles etc) and import sequin command for that and also slow and fast commands.

Slow and fast would be something that I would really like to see if we can get into the U?? files.  I don't know of any other format that has them in the pattern directly to translate to the machine.  I know some machines can do it when directly connected to the software and control it at the software.  But these are actual commands that trigger the machine to go slower and/or to go faster (which means back to normal speed, for me that's 700 spm).  

These functions do not show up visually at the embroidery machine.  I do believe these are hard coded.  As to if they are actually written as "slow" or "fast", that I don't know.

**Comment by lexelby** [comment]
Based on what @wwderw has said repeatedly, I really do have to jump through hoops.  He's saying that when he sets C00, the machine doesn't halt at that point in the design, it halts at the next color change.  That is, C00 says:

> Continue sewing with the currently-selected needle and then stop at the next color change.

Imagine I'm doing some red stitching and then some applique with black stitching:

1. red running stitch
2. black positioning line
3. halt machine
4. black tack-down
5. halt machine
6. black satin

If I just set C00 for the color change between steps 1 and 2, then it will continue sewing in red thread for the positioning line!  I therefore have to break up the positioning line with an artificial color change so that I can first set the color black, and then set C00 for the second half of the positioning line.

**Comment by tatarize** [comment]
Yeah, but he shouldn't set the first color to C00. He should set it to the correct needle then everything works exactly the way you'd expect. C01-c15 select the needle. And C00 is explicitly stop (as it says in all the documentation).

Your example would be written out as:
C01 start.
1 red running stitch.
C2
black positioning line.
C0 (halt machine)
black tack-down
C0 (halt machine)
black satin.

If you set C01 for the initial color change it will be on C01 and nothing else will be weird ever. It'll work just the way you'd expect with C0 halting and C# switching to that particular needle.

**Comment by tatarize** [comment]
The format overtly sets the needle. It's kind of like a pre-color change. Select needle index. If you set this to the function for stop. It goes kinda wonky. But, if you set it to the first needle. You can use that first thread perfectly fine, then switch needles properly and stop properly.

**Comment by lexelby** [comment]
> And C00 is explicitly stop (as it says in all the documentation).

That is not what @wwderw said actually happens:

> [lexelby:] If you set the "0st" box to C01 instead, would it still stop at stitch #411?
> [wwderw:] No. It won't stop until it hits a block that has C00 on it (in this case the next stop would be at stitch 929)

He's now said this several times.  Either there's a communication breakdown or your understanding of the manuals is incorrect, @tatarize.  I saw the same manuals but they just say "C00: Stop"; they don't describe how it actually behaves.

**Comment by tatarize** [comment]
He's right. It won't stop there. If you go from C01 to C01 that does nothing. It won't stop if you go from to C02 either, it'll just change needles and proceed as expected.

**Comment by tatarize** [comment]
He's using the word stop literally. You will change colors to the needle you want and specify by the C# command. It will *only* stop in those cases when it has C00 if it starts with a C# entry for the opening command there.  You don't want it to stop at 411. You'd want it to change to the correct thread and keep stitching. If you wanted it to stop you would start with C01 and do C00 each place you want to stop.

**Comment by tatarize** [comment]
If the first command is C00 it's weird. But this occurs at position 0. Before any stitching happens. You set that to the correct needle. Then C## is go to that needle and C00 is stop. If you set the first command to C00 it puts it in freaky mode. These are needle commands though, they encode for the needle. If the first needle is marked as stop, it goes weird. But, if you set that needle properly, the color_changes are C01-C15 and the stop is C00. --- So when he says it won't stop, he doesn't mean it won't change colors. It will change colors to that needle. If it's the same needle you ignore that command because it's effectively no op.

**Comment by lexelby** [comment]
I'm referencing his picture here, in which he's set C00 for everything:

https://github.com/inkstitch/inkstitch/pull/234#issuecomment-406482615


> He's right. It won't stop there. If you go from C01 to C01 that does nothing. 

The picture doesn't show C01 -> C01.  It shows C00 C00 C00 C00.  If we had set C01 for "0st" as I was asking, then it would be C01 C00 C00 C00.  And despite the "412st" box having C00, he says it won't stop until it gets to 929.  Translation: stop happens at the next color change after the C00.

**Comment by tatarize** [comment]
If you set that 0th command to C00 it's a bit odd.  But if you set it to C01 properly it works fine. In fact I'm pretty he makes that point here:

When you have C00 listed as the very first "color" assignment, the machine uses whatever color that is the active one (the last one used in the previous pattern that was stitched out). The user has to advance to the correct needle when they have something like this. That's what I was talking about when C00 falls at the beginning. That first stop actually isn't until 411.

**Comment by lexelby** [comment]
That's just not what I'm getting from what he's saying.  Am I misinterpreting?  One of us is, surely.

@wwderw In the screenshot you posted (https://github.com/inkstitch/inkstitch/pull/234#issuecomment-406482615), what is the _exact_ behavior that the machine would do if you set it as C01 C00 C00 C00 instead?  At what stitch does the machine stop?  Can you try it out just to be sure?

**Comment by tatarize** [comment]
"Okay, got it. So this really does mean that C00 boils down to:

Continue sewing using the currently-selected needle.
At the next color change down the line, stop before continuing."

This is *only* true for C00 in the 0th position. It starts sewing with the active needle. It shouldn't fall through though unless it's changing to the same needle.

C00 C00 C00 C00: Start with the current needle, stop three times.
C01 C00 C00 C00: Start with needle 1, stop three times.
C01 C01 C01 C01: Start with needle 1, do jack squat different
C01 C02 C03 C04: Start with needle 1, go needle 2 go needle 3 go needle 4.

**Comment by lexelby** [comment]
Unless you have a barudan machine then your guess is as good as mine.  Let's wait for his answer.

**Comment by tatarize** [comment]
> lexelby: What is the purpose of setting C00 for the "0st" box at the top? What are you telling the machine to do?

--

> wwderw: Stop at stitch 411 (for this particular pattern).

That's the meaning of the 2st box not the 0st. Hence his answer. It actually means start with the currently active thread.

--

> The stop has the same meaning here as it does if there was C01 before C00. Stop at the end of this block.
> 
> The only difference is that the user has to make sure if they need to move the machine to the appropriate needle.
> 
> Functionality, it does not change how the stop is handled at the code level from where you had it.

--

> lexelby: If you set the "0st" box to C01 instead, would it still stop at stitch #411?

--

> wwderw  No. It won't stop until it hits a block that has C00 on it (in this case the next stop would be at stitch 929) or til the end of the design.

He thinks you're referring to the second box in the image again. If you changed that to C01 and your active thread started at needle 1, it would stitch right through that bad boy. Stopping at the 3rd box which says C00 aka STOP.

**Comment by lexelby** [comment]
As I said, unless you have a barudan machine, then your guesses are only as good as mine.  You're just guessing.  Let's wait and see what he says.

**Comment by wwderw** [comment]
Sorry it took me awhile.

I did 3 patterns, all with run stitches.

First pattern was single run stitch, 1 color, no "stops"

C01

Second pattern, 2 run stitches, 1 stop to break them up, 1 color in the program, DST file shows 2 colors.

C01, C00

3rd pattern, 4 run stitches, 3 forced (the 4th was end of pattern), 1 color digitized, shows up as 4 colors in DST.

C01, C00, C00, C00

Just going by what I've observed.  Going to try to stay away from any conclusions, I think I just have enough knowledge to be dangerous.

**Comment by lexelby** [comment]
And in the last one, the machine stopped 3 times?

**Comment by wwderw** [comment]
3 forced, 4 total.

**Comment by lexelby** [comment]
The fourth being at the end of the design, right?

**Comment by wwderw** [comment]
Yes.

**Comment by lexelby** [comment]
Excellent.  So C00 really does say "stop at this point, then sew with the same color that was selected".  Wonderful, that's way simpler.  I'm glad we finally nailed this down.  I'll go rip out the incorrect code.

**Comment by tatarize** [comment]
DST can't really decide between stops and colorchanges so any stops would be forced into color changes even when they are properly and natively stops.

**Comment by lexelby** [comment]
@wwderw What do you if you want to sew with black thread, stop the machine, and then when it starts again, immediately sew with red? I ask because the C00 would tell it to continue on with black after.

@tatarize Would STOP followed immediately by COLOR_CHANGE be legit in this case, do you think?

**Comment by wwderw** [comment]
> What do you if you want to sew with black thread, stop the machine, and then when it starts again, immediately sew with red? I ask because the C00 would tell it to continue on with black after.

I never had that instance come about, but I would imagine that I would treat it like I would if C00 was at the beginning of the design.  Just advance it to the needle that has the red on it and then start it back up.

**Comment by wwderw** [comment]
Print PDF returned this:

print error

**Comment by wwderw** [comment]
>Any chance you have some U?? files with some fancy commands?

[Barudan U Files.zip](https://github.com/inkstitch/inkstitch/files/2216453/Barudan.U.Files.zip)

@tatarize, here are some U files with just color changes (up to 15), stop code, slow and fast codes and for sequins.  Most of them are just run stitch objects.  I did have one with a satin object and then run stitches (for the sequins I think).  I did take note of specific stitch counts of where those actions should take place unless it's done by some other means then just straight drop, slow, fast, stop etc (like when the sequin dispenser is active jump codes become drop sequins etc, at least in the DST format).

**Comment by lexelby** [comment]
> Print PDF returned this:

Whoops.  I guess that's what I get for not testing everything before pushing my changes :)

**Comment by lexelby** [comment]
> Though usually people just take the stop to advance the needle themselves. 

This is what I decided to stick with.  As @wwderw intimated, it's pretty rare to want to stop the machine and then start sewing a different color after.

**Comment by wwderw** [comment]
>Whoops. I guess that's what I get for not testing everything before pushing my changes :)

Print PDF seems to be working now.  At least based on the design that I ran through it when I noticed the new build.

Coming together quite nicely.

**Comment by lexelby** [comment]
> Coming together quite nicely.

Seems to be!  Now's the time when we really need to test the heck out of it.  Changing such a deep part of Ink/Stitch (the file writing code) has the potential to cause bugs pretty much anywhere.

BTW, I went ahead and adjusted the way that Print PDF displays stops.  Now, instead of "# stops" for a block, it's just "stop after?" with "yes" or "no".  This is good enough to let us release for now, but if you want something different (a red stop sign or something?) go ahead and open a feature request.

**Comment by wwderw** [comment]
I'm digging the idea of a red stop sign in there somewhere.

I'll see about giving it a good going over the next few days.  It'll take awhile for me to do a comprehensive test as I'll just have a little time here or there.  But I'll see if I can put it through the paces.

**Comment by AkiraNorthstar** [comment]
> Seems to be! Now's the time when we really need to test the heck out of it. Changing such a deep part of Ink/Stitch (the file writing code) has the potential to cause bugs pretty much anywhere.

Is it possible to generate "simple" test files for the supported formats?
So everyone could first try the "own" format without "tinkering" themselves something. Everyone has the same basis for testing. As far as I could read that out in the libembroidery / readme.md that should be possible, right?

**Comment by tatarize** [comment]
Pyembroidery outside of the PyPI version has a test.py and test-fractal.py these are expressly to generate little test files that can be looked at and judged for consistency. They were tested very very extensively. And continuously through the entire process. The test.py also has some test code that basically loads every single file in a particular directory and converts it to every single format pyembroidery writes. These files were then tested repeatedly with various software with special emphasis on testing the file with the software native to the format. So PES was tested with Brother software to make sure it worked. VP3 was tested with Premier 2™ JEF was tested with some Janome software. These were also tested for consistency throughout with Wilcom and Embird. 

In short, that's not where the errors will happen. The errors will happen when people try to load them on their machines. While everything is checked repeatedly with every bit of software I could find and checked and converted large numbers of sample files in all the formats... I don't have an embroidery machine that takes these formats, except for .DST. For this reason I tried to overbuild them and map out everything about the format I could.

But, here's some test files for that stuff.

[steps_and_move.zip](https://github.com/inkstitch/inkstitch/files/2225369/steps_and_move.zip)
[serpent.zip](https://github.com/inkstitch/inkstitch/files/2225370/serpent.zip)
[gosper.zip](https://github.com/inkstitch/inkstitch/files/2225371/gosper.zip)

This should have some of the various examples in the various formats. Including some versions that aren't actually written like .dst with extended headers and truncated pes.  The sierpinski fractal and gosper fractals are single layers. The steps and moves should do stop, color change and trim. This is to make sure it gets the variety.

--

Yes, it seems like a pretty massive and fundamental change, but the change isn't as much for inkstitch as it's mostly changes the backend and uses a different library to save the stuff out. And I can say without any reservations pyembroidery is going to be fundamentally more stable, easier, and more debug-able.

I can stand by that statement because:
1) I tested this stuff very heavily and robustly
2) libembroidery has a good number of fundamental issues. (only .dst seems to work well); it's a low bar.

Given 2, I would error on the side of recklessness. Especially given that any format error could be much more easily tracked down and fixed.

**Comment by lexelby** [comment]
> Is it possible to generate "simple" test files for the supported formats?

Maybe this would be a good use for the File -> Save Copy As  Inkstitch multi-format ZIP file feature?

**Comment by lexelby** [comment]
> And I can say without any reservations pyembroidery is going to be fundamentally more stable, easier, and more debug-able.

Most definitely.  It's also easier to code for, and the Ink/Stitch code that interfaces with it is much simpler and cleaner.


The likely spots that errors could have crept in are in the trim and stop handling code.  I got rid of a fair bit of code that worked with libembroidery's eccentricities.

In short, run it on your existing designs, test out the printout, etc.  If no one finds any bugs in a couple of days, I'll merge and release it.

**Comment by lexelby** [comment]
It looks fine to me, so I'm just gonna ship it.  If we have problems, we'll just make a bugfix release :)

**Pull request merged**
