### PR TITLE
Lexelby/fix parse style

### PR DESCRIPTION
**Pull request by kaalleen**

### CODE REVIEW

**Comment by kaalleen** [comment]
Ok, it's a pull request now. I merged master into it and added a little bit of code - just in case we handle an svg with single style attributes set separately.

Sigh, now the linux build is always failing.

**Comment by kaalleen** [comment]
Ops, I forgot to re-add the default value. Sorry for that. Fixed.

**Comment by kaalleen** [comment]
Fixes #632

**Comment by lexelby** [comment]
Thanks!

**Comment by lexelby** [comment]
Whooops, build is failing because we need `apt-get update` before the first `apt-get install` line

**Comment by kaalleen** [comment]
Thanks for having a look into it. I created a pull request with the update. Hopefully it will work.

**Pull request merged**
