### PR TITLE
lettering features

### PR DESCRIPTION
**Pull request by lexelby**
At long last, I've had some more time to work on Lettering!  So far, this branch adds a trim checkbox that will add trim commands after each letter.  You can still set it to alternate the direction of stitching for each row of text to minimize needle travel.

@wwderw	aside from center-out stitching (which I'm already hoping to work on soon), any other must-have features for lettering?

--------------

This PR adds:

* trims
* properly corrects for viewbox
* font selector
* a medium size font
  * this is just a scaled-up version of my small font
  * it probably still needs adjustments for push and pull compensation, and of course kerning
* localization support for font names and descriptions in font.json
  * for fonts packaged with Ink/Stitch, we can translate them on CrowdIn
  * for fonts shipped separately, you can add multiple description attributes in font.json, like "description_en_US" and "description_de_DE", etc.  This works for "name" and "description".
* presets support (like in Params)
* support for scaling text up and down, with limits set by a font's font.json
* adds a scale bar to the simulator to make it easier to see how big the text is

### CODE REVIEW

**Comment by jameskolme** [comment]
Trims are one trim too short and then there are special letters that need some more trimming, öä and ÖÄ needs some more trims. 
lettering

**Comment by lexelby** [comment]
@jameskolme Two fixes:

* trim after the last letter too
* hopefully add the trims for umlauts

The fix for umlauts is kind of gross: I just lowered the distance that it changes from a jump stitch to a trim.  We may need to tune that or to get more clever about it, we'll have to see.

**Comment by lexelby** [comment]
@wwderw Great ideas!  For monograms, I've seen monogram alphabets for sale that are actually a collection of three alphabets, one for left, one for middle, and one for right.  Is that what you have in mind?

I'm thinking we could have a separate kind of font for monogramming, and the lettering extension would put together the monogram from the three lettering sets.  For example, if the user enters the initials "ABC", it would take the A from the first font, the B from the second, and the C from the third.

**Comment by wwderw** [comment]
> @wwderw Great ideas! For monograms, I've seen monogram alphabets for sale that are actually a collection of three alphabets, one for left, one for middle, and one for right. Is that what you have in mind?

I was actually thinking, and this may not lead to good code so forgive me, but sticking with the 3 boxes methodology, I would have that middle box hardcoded to scale whatever is entered there some % increase over what is in the left and right boxes.

I'm thinking that by doing it that way, we wouldn't have to have a separate digitized font for monogramming.

Thoughts?

**Comment by lexelby** [comment]
@wwderw Sure, that'd get the job done.  I'll have to think about how to implement it.  For one thing, the current lettering extension doesn't have an option for scaling a font at all.

With alphabets in DST format, of course, we wouldn't want to scale much if at all.  But since our fonts are vector-based, it actually does make sense to scale a font, to a certain degree.  I'm thinking I'll add metadata in the font that tells Ink/Stitch how much it's willing to be scaled.

**Comment by jameskolme** [comment]
> The fix for umlauts is kind of gross: I just lowered the distance that it changes from a jump stitch to a trim. We may need to let the user tune that or to get more clever about it, we'll have to see.

This is causing unwanted trims, not terrible amounts, but sometimes thread gets trimmed after running stitch. Should trim distance be one metadata as well and scale when font is scaled. This is more issue with fonts that are made using wide satin, jump between running stitch and satin.

**Comment by wwderw** [comment]
Make sure it's within the software and not within the machine.  Some of the newer machines will override a jump stitch (or force a trim) if certain conditions are met, regardless of what is in the file.

**Comment by lexelby** [comment]
@kaalleen that last commit might especially interest you.  It adds a scale bar to the simulator so that you can get an idea for the zoom level and the design size.  You can even use it to measure things! :)

I added it because otherwise, changes in the font scale may be confusing, since it may not be obvious to the user that the whole text size got bigger or smaller.

**Comment by jameskolme** [comment]
I´m assuming font.json file is basic settings and description file for every font. So I try to modify to suit my fonts, but when done minimal change, medium size error is generated:

```
Traceback (most recent call last):

  File "inkstitch.py", line 62, in <module>

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\lettering.py", line 330, in effect

  File "lib\extensions\lettering.py", line 48, in __init__

  File "lib\extensions\lettering.py", line 126, in update_font_list

  File "lib\lettering\font.py", line 70, in __init__

  File "lib\lettering\font.py", line 80, in _load_metadata

  File "json\__init__.py", line 291, in load

  File "json\__init__.py", line 339, in loads

  File "json\decoder.py", line 364, in decode

  File "json\decoder.py", line 382, in raw_decode

ValueError: No JSON object could be decoded
```
Small font .json:

```
{
  "name": "Ink/Stitch Small Font",
  "description": "A font suited for small characters.  The capital em is 0.2 inches wide at 100% scale.  Can be scaled up to 300%.",
  "leading": 8,
  "letter_spacing": 1.5,
  "word_spacing": 4.5,
  "auto_satin": true,
  "default_glyph": "�",
  "min_scale": 1.0,
  "max_scale": 3.0,
  "kerning_pairs": {
    "wo": -0.3
  }
}
```
I Try to make .json for tt_masters font, but not such luck, only changed text fields so far. 
```
{
  "name": "TT Masters",
  "description": "A font suited for heavy use :) ",
  "leading": 8,
  "letter_spacing": 1.5,
  "word_spacing": 4.5,
  "auto_satin": true,
  "default_glyph": "�",
  "kerning_pairs": {
    "wo": -0.3
  }
}
```
If tt_masters font is placed on font folder and separate tt_masters folder, inkstitch uses tt_masters font everytime. font.json file must be same on both fonts because error will happen if anything is changed. Don´t understand what is expected or changed that way, but file is not valid anymore.

**Comment by kaalleen** [comment]
> I added it because otherwise, changes in the font scale may be confusing, since it may not be obvious to the user that the whole design size in the simulator got bigger or smaller.

Oh nice! I thought about this issue just the other day ;) I do like your idea!

**Comment by lexelby** [comment]
> I´m assuming font.json file is basic settings and description file for every font. So I try to modify to suit my fonts, but when done minimal change, medium size error is generated:

That's strange, because your `font.json` looks fine to me.  You're right that `font.json` has settings and information about the font, and your modifications should be right.

Is it possible that the file is named wrong or there's extra garbage at the end of the file?

This is definitely a rough edge.  A nice error message would be far preferable instead of that big traceback.

**Comment by jameskolme** [comment]
Wow found solution, I have now few fonts. Font.json file must be saved using ANSI encoding, but notepad likes UTF-8 more.

**Comment by lexelby** [comment]
Cool! utf-8 should be okay, but you had some left/right quotation marks in there instead of straight quotation marks? That would mess things up.

**Comment by jameskolme** [comment]
Actually no, if I open .json on notepad and click save without any changes, file stops working. But opening same file again and using save as with ANSI selected, file starts to work again. 

I have now four fonts and not sure what to type :)

**Comment by jameskolme** [comment]
Can you give example of multiple kerning pairs? My guess work is not working, so no lottery ticket this week. 

"kerning_pairs": {
    "wo": -0.3
  }

**Comment by lexelby** [comment]
Sure:

```

"kerning_pairs": {
"wo": -0.3,
"gu": -0.4,
"io": -0.25
}
``` 

My hope is to make font designing a little easier by adding an extension that helps you set the kerning pairs and all of the other settings.  There's a lot of work to be done for lettering :)

**Comment by lexelby** [comment]
The number is a number of millimeters of space to _add_ between that pair of letters.  In almost all cases, you want to contract certain pairs together.

**Comment by jameskolme** [comment]
Something goes wrong when I do upload, tried to  upload masters and directors font, but it seems files get overwritten. Really can´t figure out how to do folder for separate files.

**Comment by lexelby** [comment]
Okay, I think I've done enough damage here.  Better to merge this now before this PR gets even bigger :)

Here's what this adds:

* trims
* properly corrects for viewbox
* font selector
* a medium size font
  * this is just a scaled-up version of my small font
  * it probably still needs adjustments for push and pull compensation, and of course kerning
* localization support for font names and descriptions in font.json
  * for fonts packaged with Ink/Stitch, we can translate them on CrowdIn
  * for fonts shipped separately, you can add multiple description attributes in font.json, like "description_en_US" and "description_de_DE", etc.  This works for "name" and "description".
* presets support (like in Params)
* support for scaling text up and down, with limits set by a font's font.json
* adds a scale bar to the simulator to make it easier to see how big the text is

**Pull request merged**
