### PR TITLE
Add extension: Lettering along path

### PR DESCRIPTION
**Pull request by kaalleen**
I see a lot of people having a hard time to bend their Ink/Stitch lettering text along a path.

Using the path effect "bend path" works, but it stretches the letters, so that it is difficult to achieve good results. Means users need to rotate and position each glyph by hand. Let's give them a new extension to make it a little bit easier for them. The extension can also stretch the text spacings, so that it will expand over the entire path (if desired).

### CODE REVIEW

**Comment by lexelby** [comment]
You're a wizard, I swear.

**Review by lexelby — APPROVED** [review]

**Comment by danielkschneider** [comment]
Hello. There is a bug aligning letters that have been reduced along a path without ticking the "stretch" (???) box. First line with font at 50% is OK since I ticked the box, second will be bad, third line is OK since a left the font at 100%.

2023-04-27 12_37_11-_Nouveau document 8 - Inkscape

SVG file with second line ready to "go".
align-lettering-to-path-bug

Ink/stitch version: daniels-build (windows)

**Comment by kaalleen** [comment]
Aiai, thanks for pointing that out to me. This is a tricky one.

I did not expect someone to scale the lettering group as a whole. We have carefully designed fonts which can be scaled through the lettering module :D

**Comment by danielkschneider** [comment]
> Aiai, thanks for pointing that out to me. This is a tricky one.
> 
> I did not expect someone to scale the lettering group as a whole. We have carefully designed fonts which can be scaled through the lettering module :D

Hello, you might expect that people do this, but I did not. I only used scaling through the lettering module. Anyhow, I will test the new version :)

**Comment by tyrosinase** [comment]
> I did not expect someone to scale the lettering group as a whole.

FWIW I do this *all* the time, since it's much faster on my apparently-inadequate machine than re-opening Lettering.

**Comment by kaalleen** [comment]
Oh, I realized that later on. If you rescale the font manually I suppose there still will be a glitch. Transformations can be a pain. But if you don't I think it should work now.

A good version to test and with all the recent bug fixes included: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

**Comment by tyrosinase** [comment]
Yeah, I wouldn't rescale it during a fit-to-path, probably.

... probably. :laughing:

**Pull request merged**
