### PR TITLE
add E stitch for satin columns

### PR DESCRIPTION
**Pull request by lexelby**
Click a checkbox to switch a satin column from zig-zags to E stitch.  Only the top stitching is affected, not the underlay.  I imagine one would probably not use E stitch with underlay :)

If the points are facing the wrong way, just use the "flip satin column rails" extension.

E stitch is only implemented for satin columns, not for simple satin.  Mathematically, it would be fairly easy to do it for simple satin too, but that comes with a number of complications:

1. Which side should the points be on?
2. Going around corners, it's going to be _really_ terrible.

I'd much rather just implement #49 if folks want an easy way to make E stitch (or any satin column).

### CODE REVIEW

**Comment by kaalleen** [comment]
Works on my end :)

**Comment by lexelby** [comment]
@wwderw I'd love your feedback on this one when you have a chance, since you seemed interested in E stitch.  No rush of course.

**Comment by wwderw** [comment]
E Stitch worked great on my end.  Behaves exactly like I would like to see and I really appreciate the flip part of the extension, that way I won't have to re-digitize if I need it to do the e-stitch on the opposite side.

I do tend to use the SatinColums more (it reminds me of Input A with a little bit of hand embroidery thrown in (with doing the runs for stitch angles) and that's my preferred tool).

The only thing, that for me, simple satin would have an advantage in (and I'm still trying to learn things in Inkscape, as I'm an Ai guy through and through) and if those columns can handle offsets.  That's where a simple satin could really come in handy (if it can handle the corners).  X % on one side and Y% on the other side of center line etc.

All in all, E-stitch looks good.  This will be good for children's applique work.  Awesome!

**Comment by wwderw** [comment]
> Hmmm. I could probably handle percentages left and right of the center line, but to me it seems like you could just do this by expanding or contracting the entire satin column object. Maybe I'm missing something though.

This is if we were going to incorporate a simple satin object, not really for the satin column.

It would be for quick offset percentages (especially useful for applique where you want more like a 90/10 split (typically for satin cover stitches it's 70/30, but for an e-stitch it's a lot more, or at least I like to do a lot more)).

It's really more for a quick down and dirty way of doing it.  If we aren't going to implement it on a simple satin (or the new iteration of what was simple satin (I think I read where you are working on changing things up on that)), then no need to worry about this.  How corners are handled though (as you mentioned above) would be a big determining factor.

**Pull request merged**
