### PR TITLE
Add max stitch length to satin zigzag underlay

### LINKED ISSUE #1353: Satin stitches: maximum stitch length for underlay
Hi 
I have been using  an hidden gem : the  "maximum stitch length" on column satin. It works very well, except that it has no action on the underlay.  Therefore the underlay is very slow to embroider because of the length of the stitches. My feeling  is that stitches of the underlay should also be split. 
However, it is already a great feature to further enlarge lettering, thanks.

_Originally posted by @claudinepeyrat06 in https://github.com/inkstitch/inkstitch/issues/1254#issuecomment-924758272_

### PR DESCRIPTION
**Pull request by kaalleen**
Fixes #1353

### CODE REVIEW

**Comment by claudinepeyrat06** [comment]
Kaaleen, you are the best !!!

**Comment by kaalleen** [comment]
Thanks :D Do you have a chance to test if it is working as expected?
Btw. did the latest version of letters to font work out for you?

**Comment by claudinepeyrat06** [comment]
Yes it works as expected, thanks 
I still have to test the latest version of letters to font. I will report back as soon as possible.

**Comment by kaalleen** [comment]
Great, thank you for your help.

**Pull request merged**
