### PR TITLE
Font Terminus TTF

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by bkmgit** [comment]
The font needs resizing.  Are there guidelines for sizes to use? For example ranges for small, medium, large and extra large fonts?  Should fonts by default have underlay?

**Comment by bkmgit** [comment]
Also, can one use a name such as `Ink/Stitch Terminus TTF` indicating origin of the font, but that it is a derivative for use with Ink/Stitch? This can be helpful for other fonts derived from computer fonts.

**Comment by kaalleen** [comment]
First of all, thank you for adding a font to Ink/Stitch.

> Also, can one use a name such as Ink/Stitch Terminus TTF indicating origin of the font, but that it is a derivative for use with Ink/Stitch? This can be helpful for other fonts derived from computer fonts.

The license states, that derivative works have to use an other font name. Not sure if prepending Ink/Stitch is enough of a difference? What do you think @lexelby ?

> The font needs resizing. Are there guidelines for sizes to use? For example ranges for small, medium, large and extra large fonts? Should fonts by default have underlay?

If you need an underlay or not depends on the font itself. If it is not very, very small I'd say it's recommended to use underlay.

For the sizes I suppose it is actually best pratice to embroider the font with various sizes and see what still looks good or when it does need a change in the params.

**Comment by lexelby** [comment]
Hmm, that's tough.  I'd say let's be on the safe side and choose a new name that doesn't have "Terminus" in it at all, that way we're sure we're good.

**Comment by bkmgit** [comment]
Thanks. Will check. Maybe something similar is needed for [Grand Hotel small](https://github.com/inkstitch/inkstitch/tree/main/fonts/grandhotel_small) and [Grand Hotel Marif](https://github.com/inkstitch/inkstitch/tree/main/fonts/grand_hotel_marif), [Grand Hotel font](https://fonts.google.com/specimen/Grand+Hotel) is also OFL

**Comment by lexelby** [comment]
Oh yes, emailing for permission is also a great option!

Not all fonts that use OFL use a "reserved font name".  We did have a couple previously though and had to rename some of our fonts.

**Comment by rlevine** [comment]
Yep, Grand Hotel has a reserved font name.

```GrandHotel-Regular.ttf: Copyright (c) 2012 by Brian J. Bonislawsky DBA Astigmatic (AOETI) (astigma@astigmatic.com), with Reserved Font Name "Grand Hotel"```

Just discovered that Google collected all attributions for their fonts in one place: https://fonts.google.com/attribution

**Comment by bkmgit** [comment]
Response from Dimitar to:
>> Would it be ok to use the name Ink/Stitch Terminus TTF?

>Any derivative name containing "Terminus" is fine.
>If you are distributing OFL.TXT, insert your names and the reserved name you have chosen in the header section.
>For generation only, without any changes in the font itself, it can be something like this:

>"Embroidery fonts for Ink/Stitch generated <year> by <name>
>with Reserved Font Name <new name>."

**Comment by rlevine** [comment]
Cool! I wouldn’t think you need “TTF” in the name. True Type is a specific packaging and hinting format. Terminus TTF did not change the letterforms in any substantive way from the original. There isn’t any of the packaging or protocol value from the TTF version that survives the translation into an embroidery font. I’d suggest just plain “Ink/Stitch Terminus” (but that is just my opinion!)

**Comment by lexelby** [comment]
Great, Ink/Stitch Terminus it is!

And we need to check on grand hotel to see if we got permission... @kaalleen do you remember if we got permission to use the name "grand hotel"?

**Comment by Augusa** [comment]
The name of Grand Hôtel is Grand Hôtel Marif and Grand Hôtel Small. Isn't it enough? Several other fonts have a name with few difference with the original name. We were told it was correct.

**Comment by lexelby** [comment]
I'm sorry -- I don't know the history here, but I do know what the license says.  The Grand Hotel fonts' LICENSE files say that the original font is licensed under the OFL "with reserved name 'Grand Hotel'".  The OFL defines the "reserved name" concept: we can't name our version "Grand Hotel". I think that also means we can't just add a word or name -- we have to name it something entirely different.

The only way we can keep the Grand Hotel ones named as they are would be if we contacted the author and asked for permission.  Maybe that was already done?

If not, I'm afraid we must rename them.

**Comment by tyrosinase** [comment]
Why font names are weirdly restricted: in the US, typefaces are mostly uncopyrightable, so the name trademark is the only thing that provides any real IP protection.

**Comment by bkmgit** [comment]
Font is made from [Terminus TTF](https://files.ax86.net/terminus-ttf/) and @tblue has also agreed to `Ink/Stitch Terminus TTF` so think this is a better choice.

**Comment by lexelby** [comment]
Oh great, that's perfect!

**Comment by lexelby** [comment]
I finally had a chance to actually look at this font and... I'm not sure we should actually be doing this.

The letter shapes look pretty weird.  The author of Terminus TTF says that the vector outlines were generated automatically using potrace.  They recommend only using font sizes that will use the included bitmap glyphs to avoid using the vector letters, because the vector letters "are somewhat ugly".  I'm sorry to say, I don't disagree.  [https://files.ax86.net/terminus-ttf/#fontsizes](https://files.ax86.net/terminus-ttf/#fontsizes).  Of course, Ink/Stitch fonts are vector-based, so we _are_ using the potrace-generated vector outlines.

**Comment by bkmgit** [comment]
Can edit them by hand.  Would need to compare with bitmap glyphs and adjust size but would not want to make significant style changes.  At present quite large and need to update "t".  Have a use case for them, but it is not necessary to have them distributed with Ink/Stitch.

**Comment by Tblue** [comment]
Am 01.04.23 um 05:08 schrieb Lex Neva:

> The letter shapes look pretty weird. The author of Terminus TTF says 
> that the vector outlines were generated automatically using potrace. 
> They recommend only using font sizes that will use the included bitmap 
> glyphs to avoid using the vector letters, because the vector letters 
> "are somewhat ugly". I'm sorry to say, I don't disagree. 
> https://files.ax86.net/terminus-ttf/#fontsizes. Of course, Ink/Stitch 
> fonts are vector-based, so we /are/ using the potrace-generated vector 
> outlines.
>
Author/maintainer of Terminus TTF here. Yes, the outlines are pretty 
ugly. Give me a few days and I will see if they get better if I scale 
the bitmaps up before tracing them.

**Comment by lexelby** [comment]
Thanks, @Tblue!

There's an interesting opportunity here to make a "bitmap" embroidery font, kind of like how I did the pixels for the Ink/Stitch QR code patch: https://github.com/inkstitch/inkstitch/blob/main/images/examples/InkStitch%20Logo%20QR%20Code%20Patch.svg

I generated that with a script.  Not sure if I still have it kicking around...

**Comment by Tblue** [comment]
All right, magnifying the bitmaps before tracing them did improve the outlines, I would say (left is old):

screenshot_20230407-053311-803

Please have a closer look at the TTF file for the "Normal" variant: [TerminusTTF-4.49.1.ttf.zip](https://github.com/inkstitch/inkstitch/files/11175867/TerminusTTF-4.49.1.ttf.zip)

I'm tempted to release this as the next Terminus TTF version.

**Comment by Tblue** [comment]
I hope to have something ready by the coming weekend.

**Comment by bkmgit** [comment]
Thanks. Once done, can recreate the file for Ink/Stitch Terminus TTF

**Comment by Tblue** [comment]
Sorry, it might take me a bit longer; life is keeping me busy.

**Comment by Tblue** [comment]
The new Terminus TTF version has been released: https://www.ax86.net/2023/04/28/terminus-ttf-4493-released/

**Comment by lexelby** [comment]
@bkmgit Do you still want to finish this?

**Pull request closed without merging**
