### PR TITLE
update font tools

### PR DESCRIPTION
**Pull request by kaalleen**
* Fix a bug in custom font directory when the inkstitch config folder hasn't been created yet
* Fix a bug in remove kerning when there is no kerning in the given font
* Update generate json to improve for fonts without kerning information

### CODE REVIEW

**Review by lexelby — APPROVED** [review]

**Comment by lexelby** [comment]
Wait... Why do we even have an error message at all when they have multiple commands if a given type attached to one object?  Heck, who cares if they put a forest of 100 trims on it they want, makes no difference to me.  Why did I make that crash Ink/Stitch?  I wonder what I was thinking??

I think we can just ignore this case.  Can you think of a reason why multiple commands if one type is a problem?

**Comment by kaalleen** [comment]
> I think we can just ignore this case. Can you think of a reason why multiple commands of one type is a problem?

I think you are right. We just need to pick the first one.

**Comment by lexelby** [comment]
Oh, I realized what I was thinking: if they have two "fill stitch end position" commands, Ink/Stitch won't know which position to use.  That night be especially confusing if one is set to invisible.

I still think the better thing to do is just pick the first one though.  We can have a warning in Troubleshoot for multiple commands, if anyone has any trouble with this.

**Comment by kaalleen** [comment]
> We can have a warning in Troubleshoot for multiple commands, if anyone has any trouble with this.

Yes... we could... :D I actually feel a bit lazy about it, because we would need to add the warning on element level.
Maybe we can add it later and just ignore the additional commands for now?

**Comment by lexelby** [comment]
Yes, I think that's a good strategy.

**Pull request merged**
