### PR TITLE
Element selection - avoid empty patches

### LINKED ISSUE #1199: stitch_plan: IndexError: list index out of range
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/stitch_plan_preview.py", line 27, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

### PR DESCRIPTION
**Pull request by kaalleen**
Fixes #1199 #1226

### CODE REVIEW

**Comment by kaalleen** [comment]
@lexelby What do you think about this branch?

**Comment by lexelby** [comment]
Honestly... I feel uncomfortable about these changes.  It seems like we're jumping through a lot of hoops to ensure that we don't accidentally return an empty stitch plan.  I wonder if it might be better to just make it so that we can handle an empty stitch plan?

I tried making patches_to_stitch_plan return an empty `StitchPlan` object, and I did see a crash in a couple cases.  If you try to fetch the `bounding_box` of an empty stitch plan, you get a `min arg is an empty sequence` exception.  We could just handle this case specially and return a bounding box of size 0.

Are there other problems that result from an empty stitch plan that I'm not aware of?

I really just want to see if we can avoid having to do things like constructing an artificial shape in `paths()`, or returning an error message and exiting in `patches_to_stitch_plan()`.  Maybe instead, we can just filter out the small paths in `Fill.paths()`, and if there are no paths left, return an empty patch list in `to_patches()`, and find a way to handle the resulting empty stitch plan.

**Comment by lexelby** [comment]
In fact, maybe we should avoid filtering small paths in `Fill.paths()` entirely.  I'm concerned that an area of 3 is an arbitrary threshold.  What if the fill stitch row spacing is bigger, like 2mm?  A much bigger fill shape may still fall between rows, confusing the auto-fill algorithm.

Maybe we can make the auto-fill algorithm detect this kind of problem and handle it gracefully.  Can we just have it return an empty stitch list in this case?  Will that cause problems later on too?

**Comment by kaalleen** [comment]
We once decided to handle small fills in that way to make them valid. The way we did it (same amount of loops) did not fully work. We could of course just return an empty stitch path if it is too small. We would still need to filter out small shapes, in case there are subpaths (such as holes) which will be causing errors later on. I believe it is worth the extra loop.

And I also would like for people to clean up their document if they have small fills. So they should be visible in the stitch out :D

The empty stitch plan was a result of only checking if the object has a get_path method. Which also seems to bethe case with images and text objects. Additionally empty d-path objects are difficult to filter out at an early stage, because we have to check for the path first. That's why also the stitch plan itself needs to reeturn an error message if it is empty.

> I'm concerned that an area of 3 is an arbitrary threshold. What if the fill stitch row spacing is bigger, like 2mm? A much bigger fill shape may still fall between rows, confusing the auto-fill algorithm.

It will still work, because the fill stitch has a fallback to a running stitch outline if it isn't able to render it.

**Pull request closed without merging**
