### PR TITLE
Extend Satin Rungs

### LINKED ISSUE #1120: Random error : "Satin column: A rung doesn't intersect both rails."
When the rung isn't sticking out of the rails but they're just sitting on it, inkstitch doesn't seem to like it. It detects this in random error. 
Can we do something? I am bored because the French team which has just added a lot of new fonts did not overflow the rungs enough and we have this kind of error randomly. They'll go crazy if they have to correct every rail of every letter.

You will find a file which allows to highlight the error and a video which shows the behavior with me (watch the video first) :

[rungOnRail.zip](https://github.com/inkstitch/inkstitch/files/6252137/rungOnRail.zip)

### PR DESCRIPTION
**Pull request by kaalleen**
Fixes #1120

Follows the idea of @lexelby to extend the rungs a little.

### CODE REVIEW

**Comment by lexelby** [comment]
I know it was my idea, but now that I've seen it, I'm not so sure.  What if a rung is already long, and expanding it is enough to make it intersect somewhere else?  Then the user will get the error "a rung intersects a rail more than once" which will be wrong and very confusing.

**Comment by lexelby** [comment]
There are two reasons we need rungs to intersect rails.  One is so that we know where the stitches should go.  The other is do that we know which of the paths are rails and which are rungs.  

As long as we have enough information to know which paths are rails, we can be forgiving about one or two rungs that don't intersect both rails.  So we can make the validate function more lenient.

How about this: if a rung does intersect a rail, then we use the intersection point.  If not, then we use the nearest point on the rail.  I think there's a function in Shapely, `nearest_points()`.

**Comment by kaalleen** [comment]
Exactly what I had in mind. I actually started out with the nearest_points idea, but it turned out to be more complicated to implement, so I was hoping this would be enough :D

But I agree with you on the too long issue. Maybe we need to check first if it intersects or not, but this is then going to be more expensive on execution time. Same goes for nearest points while this is more secure to succeed.

**Comment by kaalleen** [comment]
@lexelby what do you think of it now?

I now use nearest_points but also need to extend the rungs afterwards a little (to ensure an intersection). This will in some rare cases cause a multiple crossing while it actually is crossing too less. It will only perform this action when the rung doesn't intersect both rungs natively. So it really has to be a bad coincidence if this happens.

I don't know if it will be necessary to put out a warning about programatically altered rungs through the troubleshoot extension?

**Comment by lexelby** [comment]
Hmmmm... Maybe we can do the `nearest_points()` stuff in `_cut_rail()` instead?  Then we don't have to worry about making sure the rung intersects.

We would also have to change `validation_errors()` to be lenient if only a few rungs don't intersect both rails.  That seems reasonable to me.  `rail_indices()` is already able to handle that situation, I think.

**Comment by kaalleen** [comment]
I don't know how to implement it best in _cut_rails.  ... could you have a look at it?

**Comment by LaureFR38** [comment]
@lexelby 
Shouldn't we limit the length of the rung to be extended? I find it strange in this example that it works: 
image

Could we extend the rail to the maximum thickness of the width of the path? In fact the problem arises when the user uses the magnetic tool and places the node on the rail (besides I do not understand that he does not detect this as a crossing) so the node is in the thickness of the path . What do you think ?
And if he places the node manually and it's not quite on the rail, he thinks it's good because he doesn't see any white space because the knot is in the color of the thickness of the path :
image
even when zooming out we see the white space ... I think that we should not therefore correct the big user errors :
image
You are going to tell me that if he changes the thickness of the line in the middle of his work, the behavior of inkstitch will not be the same and there may be errors. Too bad for him, he just has to be careful what he does. In addition, it will see for itself the white spaces and correct. Basically what we were trying to correct were the node placed with the magnetic tool, so even if it changes the thickness of the line it should still work.

**Comment by LaureFR38** [comment]
Result of my test for this version:
image

**Comment by kaalleen** [comment]
> We would also have to change validation_errors() to be lenient if only a few rungs don't intersect both rails. That seems reasonable to me. rail_indices() is already able to handle that situation, I think.

Ok, I removed the error messages... Actually, it seems like it is handling all the situations well.
Haven't tested it enough, but looks good so far.

@LaureFR38 this now should not cause the multiple crossing error on your example. But I still think that we should avoid to throw error messages on rungs which are not crossing at all. This is maily for performance reasons. Any additional checking for stroke-width and distances of points would cause a loss of time, which just would only be used to restrict users and give error messages that could be avoided. I think the mass of error messages is something which makes it hard for people to start out with Ink/Stitch. So why not allow them to make a bad rung.

**Comment by lexelby** [comment]
I just pushed my version with the nearest_points stuff in _cut_rails().  Let me know what you think.  I force-pushed because I rewrote a couple of the earlier commits, but I saved yours in `kaalleen/prolong-rungs-backup` just in case.

**Comment by lexelby** [comment]
Oops, nope, that doesn't work.  I need to think about this a bit.

**Comment by lexelby** [comment]
I just pushed two commits.  I added a few things:

* scale by only 1.01 to make the "rung crosses two rails" error less likely
  * We actually could probably do 1.001 or even less.  It really doesn't take much.  Floating point numbers are accurate to a level way smaller than that.  
* Switch TooManyIntersections back to an error.  We can't really make a good guess what the user meant if a rung intersects a rail twice.  Which one would we use?
* Added DanglingRungsError, if more than half of the rungs don't intersect both rails.  At some point, if too many rungs don't intersect, Ink/Stitch won't actually be able to tell which of the subpaths are the rails (in `rail_indices`).  I'm hoping that half is a good cut-off point.

I was wrong about doing nearest_points in _cut_rails.  I forgot that we'd have a hard time figuring out which of the sections the rail is supposed to intersect.

**Comment by kaalleen** [comment]
Thanks for working on this branch.

I think everything is good, except for the last point. It really does a suprisingly good job, even on rungs that are far away from the rest of the satin column. Not that it is desirable to have the rungs floating in space, but if I test it on rungs where I snap them to the rails I am constantly gettings this error ... now back to the font which was causing the issue, we are right back at where we started.

I think, if the users find their outcoming satin rung strange, they will check the rungs themselves. Why not leave it to the user to decide, if the rung is totally wrong in place and is causing a bad result. Additionally they will be warned by the troubleshoot extension.

**Comment by kaalleen** [comment]
I just removed the dangling error again.
Sorry, if I am going to fast on it. I just thought we can undo the commit if you don't like it. But try it first :D

Look at these wild rungs. None is is place, really. You can break it, of course, but then they can still run troubleshoot.

wild_rungs

I am mostly worried about the snapped rungs if we leave the error in.

**Comment by lexelby** [comment]
LOL, love that satin.  I'm with you on this.  I was a bit nervous about putting in the DanglingRungsError, to be honest.  I wondered if the font might still run into that error.

If it works, great!  And you're right, if something comes out wrong, they'll run troubleshoot and see it immediately.

No need to apologize.  Go go go, don't wait for me.  I can always put things back in if I feel so inclined. :)

**Comment by kaalleen** [comment]
Ok then :) Let's merge it as is.

**Pull request merged**
