### PR TITLE
new way betterer satin algo

### PR DESCRIPTION
**Pull request by lexelby**
3 years ago, I merged #607, "new way better satin algo".  Spoiler alert: it wasn't way better.

Since then, sometimes satins are way too sparse around sharp corners. #1799 was the last straw.  Here's an example:

image

The stitches are spaced too far apart on the outside of the corner.  That's gonna look like absolute garbage.  Now that we have the short stitches option, we can properly follow the stitch spacing on the outside of a corner without worrying about making the inside of the corner too dense.

This PR is yet another rewrite of the satin algorithm that uses the right stitch spacing on the outsides of corners.  Here's how that looks:

image

I also had to deal with the "V" case, rails coming together or spreading apart screws up the density.  This time, I have the simplest algorithm yet, and it seems to work pretty well!  And the best part: this algorithm is _tons_ faster.  I also got rid of the ancient `SatinColumn.walk()` method -- turns out that calling `interpolate()` a bunch on a LineString is actually quite fast.

For testing, I used the same test SVG from last time, courtesy of @jameskolme:

testi satin diff

Also this new one:

satin_density 2

Please test the hell out of this on a bunch of different satins!

### CODE REVIEW

**Comment by kaalleen** [comment]
Works beautifully :)

Not related to this branch, but I am wondering if we either should remove the maximum stitch length value from e-stitch params or add the split stitch functionality to e-stitch as well?

**Review by kaalleen — APPROVED** [review]

**Comment by lexelby** [comment]
Seems like I might've killed randomization for E-stitch? #2208

**Comment by kaalleen** [comment]
No, it's working. The maximum stitch length doesn't work though, but was never working for e-stitch. So this isn't a problem of your branch. I think we should either make it work or remove this param setting for e-stitch.

**Comment by kaalleen** [comment]
Is this ready to be merged? :D

**Comment by lexelby** [comment]
Sure!

**Pull request merged**
