### PR TITLE
Claudine/update fonts

### PR DESCRIPTION
**Pull request by claudinepeyrat06**
Add new fonts : Abril, Emilio Simple
Rename Grand Hotel to Auberge for licence compliance
Plus a few  corrections

### CODE REVIEW

**Comment by claudinepeyrat06** [comment]
hopefully will add more fonts in a few days...

**Comment by bkmgit** [comment]
There is contact information for Grand Hotel font available at https://fonts.google.com/specimen/Grand+Hotel/about perhaps see if the name 'Ink/Stitch Grand Hotel' can be used?  It may be helpful to indicate the origin in the license and the description.  There are many cases where one wants to embroider a font that is very similar/the same as a regular font.

**Comment by claudinepeyrat06** [comment]
Marie Françoise asked  for permission but got no answer . The name of the original font is in the LICENSE file. So to be on the safe side, Grand Hotel is now Auberge......

**Comment by lexelby** [comment]
Thank you for trying to ask for permission!

**Comment by claudinepeyrat06** [comment]
all these changes   are in claudine/may23_fonts

**Pull request closed without merging**
