### PR TITLE
bug fixes

### LINKED ISSUE #216: No handlers could be found for logger "shapely.geos"
IMHO this should produce a message to the user telling him/her to simplify path, e.b. break it up into smaller polygones (if that is the problem). I attached the zip of the SVG. 

I also found a workaround. 
- In Fill and Stroke, Fill tab, tick the "Fill solid ..... " icon 
- Fill again with the paint bucket. This will create a new path
- Kill the old path

No handlers could be found for logger "shapely.geos"
Traceback (most recent call last):
  File "inkstitch.py", line 20, in <module>
    if script_name.endswith('.py'):
  File "inkscape-0.92.2/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/embroider.py", line 83, in effect
  File "lib/extensions/base.py", line 196, in elements_to_patches
  File "lib/elements/element.py", line 257, in embroider
  File "lib/elements/auto_fill.py", line 129, in to_patches
  File "lib/stitches/auto_fill.py", line 21, in auto_fill
  File "lib/stitches/fill.py", line 139, in intersect_region_with_grating
  File "site-packages/shapely/geometry/base.py", line 620, in intersection
  File "site-packages/shapely/topology.py", line 70, in __call__
  File "site-packages/shapely/topology.py", line 38, in _check_topology
TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f20b0cce8d0>

[moth-bug.svg.zip](https://github.com/lexelby/inkstitch/files/2141202/moth-bug.svg.zip)

[moth-bug-fixed.svg.zip](https://github.com/lexelby/inkstitch/files/2141516/moth-bug-fixed.svg.zip)

FYI: My motivation for doing this: A co-worker wanted her drawing stitched. I got it done with a commercial program and wanted to see how much work it would require to get it done with Inkstitch. https://www.instagram.com/p/BkdGy1gHg93/?hl=en&taken-by=daniel.k.schneider

### LINKED ISSUE #217: Auto Underlay Ignored for Changed Paths
I discovered what I believe is a minor bug. I think the best way to describe it is to explain how I discovered it. 

I had a design with "Auto Underlay" enabled on the "Params" dialog. The design stitched as expected and it came out beautifully with all of the expected underlays.  I then changed one of the path objects by selecting two overlaying paths and doing an Inkscape  Path->Difference operation to subtract one path from the other. I then selected Embroidery->Params again. I verified that the "Auto Underlay" option was still selected and in the preview window I noticed that the path object that I had modified did not show the underlay for only the changed path.  All other paths had the underlay as expected. Just to verify, I sent the .pes file to the sewing machine and it did indeed not do the underlay under only the changed object.  I went back to the "Params" dialog and deselected "Auto Underlay" and then re-selected "Auto Underlay".  After doing this, the preview window showed the underlay under the changed path as well as all of the other paths.  Sending the new .pes file to the machine produced a design with underlay under all expected areas.  So it seems that if you change a path while "Auto Underlay" is enabled, the code will ignore auto underlay for the changed path when producing the stitch plan.

### LINKED ISSUE #220: Index out of range message when d attribute is empty in a path
Extension -> Embroidery -> Embroider...
When "d" is an empty string I get an out of range error. I don't know how one can create a path with nothing inside. I found this element in a file with lots of paths, i.e. I was able to create a stitch file with all selected elements on the screen, but not with all selected elements in the objects list. Also Embroidery -> Params does work.

    <path
       embroider_trim_after="True"
       embroider_zigzag_underlay="False"
       embroider_contour_underlay="False"
       embroider_center_walk_underlay="False"
       embroider_satin_column="False"
       embroider_repeats="2"
       id="path5478"
       style="fill:none;stroke:#000000;stroke-width:0.28098291"
       d=""
       inkscape:connector-curvature="0" />

Traceback (most recent call last):
  File "inkstitch.py", line 20, in <module>
    if script_name.endswith('.py'):
  File "inkscape-0.92.2/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/embroider.py", line 83, in effect
  File "lib/extensions/base.py", line 198, in elements_to_patches
  File "lib/elements/element.py", line 264, in embroider
  File "lib/elements/stroke.py", line 142, in to_patches
  File "lib/elements/stroke.py", line 46, in paths
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/element.py", line 206, in parse_path
  File "lib/elements/element.py", line 202, in path
  File "inkscape-0.92.2/share/extensions/cubicsuperpath.py", line 163, in parsePath
  File "inkscape-0.92.2/share/extensions/cubicsuperpath.py", line 150, in CubicSuperPath
IndexError: list index out of range

Attached the example that shows why an error message giving the offending path ID would be nice: Look at path5478 (in the end of object list and beginning of XML file), also the one next to it. Finding these requires either simple XML skills or "divide and conquer", but some folks may not have that.

[Hershey-sans-table-1-with-2-emtpy-d-attributes.zip](https://github.com/inkstitch/inkstitch/files/2160355/Hershey-sans-table-1-with-2-emtpy-d-attributes.zip)

PS: I don't know where these elements came from. The paths are originally from the Inkscape Hershey font generator.

### LINKED ISSUE #279: Windows directory path issue
When I run "Embroidery...", Windows goes to write the pes file and chokes.  It looks like it's doubling all of the Backslashes..
I put "C:\Users\%USERNAME%\Documents\Embroidery\" in the Directory field.

```
Traceback (most recent call last):

  File "inkstitch.py", line 24, in <module>

    binary_name = script_name

  File "inkscape-0.92.3\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\embroider.py", line 85, in effect

  File "lib\output.py", line 114, in write_embroidery_file

  File "site-packages\pyembroidery\PyEmbroidery.py", line 593, in write

  File "site-packages\pyembroidery\PyEmbroidery.py", line 541, in write_embroidery

IOError: [Errno 2] No such file or directory: 'C:\\Users\\%USERNAME%\\Documents\\Embroidery\\Quik Massage Logo - Embroidery.pes'
```

### PR DESCRIPTION
**Pull request by lexelby**
I tried to knock off as many bugs as I could:

* helpful error message for empty path "d" attribute (fixes #220)
* fix broken image icon in windows "install add-ons" extension
  * ...by simply not displaying an icon.  Not sure how to correctly fix this.
* useful error message when writing embroidery file fails (fixes #279)
* support `~/`, `$ENV_VARS`  and `%vars%` (on Windows) in Embroider output directory (#279)
* add change indicator to Params (fixes #217)
* stop showing "None" in Params
* name AutoFill tabs consistently
  * main tab was "Auto-Fill" but underlay was "AutoFill Underlay"
* add error message for invalid geometries (fixes #216)
* make error messages more useful
  * things like "satin column: one or more rungs does not intersect both rails" now have the object id

The most interesting one is the change indicators in Params.  This came out of the discussion in #217 and a couple other issues I can't remember.  I think @x3msnake or @AkiraNorthstar was involved.  The question is, if you don't change a setting in the Params window, should that setting still be applied to the selected objects?

A pretty good argument was made that whatever is shown in the UI should be applied to objects when you click "Apply and Quit".  The problem is when you select multiple objects with different settings.  I've had situations where I had varying pull compensation settings for different satins, but I wanted to set their underlay settings all at the same time.  If I select objects with varying pull compensation and change only the underlay settings, I definitely don't want my carefully configured pull compensation settings to be modified!

Then again, #217 shows us that it can also be confusing if unmodified settings _aren't_ applied.

I chose to solve this by surfacing in the UI the state of a parameter, showing whether or not it has been modified.  When you modify a parameter, a little pencil icon shows up in the left margin.  A tooltip explains that this parameter will be saved when you click "Apply and Quit".  It's actually a button, and you can click the button to force the pencil to appear for a field.

The pencil icon started out as a public domain icon from [OpenClipart](https://openclipart.org), and I modified it to look a little nicer in our UI.

change_indicators

Hopefully this feature makes everything more clear to the user.  I'd love to hear feedback on what folks think.  @mskressin, I'm especially interested in what you think of this as a possible solution to your difficulties in #217.

### CODE REVIEW

**Comment by AkiraNorthstar** [comment]
@lexelby i've tested this version, but i have trouble with it. Object is already converted to Path. Params shows following dialog:
ink_error_new_all
Any thoughts?

**Comment by lexelby** [comment]
Huh, weird.  Could you post that SVG here?

**Comment by AkiraNorthstar** [comment]
Here it is : [drawing.svg.txt](https://github.com/inkstitch/inkstitch/files/2343691/drawing.svg.txt)
I also deleted ~./config/inkscape and  ~./config/inkstitch, without success.

**Comment by lexelby** [comment]
That's really strange... it works fine here.  I'll delve in deeper later today.  Hmmmmm.

**Comment by AkiraNorthstar** [comment]
In the meantime, I will reinstall fedora28 (not because of inkstitch alone). Maybe I tested something (like conda-forge, pipenv, etc) that affects inkstitch and/or inkscape.
I will tell you afterwards - if the error still exists, or it was fedora, or my installation.
Since no one else has reported so far, I assume that it may be due to the (my) configuration.
We will see...

**Comment by AkiraNorthstar** [comment]
@lexelby 
Report: After the new installation (without updates) and after new installation (with updates) this error still occurs. Therefore, I would like to continue testing. Is there a way to individually test the above commits? The thing is, that when I start inkscape in a console, there is no error. Params is started, either the error message comes up or no message appears.
Do you have any idea how I can narrow down the problem?

**Comment by lexelby** [comment]
I'm able to reproduce something weird on your file when I use the packaged release version.  When I run Params, it just does nothing; no error message.  That's pretty close to what you're seeing, so how about I work on fixing this before you continue spending time debugging.  Hopefully I fix your problem while I'm in there.

Does Embroider work okay for you?

**Comment by AkiraNorthstar** [comment]
> That's pretty close to what you're seeing, so how about I work on fixing this before you continue spending time debugging.

That would simplify it for me ;)
Embroider and the simulation works, only params don't want work.
I have the impression that params works until it comes to the display of the dialogue.

**Comment by AkiraNorthstar** [comment]
I was able to narrow down the error.
If I compile inkstitch without [e2b5e96](https://github.com/inkstitch/inkstitch/pull/301/commits/e2b5e968340aeab55c4b7c280946640fb3131107), then it works!

**Comment by lexelby** [comment]
Thanks, that's really helpful!  I'm fairly certain the problem is in loading the new pencil icon.  I'll take a look.

**Comment by lexelby** [comment]
Yup, that fixed it.

**Pull request merged**
